### ISSUE TITLE
Order List

### ISSUE THREAD

**Issue by jleandroperez** [woocommerce/woocommerce-ios#1]
## Stories / Tasks

- [ ] Order List View #3
- [ ] Order List View: Table Section Headers #7
- [ ] Order List: Wire Up to FluxC #25

## Epic Story

As a store owner I want to see all past and incoming orders within the app so I can fulfill them, and see the order types and amount.

From MVLP document: Quickly list out orders that is contextually important - when I want to fulfill orders show unfulfilled, let me search, see important details like customer information, where to ship it, what’s included, and any notes associated.

## Details:
Implement the Order List interface. We should deal with:

- Grouping by date.
- Rendering each order's top level data.
- Deal with the *details* transition.
- **UISearchController** support.

## Notes:
Authentication, networking, and live data feed will be dealt with later on. At this stage, let's work with mockup data.

## Live Sample:
[Available here!](https://automattic.invisionapp.com/share/MPFWR3DWFHU#/screens/279967471) courtesy of @olaolusoga (loved it!!!).

## Mockup:
![4-0-orders](https://user-images.githubusercontent.com/1195260/36918561-11675dc0-1e39-11e8-9c6d-27cabb770f77.jpg)
