### ISSUE TITLE
Product description AI: The generated message doesn't use the correct language.

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#10103]
Despite working previously, the current prompt for product description seems to have an issue with language detection again:

https://github.com/woocommerce/woocommerce-ios/assets/5533851/45db0799-9382-4134-b9e8-a42ab32135a6

**Comment by 0nko** [comment]
We have the same issue on Android.

**Comment by itsmeichigo** [comment]
@selanthiraiyan Suggested in our team call today that we can try adding a separate prompt to detect the language and use it for another prompt for generating content. We can try this solution to see how it works.

**Comment by selanthiraiyan** [comment]
Task breakdown 

- [x] Add a separate prompt to identify language #10169
- [x] Clear identified language if user voted down in Feedback banner #10177
- [x] Use language code instead of name #10179
- [x] Track the identified language #10179
