### ISSUE TITLE
Local notification: Add notification to survey 24 hour after free trial subscription without plan purchase

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#10266]
Notification content: 

> Title:  💡Help Us Understand Your Subscription Decision
Description: We’re interested in your decision-making journey. Could you please tell us about your current status?

Tapping on the notification should direct to a new screen similar to the profiler questions with the following content:

 > Help Us Understand Your Subscription Decisions. Your feedback matters.
1. I am still exploring and assessing the features and benefits of app.
2. I am evaluating and comparing your service with others on the market.
3. I am part of a team, and we need to make the decision collectively.
4. I am evaluating how to best integrate this service into my business operations.
5. Other (please specify).

Behavior (summarize from the discussions above but with light tweaks): 
– Tapping the notification will open a new screen inside the app, similar to the one used for profiler questions.
– There should be a button to send the answer to Tracks for analytics or to dismiss the screen.
– If merchants tap #1 (I am still exploring…), we schedule a notification in 3 days that says:

> Title: 🧭 Still Exploring WooCommerce?
Body: No rush, take your time! If you have any questions or need assistance, we're always here to help. Happy exploring!

Tapping on this notification should just navigate to the app home screen.

Internal discussion: pe5sF9-1Ja-p2

**Comment by selanthiraiyan** [comment]
- [x] Add this new notification #10324
- [x] Add survey screen #10319
- [x] Show survey upon tapping notification #10328
    - Submit feedback using tracks events
    - Add unit tests for the view model
- [x] Schedule another notification after 3 days if selected "I am exploring..." option #10331
- [x] Enable feature flag to release feature #10344
- [x] Safely remove existing 24h after subscription notification #10345
- [x] Remove 24h after subscription notification remote feature flag
    - [x] Remove the remote flag from the backend D117388-code
    - [x] Remove iOS remote feature flag parsing code #10347
