### ISSUE TITLE
Store Creation: Remove web version

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#10327]
Since we've enabled free trial for all merchants, store creation with web view is now deprecated.

- [ ] Remove web store creation #10360 
- [ ] Remove IAP plan check #10360
- [x] Remove `storeCreationMVP` feature flag. #10357
- [x] Remove `freeTrial` feature flag. #10358
- [ ] Remove `storeCreationM2` feature flag and enable related code path by default. #10362
- [ ] Remove `storeCreationM2WithInAppPurchasesEnabled` feature flag. #10362 

Internal discussion: p1690167196145379-slack-C03L1NF1EA3.
