### ISSUE TITLE
Optimize profiler question

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#10374]
pecCkj-SO-p2

- [x] The profiler question screens
    - [x] #10376
    - [x] Update navigation as per the new flow 
        - [x] #10401 
        - [x] Make new profiler flow default #10471
    - [x] Collect, store and upload answers
        - [x] #10385
        - [x] Upload answers from dashboard #10473
        - [x] #10478
        - [x] #10386
        - [x] #10525
    - [x] #10409
    - [x] #10422
    - [x] Polishes
        - [x] Check about removing the async requirement for the `continueButtonTapped ` method. #10486
        - [x] Remove hosting controllers for individual profiler question views #10486
        - [x] Update [check](https://github.com/woocommerce/woocommerce-ios/blob/e913d1d07dc293d1a67dead5a4391f7c1ef72386/WooCommerce/Classes/ViewRelated/AppCoordinator.swift#L435-L441) for store creation start. 
        - [x] Unit tests for `StoreCreationProfilerQuestionContainerViewModel`. #10475 
        - [x] #10488
- [x] #10421
- [x] #10451
- [x] “Name your store” task in the Onboarding task list
    - [x] #10463
    - [x] #10453
- [x] Look into tracking from the design P2 post pecCkj-SO-p2#tracking
- [x] Change how we track `store_installation` step #10495
- [x] #10390
- [x] #10492
- [x] #10534
- [x] #10490

**Comment by itsmeichigo** [comment]
Closing as all subtasks have been completed.
