### ISSUE TITLE
Send it using a Jetpack request once the site is ready  pe5sF9-1NZ-p2#comment-2639

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#10385]
- Store the profiler answers in user defaults
- Add a network call in SiteRemote to submit answers
- This request should be sent after the site is ready and the user lands in the dashboard
- Clear the stored answers from user defaults on receiving a successful API response

Tasks
- [x] Network request to send profiler answers #10459
- [x] Usecase to store and upload answers #10460

Once this feature is ready for release
- [x] Remove code for sending profiler info in `enableFreeTrial` network request and remove `SiteProfilerData` model #10477
