### ISSUE TITLE
Product Bundles support during order creation

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-ios#10428]
Adding product bundles' support during order creation will provide a consistent experience for merchants, and it could increase the app’s revenue and engagement.

> Need to support variable items, composite items, and bundled items. I can add these to the order via the website and the order shows up correctly in the app, but I can’t add them to the order via the app because they show up as $0.00 items.

## Subtasks

```[tasklist]
### Add attributes to `ProductBundleItem` for configuring a bundle product
  - [x] Storage layer https://github.com/woocommerce/woocommerce-ios/pull/10826
  - [x] Yosemite layer https://github.com/woocommerce/woocommerce-ios/pull/10827
  - [x] Networking layer https://github.com/woocommerce/woocommerce-ios/pull/10827
```

```[tasklist]
### UI/UX integration
- [x] In order form, add a Configure CTA to a bundle product when its bundle items are non-empty behind a feature flag https://github.com/woocommerce/woocommerce-ios/pull/10985
- [x] Show a configuration screen with v0 design https://github.com/woocommerce/woocommerce-ios/pull/10996
- [x] Add/update bundle product from the configuration remotely https://github.com/woocommerce/woocommerce-ios/pull/11004
- [x] Set the min/max quantity rules to the quantity stepper https://github.com/woocommerce/woocommerce-ios/pull/11008
- [x] Update product selector in order form: add a disclosure icon to a bundle product, and tapping on it navigates to the configuration screen. The bundle products' child order items shouldn't be selected in the product selector Pe5pgL-3Vd-p2#product-selector-changes https://github.com/woocommerce/woocommerce-ios/pull/11034
- [x] [Auto-checked - fixed probably by Peacock] Handle the case when creating an order before updated order items with bundled items come back (it results in unexpected extra items): consider disabling the Create CTA until items are updated remotely
- [x] Configuration screen: validate all bundle items and show error message https://github.com/woocommerce/woocommerce-ios/pull/11018
- [x] Given the design update on order form product card pecCkj-RY-p2, we need to come up with a different design to display the child products of the parent bundle product https://github.com/woocommerce/woocommerce-ios/pull/11038
- [x] Handle error loading products on the configuration screen https://github.com/woocommerce/woocommerce-ios/pull/11066
- [x] Analytics https://github.com/woocommerce/woocommerce-ios/pull/11069
```

```[tasklist]
### Support variable bundle items
- [x] Support syncing a subset of variations https://github.com/woocommerce/woocommerce-ios/pull/10990
- [x] For any variation attributes that are "Any", offer a UI to select the option https://github.com/woocommerce/woocommerce-ios/pull/11058
- [x] Pass an existing variation & attributes to the configure form https://github.com/woocommerce/woocommerce-ios/pull/11058
- [ ] Test when a variable bundle item has no variations
```

```[tasklist]
### Design updates
- [x] Configure screen: loading screen while loading products https://github.com/woocommerce/woocommerce-ios/pull/11066
- [x] Update design based on design feedback pe5pgL-3Vt-p2: pe5pgL-3Vt-p2#comment-3172 https://github.com/woocommerce/woocommerce-ios/pull/11038
```

```[tasklist]
### Design feedback: Product selector & configure screen pe5pgL-42P-p2#comment-3267
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11256
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11259
- [x] Disable “+” and “–” buttons when limits have been reached. https://github.com/woocommerce/woocommerce-ios/pull/11204
- [x] Don’t show steppers until product has been selected.
- [x] Don’t show variation button until product has been selected. Tidy up the layout of this button, and change it to “Choose variation”. Related: #11235
```

```[tasklist]
### Design feedback: Order creation screen pe5pgL-42P-p2#comment-3267
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11249
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11250
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11251
```

```[tasklist]
### Design feedback: Order details screen pe5pgL-42P-p2#comment-3267 
- [ ] Use the same structure for the product details as the order creation screen, with a few differences:
- [ ] Don’t wrap them in a card, and remove the chevrons (except on the parent bundle product).
- [ ] Don’t add any borders between the child products (it’s the chevrons that make these necessary this on the creation screen).
- [ ] Don’t show stock levels (I’m not sure why we don’t do this here, but I don’t want to mess with it right now).
- [ ] Keep the chevron in the top right for the parent bundle product, but use it to show/hide the children. I think, for now, show all children by default.
```

TODO: check the latest QA feedback pe5pgL-3Ze-p2#comment-3347 and add subtasks that are applicable.

- [ ] QA feedback pe5pgL-3Ze-p2#comment-3216
  - [ ] Issue 3: hide the checkmark from the variation selector so that it doesn't look like a variation can be deselected
  - [ ] Issue 5: remove child bundled order items when the parent order item is removed
 
```[tasklist]
### Other fixes from testing
- [ ] #11157
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11201
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11159
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11177
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11193
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11198
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11232
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11329
- [ ] Configuration form: for variable items with a selected variation with "Any" attributes, the picker  should either pre-select the displayed option or show a different text for the default option (ref: https://github.com/woocommerce/woocommerce-ios/pull/11330#pullrequestreview-1758003025)
```

```[tasklist]
### Known issues
- [ ] Edge case: when creating an order, attributes with "Any" aren't saved properly like during the order update
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11136
- [x] Edge case: when updating an existing bundle, if there are no outstanding changes it shouldn't trigger another order sync https://github.com/woocommerce/woocommerce-ios/pull/11066
```

**Comment by jaclync** [comment]
Now that we've moved to other tasks, the remaining tasks were moved to a separate issue https://github.com/woocommerce/woocommerce-ios/issues/11531 so that this issue can be closed.
