### ISSUE TITLE
Gift cards support during order creation

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-ios#10518]
Adding gift card support during order creation will provide a consistent experience for merchants, and it could increase the app’s revenue and engagement. This task is about researching if this support is possible, drafting a design inspired on wp-admin interaction, and developing an implementation.

> Need to support variable items, composite items, and bundled items. I can add these to the order via the website and the order shows up correctly in the app, but I can’t add them to the order via the app because they show up as $0.00 items.

## Refs

- [API doc](https://woocommerce.com/document/gift-cards/rest-api-reference/)
- Code format: Unique gift card code in XXXX-XXXX-XXXX-XXXX format ([ref](https://woocommerce.com/document/gift-cards/store-owners-guide/#importing-exporting-gift-card-codes))
- Design request p1695028162140249-slack-C0354HSNUJH

## Subtasks

- [x] UX v0 pe5pgL-3Hl-p2 https://github.com/woocommerce/woocommerce-ios/pull/10732
- [x] Support editing a gift card code https://github.com/woocommerce/woocommerce-ios/pull/10732
- [x] Only show the CTA when the plugin is active https://github.com/woocommerce/woocommerce-ios/pull/10746
- [x] Show the applied gift cards in order form https://github.com/woocommerce/woocommerce-ios/pull/10743
- [x] Validate gift card format https://github.com/woocommerce/woocommerce-ios/pull/10753
- [x] [Time-box] Gift card code scanner with text recognition https://github.com/woocommerce/woocommerce-ios/pull/10769
- [x] Disable gift card usage when order total is 0 https://github.com/woocommerce/woocommerce-ios/pull/10758
- [x] Handle errors https://github.com/woocommerce/woocommerce-ios/pull/10751
  - Handle invalid gift card:
```
{
	"error": "woocommerce_rest_gift_card_cannot_parse_data",
	"message": "Gift card code 1212 not found."
}
```
  - Applying a gift card when the order total is zero results in an error: 
```
{
  "error" : "woocommerce_rest_gift_card_cannot_apply",
  "message" : "Requested amount for gift card code ZU3A-HW9W-GVAJ-W9AA exceeded the order total."
}
```
  - Handle applying a gift card with 0 balance when the order total is positive - this results in success without the gift card applied https://github.com/woocommerce/woocommerce-ios/pull/10732#pullrequestreview-1633647176

- [x] Design updates w3JBReW1UJesCf02sj43kR-fi-513_7930

### Analytics

- [x] Analytics https://github.com/woocommerce/woocommerce-ios/pull/10759

Event | Properties | Triggers
-- | -- | --
order_form_add_gift_card_cta_shown | flow: creation/editing | When the Add Gift Card CTA is shown in the order form (the site has active Gift Cards plugin).
order_form_add_gift_card_cta_tapped | flow: creation/editing | When the user taps the Add Gift Card CTA in the order form.
order_form_gift_card_set | flow: creation/editing, removed: Bool (whether the gift card is removed) | When the user sets the gift card in the order form.
order_creation_success(EXISTING) | use_gift_card: Bool (whether a gift card is used) (NEW) |  
order_creation_failed(EXISTING) | use_gift_card: Bool (whether a gift card is used) (NEW) |  
order_sync_failed(EXISTING) | use_gift_card: Bool (whether a gift card is used) (NEW)
