### ISSUE TITLE
Add option to edit and delete product categories

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#10634]
(Cloned from 306-gh-woocommerce/woomobile-private)

It would be useful for users to be able to edit and delete product categories from the app.

To-do:

- [x] Update Networking and Yosemite layers to support updating and deleting categories. #10635 
- [x] Support deleting categories. #10643 
- [x] Support updating categories. #10648
