### ISSUE TITLE
Eligibility check

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#10689]
Check `ai-assistant` feature availability from `me/sites` response.

Update Networking and Storage layers to read this info and add it to `Site`

More details 
p1694608029232419/1694598270.681329-slack-C03L1NF1EA3

pe5sF9-1H4-p2#comment-2759

- [x] Networking layer: Parse active features #10694
- [x] Update core data model: Store active features #10697
- [x] Add eligibility checker class #10700
- [ ] Use eligibility checker in coordinator #10710
