### ISSUE TITLE
Master Issue: Detect Jetpack Stats turned off

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1070]
Detect when Jetpack site visitor stats are turned off and quiet errors. 

- [x] Detect when Jetpack site visitor stats are turned off.
- [x] Mute all of the error messages coming from the turned off module. #932 
- [x] Remove the "Visitors" subview (reported in the My store > Dashboard). #838
- [x] Attempt to reproduce bug #823. Verify these fixes work and close the bug. #823

**Comment by jaclync** [comment]
On detecting this Jetpack module disabled error: I'm thinking about changing [how we handle sync errors in `DashboardViewController`](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift#L244) from just displaying an error toast to handling the sync error. In the sync error handler function, this particular jetpack module disabled error can be identified by the error code `invalid_blog` and in this case we do something differently from other sync errors (displaying an error toast). I checked the API doc for `sites/visits` (I believe is [this one](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/stats/)), and the only other error scneario with the same error code is when `This blog does not have Jetpack connected` - which is impossible if the app is already logged in to a store and fetching stats. What do you think @mindgraffiti @ctarda ?

**Comment by mindgraffiti** [comment]
>  `This blog does not have Jetpack connected` - which is impossible if the app is already logged in to a store and fetching stats.

@jaclync a user can disconnect Jetpack at any time. HEs can also disconnect Jetpack, if it violates our policy on CBD sales. So it is possible for the user to appear logged in and to have previously fetched stats successfully, but be unable to now.

>handling the sync error

Right now, all Android does is ignore the error and show a blank view for stats. Did you have something special in mind, or were you referring to using the same solution?

**Comment by ctarda** [comment]
I think we should break the logic in two parts: first, the Remote attacking `stats/visits` [seems to provide an error specific to this case](https://github.com/woocommerce/woocommerce-ios/issues/838), a 404 with:

```
{"error":"invalid_blog","message":"This blog does not have the Stats module enabled"}
```

I think it would be nice if we could detect that error at the Remote level, and propagate it up to the UI. 

Even though this is a networking error, it has some significance in terms of UI behaviour, so I'd explore mapping it to an error in the Yosemite layer. Ideally, that would be a method in StatsStore, that checks the availability of stats and returns either a success or an error (which could be, for example, an enumeration with .unknown .notInstalled) 

The Store would declare and expose that error to the UI. 

That way we would decouple the way we behave in the UI from the way we figure out that the plugin is deactivated. 

Thoughts @mindgraffiti @jaclync ?

**Comment by mindgraffiti** [comment]
Oh, okay! I think that's what Jaclyn was getting at, but I didn't understand what she meant. That looks like a good plan.

**Comment by jaclync** [comment]
> a user can disconnect Jetpack at any time. HEs can also disconnect Jetpack, if it violates our policy on CBD sales. So it is possible for the user to appear logged in and to have previously fetched stats successfully, but be unable to now.

@mindgraffiti great to know! then we'd probably have to check both the error code and message to identify this Jetpack disabled error. Is it safe to assume that the error message would not change over time?

(According to the [API documentation](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/stats/), there are two errors that could return 404 response with `invalid_blog` error code:

> 404 | invalid_blog | This blog does not have the Stats module enabled
> 404 | invalid_blog | This blog does not have Jetpack connected

)

> Right now, all Android does is ignore the error and show a blank view for stats. Did you have something special in mind, or were you referring to using the same solution?

I'm planning on tackling this Master issue in two parts: 
- first to identify this Jetpack module disabled error at the Networking layer and propagate to the Yosemite layer, then from Yosemite layer back to how Dashboard handles the error - right now it displays and error alert, and I'm going to just do nothing in this first part.
- for the second part, I plan to try hiding the visitor stats UI like in [this comment](https://github.com/woocommerce/woocommerce-ios/issues/838#issuecomment-480947715). Perhaps we can also show a toast message letting the user know about the Jetpack module status, it might still be in the design backlog [from this comment](https://github.com/woocommerce/woocommerce-ios/issues/838#issuecomment-501894263)?

**Comment by jaclync** [comment]
> I think it would be nice if we could detect that error at the Remote level, and propagate it up to the UI.
> Even though this is a networking error, it has some significance in terms of UI behaviour, so I'd explore mapping it to an error in the Yosemite layer. Ideally, that would be a method in StatsStore, that checks the availability of stats and returns either a success or an error (which could be, for example, an enumeration with .unknown .notInstalled)
The Store would declare and expose that error to the UI.

@ctarda thanks for the suggestion! I forgot not to have this networking level implementation detail in the app/UI layer. From my understanding, I'd create two `Error` enums, one for the Networking layer and the other for the Yosemite layer. We detect the Jetpack module disabled error first at the Networking layer and propagate to Yosemite, then map the error to the Yosemite-level error and propagate that error from Yosemite to the app. Does that make sense?

**Comment by ctarda** [comment]
> I'd create two Error enums, one for the Networking layer and the other for the Yosemite layer. We detect the Jetpack module disabled error first at the Networking layer and propagate to Yosemite, then map the error to the Yosemite-level error and propagate that error from Yosemite to the app

That sounds perfect!

**Comment by mindgraffiti** [comment]
>then we'd probably have to check both the error code and message to identify this Jetpack disabled error. 

Sounds like a good plan!

>Is it safe to assume that the error message would not change over time?

That's correct, the API versions don't change over time -- new versions are introduced instead. So in this case it's perfectly fine to rely on the error code and the message.

**Comment by jaclync** [comment]
I just checked the issue with Shop Manager role (#823), and it looks like a Shop Manager receives `unauthorized` error for site visit stats, while a store Admin receives the Jetpack "site stats" module turned off error. Do you think we can handle `unauthorized` errors from site visit stats endpoint the same way we handle Jetpack module disabled errors (i.e. just hiding the visitor stats subview)?

From the [API documentation](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/stats/), there could be three types of unauthorized errors:
```
403 | unauthorized | User cannot access this private blog.
403 | unauthorized | User cannot access this restricted blog
403 | unauthorized | user cannot view stats
```

The error in the Shop Manager case is `403 | unauthorized | user cannot view stats` when the Jetpack module is on/off, however currently in `DotcomError` we don't decode the message field. We could add the message to the `DoctomError`'s `unauthorized` case, and only handle this particular error case with Shop Manager and leave the other two 403 unauthorized errors as in the API doc. What do you think? @mindgraffiti @ctarda

**Comment by mindgraffiti** [comment]
Do it 😀 

That sounds like an excellent plan!
