### ISSUE TITLE
Update product count in stores to filter out sample products

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#10711]
Following logic in pecCkj-Zo-p2#comment-506.

- [x] Networking: Update `Product` model with a new property `isSampleItem`. #10712 
- [x] Storage: Update `Product` entity with new attribute `isSampleItem` #10713 
- [ ] `AddProductCoordinator`: update `storeHasProduct` to filter out items with `isSampleItem` = true #10720
