### ISSUE TITLE
Handle creating new categories and tags

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#10841]
- [x] ~Support for creating bulk tags~ Implementation exists
- [x] Support for creating bulk categories #10846
- [x] Handle AIProduct in view model #10848
- [ ] Update AI generation to handle creating new tags and categories  #10864
