### ISSUE TITLE
Trigger login action with password input from QR Code data

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-ios#10843]
Depends on #10824 

```[tasklist]
### Tasks
- [ ] Once the QR code data coming from the QR Code Camera is available, we should trigger the login flow deciding if the app will use the WordPress.com account (if available), or use the Store credentials (if Jetpack is not available).
- [ ] Trigger the account login request
- [ ] Open the password input view and request the user to fill the WordPress.com password or Store credentials password
- [ ] Once the full login succeeds, open the app configured with the Selected site provided by the QR Code
```

## Context
We want to allow our users to fill in the credentials of a login flow through a QR code login action button. Those credentials should allow them to jump directly to the password input view, without the need to decide to login using a WordPress.com account or Store credentials.

This way, the QR Code login flow shall be:
1. Points the system camera of the phone to the Login QR code inside the web onboarding banner.
4. The QR Code opens a deep link to the Woo app, opening it
5. The deep link reading succeeds and offers the store credentials or WordPress.com account details.
6. With the login data available from the QR Code, the app jumps directly to the password input view, asking for the Store account login or WordPress account login.
7. The app login succeeds and we jump directly to the My Store section from the store that generated the QR Code.
