### ISSUE TITLE
[Passkeys]  Sign & Verify challenge in the device 

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#10856]
Depends on

- #10852
- #10855

# Context

With the API endpoints ready, the device needs to orchestrate the `Continue with security key` flow.

# Task

- [ ] Request a challenge from the server when the user taps on the "Continue with security key" CTA.
- [ ] Invoke the device's native SDK to sign the server challenge
- [ ] Submit the signed challenge to the server
- [ ] Exit the login flow with the authenticated access token.
