### ISSUE TITLE
Blaze optimization

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#10906]
Figma: mBhyoV7OPhFnOugxLy6SMS-fi-513-3184
P2: pecCkj-13f-p2

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/10907
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/10928
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/10933
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/10952
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/10951
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/10953
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/10955
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/10961
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/10954
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/10942
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/10966
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/10991
```
