### ISSUE TITLE
[Passkeys] Handle invalid security key error

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#10926]
# Context

A user with multiple passkeys stored could select an invalid passkey for the account they are trying to log in to.
We should identify this case and error locally before sending the passkey to the server.

# Task

- [ ] Before sending the passkey, check if the credential ID is part of the list of allowed credential IDs.
- [ ] If it is not part of it, show an "Invalid Key" error.
- [ ] After the error is dismissed, exit the flow to the previous screen.

# Copy
> Whoops, that security key does not seem valid. Please try again with another one.
