### ISSUE TITLE
Read-only Refunds: UI

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1099]
### Update the Order Details to display read-only information about a refund
- [x] Order Details: Display refunded amounts #1577 
- [x] Order Details: update Order Item cells with calculated quantities, totals, and sorting #1731 

### Add a full refund details screen
- [x] Refund Details: Navigate to Refund Details screen #1578 
- [x] Display Products and Quantity section #1681
- [x] Display Refund Details section #1697 

<img src="https://user-images.githubusercontent.com/1062444/71692247-f6e3d400-2d6e-11ea-9152-dbd149d2b955.png" width="350" />

### Add refunded product list screen
- [x] Products Refunded: Navigate to Refunded Products Detail screen #1700
- [x] Display Refunded Products & Quantity section and table cells #1703 
- [x] Add pull-to-refresh action #1716 
- [x] Support summarized products instead of "duplicate" product cells #1717 

<img width="649" alt="Screen Shot 2020-01-03 at 12 38 30 PM" src="https://user-images.githubusercontent.com/1062444/71742026-096d1480-2e26-11ea-8482-fcf8681600a8.png">

<img width="393" alt="Screen Shot 2020-01-03 at 12 37 26 PM" src="https://user-images.githubusercontent.com/1062444/71742033-0d993200-2e26-11ea-9ee8-0a36e2155ce6.png">

**Comment by shiki** [comment]
Looks like all of the items in the checklists have been completed so I'm moving this to Done. 🙂
