### ISSUE TITLE
Blaze: Hide the promote button if there is an existing campaign for the product

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#11035]
**Description**
During #10906 - we added a new button to suggest users promote their product with Blaze. 

We should check if the product has an active campaign already and hide the button if it does.
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11059
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11063
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11068
```

**Comment by itsmeichigo** [comment]
Closing in favor of #11562
