### ISSUE TITLE
Add an extra option for shipping for both simple and variable subscription products when free trial is not set.

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#11178]
<img width="700" alt="image" src="https://github.com/woocommerce/woocommerce-ios/assets/5533851/9e7ac56a-ca5f-4c09-87b1-63ae9edd8571">

There's an extra option in the Shipping section for simple and variable subscription products: "One time shipping". This is enabled only when free trial is not set for the subscription.
```[tasklist]
### Tasks
- [x] Add new option for One time shipping in Shipping section for subscription product types
- [x] Add new field for `ProductSubscription`, which will then be encoded as `_subscription_one_time_shipping` in `meta_data`
- [x] Update Core data entity for `ProductSubscription` to add the new attribute to store one time shipping info.
- [x] Encode payment sync date to enable/disable one time shipping toggle
- [x] Update Core data entity for `ProductSubscription` to add the new `paymentSyncDate` attribute
- [x] Parse and store payment sync month info in `ProductSubscription`
- [x] Check payment sync month info before supporting one time shipping setting
```

**Comment by selanthiraiyan** [comment]
@hichamboushaba shared the below message about when to enable this setting. p1700490449837929/1700490418.657119-slack-C03L1NF1EA3

> Just sharing some notes on how the option “one-time shipping” works for variable subscriptions:
> 1. Unlike all of the other subscription details, this field is attached to the parent product itself, and not the variations, so it should be editable from the shipping options of the product itself, and not the variations.
> 2. The condition will be enabled when these two conditions are both true:
>     1. None of the variations have free trial.
>     1. None of the variations have p1700221197567989-slack-C03L1NF1EA3.
