### ISSUE TITLE
Support creating and editing variable subscription products

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#11171]
```[tasklist]
### Tasks
- [x] Update product form for variable subscription products
- [x] Add default subscription for generated variations
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11213
- [x] (@hafizrahman) Update detail form for variations to include subscription details: free trial #11221
- [x] (@hafizrahman) Update detail form for variations to include subscription details: expiration date #11221
```
