### ISSUE TITLE
Install and set selected theme on the site

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#11323]
Internal - pe5sF9-2f9-p2#comment-3144

- [x] adding new theme install and activation endpoints to the networking layer. 
    - [x] Install theme #11430
    - [x] Activate theme #11434
- [x] Switch to the newly created store if the app is terminated/closed while waiting for store creation. (Can this from the app delegate?) #11478
- [x] Helper to handle the installation and activation of the theme #11443
    - [x] save theme id and site id and clear on success
    - [x] async method to install theme (app foreground cases)
    - [x] automatically install theme upon landing in dashboard
- [x] Check adding unit tests for `StoreCreationCoordinator` and `AppCoordinator`. #11488
