### ISSUE TITLE
[Order form] Refactor product row views and logic for product selector and order form

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#11357]
When we first implemented Order Creation on iOS, we used the same SwiftUI view (`ProductRow`) for both the product selector (“Add Product”) and for an order item in the order screen. Over time, those screens have diverged and now use different views for products/order items (`ProductRow` and `CollapsibleProductCard`, respectively).

We should disentangle these SwiftUI views (and their subviews) and view models. This will make it easier to work with them, and will help us resolve some cross-platform discrepancies and merchant confusion about the order form. (Example: Showing order items prices excluding tax, for clarity when adding discounts.)

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11360
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11368
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11382
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11378
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11396
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11412
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11392
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11423
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11425
- [x] Remove `ProductRowViewModel` from `CollapsibleProductCardViewModel` (at this point it shouldn't be required anymore)
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11389
```

Discussion: pe5pgL-45I-p2

**Comment by rachelmcr** [comment]
The last step of this task is user-facing and turns out to be more delicate than I anticipated. I'm opening a separate issue to track that work and saving it for another time: https://github.com/woocommerce/woocommerce-ios/issues/11455
