### ISSUE TITLE
[Deposits Summary] Update UI for web alignment

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#11528]
Context: p91TBi-aOZ-p2
Figma: 3E61T7yTgRY2BSPo697e2W-fi-35_1513
Android's update: https://github.com/woocommerce/woocommerce-android/issues/10401

**Tasks:**
- [x] Remove `x deposits` that is displayed underneath the Pending funds balance. This is no longer necessary as we’re not estimating future deposits based on how long funds pend for.
- [x] Remove existing calendar icon
- [x] Replace `LAST` wording with new calendar icon
- [x] Move `Funds become available...` string
- [x] `DEPOSITS` heading renamed to `LAST DEPOSIT` as we’re no longer showing an upcoming estimate.
- [x] Add separator to the bottom of the component
