### ISSUE TITLE
[iOS][Tablet Orders] Further design tweaks

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#11534]
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11548
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11543
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11545
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11553
```
