### ISSUE TITLE
[Performance] Improvements to API requests on app launch

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#11592]
A recent audit of the API requests made when the app launches identified a number of followup tasks:

```[tasklist]
### Tasks
- [x] Remove the references to A/B tests that are no longer running, so we don’t try to fetch their assignments unnecessarily
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/11594
- [x] Reduce the requests to sync Blaze campaigns to a single request (`GET /wpcom/v2/sites/{SITE_ID}/wordads/dsp/api/v1/search/campaigns/site/{SITE_ID}`)
- [x] Consider adding the request to sync Blaze campaigns to `AppStartupWaitingTimeTracker`
- [x] Reduce the requests to sync remote feature flags to a single request (`GET /wpcom/v2/mobile/feature-flags`)
- [x] Consider limiting how often we sync "What's New" announcements (e.g. only sync the first time the app is opened after upgrading to a new version)
- [ ] Consider limiting how often we sync remote feature flags (e.g. cache this response and only refresh it occasionally, similar to how we handle refreshing stats)
- [ ] Reduce the requests to fetch A/B experiment assignments to a single request
```

Audit: pe5pgL-4e2-p2

**Comment by rachelmcr** [comment]
> Reduce the requests to fetch A/B experiment assignments to a single request

This happens in three places:

1. When `WooAnalytics` is initialized
2. When we sync the account in `DefaultStoresManager.synchronizeAccount(onCompletion:)`
3. When we set the analytics opt-in/opt-out preference (`WooAnalytics.setUserHasOptedOut(_:)`) after syncing the account settings in `DefaultStoresManager.synchronizeAccountSettings(onCompletion:)`

This happens because we call `ServiceLocator.analytics.refreshUserData()` in each case, which requires refreshing the test assignments. Reducing the requests to fetch the test assignments will require reducing (consolidating) the places where we refresh user data.

**Comment by rachelmcr** [comment]
> Reduce the requests to sync remote feature flags to a single request

The improvements up to now have reduced this to two requests from different parts of the app:

1. When the blaze campaigns view is loaded in the dashboard
2. When the blaze eligibility is checked for the hub menu (when `HubMenuViewModel` is initialized, which happens when the main tab bar is loaded)

> Consider limiting how often we sync remote feature flags

I think ideally we would cache this so the request is only needed once when the app launches, but not persisted across app launches (in case the remote feature flag changes).

**Comment by rachelmcr** [comment]
> Consider limiting how often we sync "What's New" announcements

I thought this over but we probably don't want to change this without further discussion. Part of the flexibility of these announcements is the ability to launch an announcement at any time from remote, even if it's after a version is released.

**Comment by rachelmcr** [comment]
I've finished all but the last two tasks:

* Consider limiting how often we sync remote feature flags
* Reduce the requests to fetch A/B experiment assignments to a single request

I outlined these potential improvements in my comments above, but there are some reasons we might not want to prioritize working on them now:

* Both of these are requests to WPCom directly (not to the store) and the responses are returned very quickly.
* I don't have a lot of context for how remote feature flags are used and how frequently we expect them to change or how responsive we need to be to remote changes.
* We don't currently have any A/B experiments running, so we aren't making any requests for that at the moment.

Given the speed of these requests, there is relatively small benefit to reducing them compared to the potential complexity or risk of changing the current behavior. I'm going to skip them and close this issue as complete for now.
