### ISSUE TITLE
[Tablet Orders] Fix deeplink to Order Details when SplitViewOrders is enabled

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#11674]
When the `splitViewInOrdersTab` feature flag is enabled, Universal URLs such as `https://woo.com/mobile/orders/details?blog_id={id}&order_id={id}` only navigate to the Orders tab, but don't open the specific order.

This also affects order notifications, both displayed as a Notice in the app, or as a system notification when backgrounded.

The routing in MainTabViewController needs to be updated to take account of the WooTabContainerController use for the split view, rather than expecting a navigation controller as the container. See #11673 for context.

## Subtasks

- [x] Handle universal links in `OrdersSplitViewWrapperController` https://github.com/woocommerce/woocommerce-ios/pull/11718

### Split view specific issues

The following issues only happen when the split view is shown (two panes).

- [ ] Fix an issue where deep deep-linked order is overridden by the auto-selected order in `OrderListViewController.checkSelectedItem` in `viewWillAppear`

Repro steps:

- Prepare an order link in a separate app
- Switch to a different store from the store ID in the link
- Tap on an order universal link --> notice that the first order of the store is shown instead of the order ID in the link

https://github.com/woocommerce/woocommerce-ios/assets/1945542/7fecc721-3e80-470e-b0e7-abe1b945058e

- [x] Fix the order not appearing as selected in the primary view (order list) https://github.com/woocommerce/woocommerce-ios/pull/11729

Notice that the order ID in the two views do not match.

<img src="https://github.com/woocommerce/woocommerce-ios/assets/1945542/51225738-0466-49dd-84ab-355783eb6ab7" width="300" />
