### ISSUE TITLE
[Better Errors] App Passwords Explanation logic

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#11998]
## Tasks

- [ ] Wire the continue button to the app password login web page
- [ ] Wire contact support button
- [ ] Properly display why we couldn't login into the site. **Details TBD**

# Note: Share strings and details with the other platform

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
