### ISSUE TITLE
[Analytics Hub] Milestone 1 design feedback

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12035]
Changes based on design feedback:

- [ ] “See report” should be in sentence case.
- [ ] We usually add a break on the left of the dividing line above a button like this. [The example I found](https://href.li/share.cleanshot.com/SH5dv5SB) is from order details, but I’m sure there are more.
- [ ] This isn’t part of this project, but the date ranges at the top of the screen should use en-dashes (not hyphens).

![Image](https://github.com/woocommerce/woocommerce-ios/assets/8658164/b3f05116-f3fb-460e-bd03-0d068a8968e5)

Discussion: pe5pgL-4wy-p2#comment-3730

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
