### ISSUE TITLE
Blaze: Use v1.1 GET campaigns endpoint

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12120]
Start using v1.1 GET campaigns endpoint to load campaigns list

- [x] Networking layer add v1.1 endpoint #12121
- [x] Storage layer - New entity to store the response from v1.1 endpoint #12124
- [x] Yosemite and Woo layer #12127
    - [x] Add new action to BlazeStore to sync entities
    - [x] UI layer Use v1.1 endpoint to display the campaign list
    - [x] Remove other old Blaze endpoint usages and replace with v1.1 - Dashboard screen for example
- [x] Remove unused old endpoint-related code and core data models #12198
- [ ] Change `BlazeCampaignListItem`'s `Status` enum case types to match v1.1 #12207

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
