### ISSUE TITLE
[Products] Favorite section in product list

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12274]
- [x] Add a way to mark a product as favorite #12284
- [x] Display favorite products filter in product list screen #13995
- [x] Remote and storage code for synching favorite products using IDs #13998
- [x] Add logic to apply favorite product filter #14001
- [x] Add tracking #14597
- [x] Enable feature flag #14597
- [ ] Remove feature flag

Internal - pe5sF9-2vU-p2#comment-3466

#### Enhancements
- [ ] Show a star in product row for a favorite product
- [ ] Make the favorites filter into a toggle https://github.com/woocommerce/woocommerce-ios/pull/13995#pullrequestreview-2327738800

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by JorgeMucientes** [comment]
What's the status of this @selanthiraiyan, is this issue done? Can we close it and mark it as `Done`?

**Comment by selanthiraiyan** [comment]
Yes, we can close this as only the "Enhancements" work is left, and I don't think we will prioritise this anytime soon. Thanks, @JorgeMucientes!
