### ISSUE TITLE
[Better Errors] Connectivity Tool design adjustment

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#12298]
[Figma](https://www.figma.com/file/w3JBReW1UJesCf02sj43kR/Joe%E2%80%99s-Scratchpad?type=design&node-id=1938-6274&mode=design&t=MIBV1Bf3J9XDB2CV-0)

## UI

![Image](https://github.com/woocommerce/woocommerce-ios/assets/562080/c8f9b2c3-527c-4dfd-9c41-b78dbf18db00)

## Tasks

- [ ] Update UI to the new design
- [ ] Update texts (avoid using oops/whoops)
- [ ] Add a retry button to each step when failed.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
