### ISSUE TITLE
[Hub Menu] Customers section

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12294]
We want to add a Customers section to the Hub menu. Planning discussion: pe5pgL-4Ir-p2

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12296
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12297
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12309
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12314
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12316
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12334
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12342
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12346
- [ ] Bonus: If a customer is registered, fetch and display their phone number and billing/shipping address
- [x] Remove feature flag
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
