### ISSUE TITLE
Remove WooExpress sign-up

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12323]
pfwcF5-by-p2

```[tasklist]
### Login Changes
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12324
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12375
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12367
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12392
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12396
```

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12377
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12390
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12394
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12395
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12393
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12413
```

```[tasklist]
### Misc
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12442
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12412
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by itsmeichigo** [comment]
Code cleanup task is still open, but I'll close this main issue for now.
