### ISSUE TITLE
Stats v3/v4: handle corner cases

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1232]
Right now, we just check on the feature flag to decide which stats version to show. There are a few tasks for this master ticket:

**Task 1 - stats v4 eligibility check & saving the state of the last stats version**

- [x] In the following timing, check if the site is eligible for stats v4 (with WC admin activated as of writing, and a certain WC version when WC admin is merged into core) and then switch to show stats v4 if eligible and stats v3 otherwise:
- The user just logged in a store
- The user just switched to a different store
- The user launched the app while already logged in to a store
- The user pulls down to refresh the Dashboard

Note: check if the following user defaults tasks make sense to be in a separate high-level task
- [x] store the last stats version that is presented to the user into user defaults: `UserDefaults.Key.lastStatsVersion: String` of value `v3` or `v4`
- [x] use the user defaults value to show Dashboard first
- [x] reset the user defaults value on log out / store switch

**Task 2 - Stats v4 is not supported when it previously was**

- [x] when the currently shown stats version is v4 and then it's being switched to v3 after compatibility check, we show the following banner at the top of the dashboard
<img width="481" alt="v4-v3" src="https://user-images.githubusercontent.com/1945542/63578803-cbccc500-c5c3-11e9-9bf6-edf9e00a6cfb.png">

- [x] when user taps on "Learn more", we show the web page about WC admin: https://wordpress.org/plugins/woocommerce-admin/
- [x] if the user dismisses the banner, save this preference and we won't show the banner for the site again

**Task 3 - Stats v4 is now supported**

- [x] when the currently shown stats version is v3 and then it's eligible for v4 after compatibility check, we show the following banner at the top of the dashboard
<img width="458" alt="v3-v4" src="https://user-images.githubusercontent.com/1945542/63580291-13088500-c5c7-11e9-9e64-d5b6e6df93cf.png">

- [x] when user taps on "Try it now", we switch to stats v4

- [ ] add the new gift grid icon to `Gridicons-iOS`, use the new icon, and draw a red dot at the top right
- [x] if the user dismisses the banner, save this preference and we won't show the banner for the site again

**Task 4 - New setting to opt into beta features**
- [ ] add a beta section to app settings under feature flag
- [x] save stats v4 eligibility into user defaults `UserDefaults.Key.eligibleStatsVersion: String` of value `v3` or `v4` so that the check is the same as `UserDefaults.Key.lastStatsVersion: String` in Task 1
- [ ] if the user is eligible for stats v4, show the beta section like below
<img width="776" alt="stats-beta-setting" src="https://user-images.githubusercontent.com/1945542/63579891-34b53c80-c5c6-11e9-8fc1-57880dd78175.png">
