### ISSUE TITLE
Migrate from simple payments to order creation

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12387]
Design: uycU7BYzmc3vLKX0cuHLNk-fi-60_42572
Ref: pecCkj-1mt-p2#comment-737

```[tasklist]
### Tasks
- [x] Create a feature flag https://github.com/woocommerce/woocommerce-ios/pull/12388
- [x] Show the order form instead of simple payments when tapping on Payments > Collect Payment https://github.com/woocommerce/woocommerce-ios/pull/12388
- [x] Show a new bottom sheet after 0.5s https://github.com/woocommerce/woocommerce-ios/pull/12400
- [x] Show custom amounts modal when the user taps on `Add a custom amount` CTA https://github.com/woocommerce/woocommerce-ios/pull/12400
- [x] Handle payment methods navigation when tapping `Collect Payment` in the order form https://github.com/woocommerce/woocommerce-ios/pull/12419
- [x] Analytics https://github.com/woocommerce/woocommerce-ios/pull/12455
- [x] Update UI tests https://github.com/woocommerce/woocommerce-ios/pull/12450
```

<img width="1220" alt="Screenshot 2024-03-29 at 3 54 06 PM" src="https://github.com/woocommerce/woocommerce-ios/assets/1945542/cbb8fbc6-693b-4a3c-a6dd-ef9023bab544">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
