### ISSUE TITLE
Introducing landing page switch after Phone sync

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-ios#12496]
Once we're capable of fetching and receiving the store credentials, we should be able to move away from the syncing steps and send the user to the landing page. 

We won't introduce a store selector right now, instead, we will ensure that the phone app always communicate to the watch when a store changes.

This task should focus on detecting if the store credentials are available, and if true, send the user to the my store view, and if not, send the user to the device sync steps.

![Image](https://github.com/woocommerce/woocommerce-android/assets/5920403/1eece799-2462-4815-a478-a0ad65dd20e9)

```[tasklist]
### Tasks
- [x] Introduce logic to check if the store credentials are available
- [x] Initiate the My Store screen when store credentials are available
- [x] Initiate the Phone login screen when store credentials are not detected
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
