### ISSUE TITLE
Intercept New Orders notifications

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-ios#12505]
One of the main advantages of using the Watch app should be the more reachable notification presentation. We should be able to present a new Order notification coming from the phone app and ensure the Cha-ching sound is possible.

![Image](https://github.com/woocommerce/woocommerce-android/assets/5920403/8ee63fd7-4395-483d-802c-cdc45280075f)

```[tasklist]
### Tasks
- [x] Register the Watch app to receive notifications from the phone app
- [ ] Ensure the notification contains the `view order` and `dismiss` buttons
- [x] Handle the `view order` click opening the Order Details
- [ ] Ensure the Notification plays the cha-ching sound
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
