### ISSUE TITLE
Blaze Campaign Creation Ad Image Picker

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12540]
Clone in Android issue https://github.com/woocommerce/woocommerce-android/issues/11323

In the Edit Ad screen we currently don't provide the option for the user to directly pick an image from all the available images for the given product. 

Ideally, we'd like to offer a 4th option in this dialog, so that user can pick directly from the product images:

<img width="300"  src="https://github.com/woocommerce/woocommerce-ios/assets/524475/f37d2d78-0240-4d94-b1cd-387a4c304bfe"> 

---

#### Task breakdown
- [x] Support fetching media for specific product IDs in the Networking layer #13529
- [x] Add an option to MediaPicker to select Media from a specific product #13539
- [ ] Show option to pick from product images in Blaze Edit Ad screen

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
