### ISSUE TITLE
[SiOC - customer creation] Order form: implement card design for the customer section

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12592]
We decided on option 2 for now: pdfdoF-4KB-p2#comment-6021

Q9tkFMtymZz0yhfLLbKhig-fi-2180_72813

<img width="1389" alt="Screenshot 2024-04-30 at 3 53 25 PM" src="https://github.com/woocommerce/woocommerce-ios/assets/1945542/209b71ea-0fc7-47ac-8f56-76df3560a7ef">

```[tasklist]
### Foundation
- [x] Show the existing flow under the new feature flag with the title updated from `Add Customer Details` to `Add Customer` as a separate section above the `Add Note` section in order form https://github.com/woocommerce/woocommerce-ios/pull/12595
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12623
- [x] The customer section view model has two states: whether customer account is required, whether the customer is editable https://github.com/woocommerce/woocommerce-ios/pull/12650
```

```[tasklist]
### Subscription order states
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12617
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12618
- [ ] When customer account is required, add a Required badge to the `Add Customer` row
```

```[tasklist]
### Search
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12652
- [x] Add a search CTA above the collapsible customer card when the customer card is shown (an existing customer is set, or the merchant is editing the customer) https://github.com/woocommerce/woocommerce-ios/issues/12652
- [x] Tapping on the search CTA opens the existing customer search view, and selecting a customer from search will populate/override the customer details https://github.com/woocommerce/woocommerce-ios/issues/12652
```

```[tasklist]
### Customer card
- [x] Email header view & text field: if customer account is required, "Required" is shown in the placeholder in the header https://github.com/woocommerce/woocommerce-ios/pull/12650
- [ ] [Subscription specific] Email header view: a green text is shown about creating an account if the email is different from the remote one and the user enables customer creation
- [ ] Email: the email in the header view is updated and synced in editing mode when the email text field loses focus with validation
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12665
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/12658
- [ ] Bug fix: tapping `Remove customer from order` doesn't unset the email and phone number
- [ ] Bug fix: discard changes alert isn't shown when dragging to dismiss the address form with unsaved changes
- [ ] [Subscription specific] When the customer is not editable, hide the email text field / create account toggle / address pencil / Remove customer from order CTA
- [ ] Tech debt: add equivalent test cases where the feature flag is set to `false`
```

```[tasklist]
### Customer creation
- [ ] `Create new customer account` toggle: show a toggle. If a customer account is required, an error text is shown in red Q9tkFMtymZz0yhfLLbKhig-fi-2180_79790. If a customer ID is available for the order before, the toggle is hidden first and then shown when the merchant changes the email
- [ ] Editing mode: instead of syncing email after losing text field focus, a Save CTA is shown in the order form to update the order with the email
- [ ] Integrate with remote for both creation & editing modes
```

```[tasklist]
### 🚧 Pending design
- [ ] Whether to move the customer note to the customer card Q9tkFMtymZz0yhfLLbKhig-fi-2180_77418#786116416
- [ ] We might have a different design when the customer isn't set Q9tkFMtymZz0yhfLLbKhig-fi-2180_77418#786116416
- [ ] Recover existing customer Tracks events, e.g. `order_customer_add`
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by jaclync** [comment]
Closing, there's no plan to resume the customer creation project.
