### ISSUE TITLE
Setup WCiOS with Apple Watch module

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#12641]
## Tasks
```[tasklist]
- [x] Create feature branch
- [x] Add watch target
- [x] Make sure it runs on testflight
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by Ecarrion** [comment]
Requested profiles here pdnsEh-1DB-p2
