### ISSUE TITLE
[Woo POS] UI: Dashboard wireframe

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12703]
Ref: TfaZ4LUkEwEGrxfnEFzvJj-fi-6_1657

The dashboard should have the following UI components, all of them non-functional at the moment:
- [x] A custom navigation top bar with 3 toolbar items
- [x] Product list view
- [x] Cart view
- [ ] Search field view: https://github.com/woocommerce/woocommerce-ios/issues/12762
- [ ] Filter field view: https://github.com/woocommerce/woocommerce-ios/issues/12761
- [x] Product card view: https://github.com/woocommerce/woocommerce-ios/issues/12722
- [x] Product row view: https://github.com/woocommerce/woocommerce-ios/issues/12724
- [x] Checkout button

Ideally let's apply the colors from a common extension to `Color`, as we do through WooFoundation now for WooCommerce through `Color.withColorStudio()`. This can be tackled separately: https://github.com/woocommerce/woocommerce-ios/issues/12702

<img width="478" alt="Screenshot 2024-05-13 at 10 05 46" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/6d038676-e24f-4b53-841f-44fad4aae21c">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
