### ISSUE TITLE
[Min/Max Quantities] Implement UI

### ISSUE THREAD

**Issue by toupper** [woocommerce/woocommerce-ios#12718]
# Tasks
- [x] Add UI Editable support
- [x] Remove edit support notice
- [ ] Sync info
- [ ] Show row even if there are no quantities set. Check that it's not shown in case the plugin is not installed
- [ ] Nice to have: Done button disables when there are no changes
- [ ] Unit Tests

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
