### ISSUE TITLE
[Woo POS] Update entry point design

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12779]
Ref: p91TBi-beb-p2

<img width="615" alt="Screenshot 2024-05-20 at 08 36 08" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/933b9356-b574-419f-b34d-4bd2cd90c508">

```[tasklist]
### Tasks
- [x] Update the entry point CTA row design in the Menu tab (please focus on the `PointOfSaleEntryPoint: HubMenuItem` struct content update, as I am working on changing the POS location in https://github.com/woocommerce/woocommerce-ios/issues/12780 to avoid merge conflicts) https://github.com/woocommerce/woocommerce-ios/pull/12793
- [x] Fix pre-existing issue where one has to go to another tab and back after turning on the feature switch or when the eligibility changes https://github.com/woocommerce/woocommerce-ios/pull/12808
- [ ] Potential design updates from p91TBi-beb-p2 - change icon to swap back/forth
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jaclync** [comment]
I think we can break down the tasks by:

- [ ] Update the entry point CTA row design in the Menu tab (please focus on the `PointOfSaleEntryPoint: HubMenuItem` struct content update, as I am working on changing the POS location in https://github.com/woocommerce/woocommerce-ios/issues/12780 to avoid merge conflicts)

Regarding the red dot notifications:

> While I’ve included it here, I think this dot isn’t necessary to begin with. If we decide to launch this feature quietly in a beta, then we might prefer to use it to point people to an “enable” switch in Settings, or we might not want to draw attention to it at all.

We can still implement this first pending the clarification p91TBi-beb-p2#comment-12129:

- [ ] Potentially under a different feature flag if we might not launch it until slightly after MVP
- [ ] Red dot on the tab bar (we used to have this on the Menu/Reviews tab for new review notifications, can look for the PR that removes it)
- [ ] Red dot on the Menu button (probably similar to the dot from `HubMenuViewModel.shouldShowNewFeatureBadgeOnPayments`)
- [ ] Implement the red dot show/hide logic pending product requirements

**Comment by jaclync** [comment]
Update: as in p91TBi-beb-p2#comment-12137, we're not implementing the red dot notifications for now.

**Comment by iamgabrielma** [comment]
I think we can close this one @jaclync?

**Comment by jaclync** [comment]
There is one pending subtask for a design update added after the dev, to update the accessory icon with system symbol `arrow.left.arrow.right`:

what we have now | design
-- | --
<img width="901" alt="Screenshot 2024-06-21 at 9 14 49 AM" src="https://github.com/woocommerce/woocommerce-ios/assets/1945542/bbdcb88b-8757-4d94-bcd1-e4ef3509fdf4"> | <img width="691" alt="Screenshot 2024-06-21 at 9 14 59 AM" src="https://github.com/woocommerce/woocommerce-ios/assets/1945542/036ff1e5-2a51-44fc-bbb9-c8d3dd91bd61">

It's pretty quick I just haven't got the time 😅 I'll do it today just so that we can close this issue.

**Comment by iamgabrielma** [comment]
Ah, gotcha! I didn't see the icon update. Thanks for handling it 🙇
