### ISSUE TITLE
Last 3 orders card logic

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12792]
- [x] Load and display orders #12802
- [x] Load order statuses for filter from storage (to load custom statuses) #12847
- [x] Save and load last selected order status #12847
- [x] Unit tests for Last orders dashboard view model #12847
- [x] Handle navigation to list and individual orders #12851

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
