### ISSUE TITLE
[Woo POS] Mechanism to refresh product data

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12837]
Product data might change after the `POSProducts` have been initially injected into the dashboard. We need a sync mechanism, for example via by pull-to-refresh the product grid/list.

Tasks:
* [x] Update/create a remote to pull directly 100 simple products: https://github.com/woocommerce/woocommerce-ios/pull/13116/
* [x] Loading screen while await for the remote: https://github.com/woocommerce/woocommerce-ios/issues/13143
* [x] Sync/Pull-to-refresh: https://github.com/woocommerce/woocommerce-ios/pull/13149
* [x] Store/cache. TBD post-MVP: https://github.com/woocommerce/woocommerce-ios/issues/13142
* [x] Pagination. TBD post-MVP: https://github.com/woocommerce/woocommerce-ios/issues/13142

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kilbot** [comment]
Hi @iamgabrielma, I have spent many months working on the problem of replication and sync for WooCommerce: https://github.com/wcpos/query

I'm available for hire as a consultant! 😁 paul@wcpos.com

**Comment by iamgabrielma** [comment]
Hi Paul 👋! If you're interested in working with us I'd recommend to check https://automattic.com/work-with-us/

**Comment by bozidarsevo** [comment]
Should this issue be moved to "Done"?

**Comment by iamgabrielma** [comment]
> Should this issue be moved to "Done"?

Yeah I think we can, I was waiting for the "_Loading screen while await for the remote_" item, but design might take a bit to come back with this and we can move it forward with the dummy loading screen for now.
