### ISSUE TITLE
Dynamic Dashboard: Analytics

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12877]
- [x] Tracking events for M2 cards #12891
- [x] Tracking events for M1 cards #12922
- [x] Fix duplicate tracking events in Blaze card #12963

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by selanthiraiyan** [comment]
Reopening to fix duplicate tracking events in Blaze section.
