### ISSUE TITLE
[Woo POS] Using selected products create an order draft

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#13021]
From [this](https://a8c.slack.com/archives/C06C3CZFHGD/p1717769577752619) discussion in Slack:

Create an order
Add products to it
Order model is returned
It will contain everything we need
IF there are any modifications to the cart, we add to the order

```[tasklist]
### Tasks
- [ ] Update ViewModel for Order Creation
- [ ] get products
- [ ] Put into the model
- [ ] Handling API Integration
- [ ] do the request to create order upon tapping the checkout button
- [ ] Reuse existing code
- [ ] Update UI and View States
- [ ] Testing
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
Should we close this one as part of M1's wrap-up @bozidarsevo ?
