### ISSUE TITLE
Dynamic Dashboard: 19.0 Beta Feedbacks

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#13048]
Thanks to @JorgeMucientes for reporting these:

TBD
```[tasklist]
### Tasks
- [ ] Customize panel shows black bottom background (not grey) on tablet screen.
- [ ] **New cards notice**: the badge and the card suggesting there are new view are always there. Can’t get rid of them, not even after selecting several of the M2 cards.
- [ ] **Stock:** Empty case for Stock card is missing. When selecting a status that has no items, the generic error is displayed
- [x] **Last orders:** `Pending` status from differs from `Pending payment`. Status labels should be the same between both screens.
- [x] When tapping on the already selected filter options, the card is refreshing all the time. Imho selecting the same option should not trigger a refresh:
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by itsmeichigo** [comment]
> **Stock:** Empty case for Stock card is missing. When selecting a status that has no items, the generic error is displayed

This is the empty state for the Stock card when there are no items for a selected status. @JorgeMucientes could you share what's the expectation here? 

<img src="https://github.com/user-attachments/assets/f7b69b0b-a61f-4e1c-bc3e-797618bfbaa7" width=320 />

**Comment by itsmeichigo** [comment]
> Customize panel shows black bottom background (not grey) on tablet screen.

This is expected for list views on iOS.

**Comment by itsmeichigo** [comment]
> New cards notice: the badge and the card suggesting there are new view are always there. Can’t get rid of them, not even after selecting several of the M2 cards.

I cannot reproduce this on the 19.5 build from TestFlight.

**Comment by JorgeMucientes** [comment]
Hey @itsmeichigo about this: 

> This is the empty state for the Stock card when there are no items for a selected status. @JorgeMucientes could you share what's the expectation here?

I presume that is coming from this feedback: p1718207386514289/1718207019.391089-slack-C03L1NF1EA3
```
Empty case for Stock card is missing. When selecting a status that has no items, the generic error is displayed
```
![IMG_0215 (1)](https://github.com/user-attachments/assets/23b0363e-f455-4880-b1cb-d16650f76e63)

Back when I tested, I was seeing the generic error rather than the no items error.

**Comment by itsmeichigo** [comment]
Thanks @JorgeMucientes! I can't seem to reproduce the issue, there could be something wrong with the request at that time but not with the empty state. Please let me know when you come across the issue again.

**Comment by itsmeichigo** [comment]
I fixed the last two items in #13408, and the rest are either non-issue or non-reproducible. I'll close this issue for now, please feel free to leave any comment with more details if you can still encounter any of the remaining items.
