### ISSUE TITLE
Image selection

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13104]
- Update the text field button “Read text from product photo” to open the image selection/upload flow.
- The text field button should have options to view, replace and remove the photo.
- Please note that we must show a notice/toast message with an undo option when removing the photo.
- We should keep a reference to the selected image to later upload the image to the product.

Tasks
- [x] Add "Starting information" view and view model #13171
- [x] Select package image. #13193
- [x] Options to view and remove selected image. Show Notice with Undo option. #13213

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
