### ISSUE TITLE
Product Creation with AI: v2 - Milestone 1

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13103]
Version 1 - https://github.com/woocommerce/woocommerce-ios/issues/10688
Design - pe5sF9-2Nd-p2
Internal - pffQ75-yr-p2

### Endpoint migration
- [x] #12727

### Feature flag
- [x] #13154

### Create Order Sheet
- [x] #13160

### Starting information
- [x] #13104
- [x] #13105
- [x] #13106
- [x] #13107

#### General updates
- [x] #13238
- [x] Animation while generating and displaying content (Marking as done as there is no change needed to the existing  loading animation)
- [x] #13287

#### Photo section
- [x] #13246
- [x] Popup Menu to view or remove selected photo.
- [x] #13299

#### Name & Description
- [x] #13254
- [x] #13108
- [x] #13265
- [x] #13109
- [x] #13110
- [x] #13259

#### Details
- [x] UI updates to the details fields. (Making these fields editable will be handled in M2 https://github.com/woocommerce/woocommerce-ios/issues/13117) Done in https://github.com/woocommerce/woocommerce-ios/issues/13238

### Bugs
- [x] #11189
- [x] #13291
- [x] #13308

### Tracking
- [x] #13300
- [x] #13304

### Release
- [x] #13327
- [x] #13332
- [x] Enable "What's new" announcements (Both iOS and Android)
- [ ] Remove the feature flag. #14010
- [x] #13266 https://github.com/woocommerce/woocommerce-ios/pull/14010

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by itsmeichigo** [comment]
@selanthiraiyan Do we need to include uploading package photo as part of milestone 1 as well? I don't see that task in this list.

**Comment by selanthiraiyan** [comment]
> @selanthiraiyan Do we need to include uploading package photo as part of milestone 1 as well? I don't see that task in this list.

Good catch, Huong! I added a subtask for that under the "Photo section".
