### ISSUE TITLE
Product Creation with AI: v2 - Milestone 2

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13117]
Milestone 1 - https://github.com/woocommerce/woocommerce-ios/issues/13103
Design - pe5sF9-2Nd-p2
Internal - pffQ75-yr-p2

### Feature flag
- [ ] Add feature flag

#### Details
- [ ] Make "Price" field editable.
- [ ] Make "Inventory" field editable.
- [ ] Make "Categories" field editable.
- [ ] Make "Tags" field editable.
- [ ] Make "Shipping" field editable.

#### General updates
- [ ] "Publish" button and action

### Tracking
- [ ] Define tracking events. (If needed, create test funnels to ensure project success can be measured.)
- [ ] Add tracking events.

### Release
- [ ] Add release notes and enable feature flag.
- [ ] Remove the feature flag.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by selanthiraiyan** [comment]
We will wait until we measure how milestone 1 and 3 performs and decide whether to work on milestone 2.

**Comment by JorgeMucientes** [comment]
Can we close this? Is this a duplicated issue @selanthiraiyan ? Afaik all task related to product creation with AI where completed.

**Comment by selanthiraiyan** [comment]
Thanks, @JorgeMucientes! I am closing it now.
