### ISSUE TITLE
Product Creation with AI: v2 - Milestone 3

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13118]
Milestone 2 - #13117
Design - pe5sF9-2Nd-p2
Internal - pffQ75-yr-p2

### Feature flag
- [x] Add feature flag https://github.com/woocommerce/woocommerce-ios/pull/13269

### Improve seed prompt suggestions
- [x] UI - Progress bar and label with dynamic color and text. @pmusolino 
- [x] #13111
- [x] https://github.com/woocommerce/woocommerce-ios/issues/13295

### Misc
- [x] Moving text detection error above advice block. https://github.com/woocommerce/woocommerce-ios/pull/13335#pullrequestreview-2179491147 
    - Marking as done as we have changed the design of this screen in https://github.com/woocommerce/woocommerce-ios/pull/13403. 
- [x] #13384

### Tracking
- [x] Define tracking events. (If needed, create test funnels to ensure project success can be measured.) 
    - Done in p1721819695107559/1721819689.954159-slack-C03L1NF1EA3
- [x] Add tracking events. https://github.com/woocommerce/woocommerce-ios/pull/13411

### Release
- [x] Add release notes and enable feature flag. #13412
- [ ] Remove the feature flag. #14010

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
