### ISSUE TITLE
Dashboard card for Google ads campaigns

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#13230]
```[tasklist]
### Tasks
- [x] Add new card type for Google ads
- [x] UI for Google ads dashboard card
- [x] Fetch data for Google ads dashboard card
- [x] Navigation from Google ads dashboard card
- [x] Unit tests
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
