### ISSUE TITLE
[Woo POS] MVP Analytics

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13277]
Updated 2025-02-14: Task to track analytics events heading to POS MVP. 
* Final events are ready: pdfdoF-6hn-p2
* [Android's current POS event tracking](https://github.com/woocommerce/woocommerce-android/blob/trunk/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/util/analytics/WooPosAnalyticsEvent.kt).
* For MVP, we have 2 ways to track events: 
  * Existing events (eg: reader connection, card payments, etc, ..) that happens during POS mode, are simply decorated with a `_pos_` tag
  * New events (pdfdoF-6hn-p2) need new logic.

**TODO:**
- [x] Order events: https://github.com/woocommerce/woocommerce-ios/issues/13613
- [x] Payment events: https://github.com/woocommerce/woocommerce-ios/issues/13614
- [x] Miscellaneous events: #15018
- [x] Cart events: (added as part of 15018)
- [x] Resolve how we'll handle deep-in-payment-service events #15128
- [x] Log time intervals in event properties  https://github.com/woocommerce/woocommerce-ios/pull/15148
- [x] Cash events: https://github.com/woocommerce/woocommerce-ios/issues/15057
- [x] Card reader is ready post-order creation https://github.com/woocommerce/woocommerce-ios/issues/15150
- [x] Receipt events: (added as part of 15018)
- [x] Bug: https://github.com/woocommerce/woocommerce-ios/issues/15194
- [x] Implement success/failure receipt events https://github.com/woocommerce/woocommerce-ios/issues/15203
- [x] Confirm final events: https://github.com/woocommerce/woocommerce-ios/issues/15058

**Should have:**
- [x] Make allowedList: https://github.com/woocommerce/woocommerce-ios/issues/15058

**Nice to have:**
- [x] Improve POS tracking conformance https://github.com/woocommerce/woocommerce-ios/issues/15149

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
Updated: p91TBi-bNR-p2#comment-12826

We can start with: 
```
Payment Success card_present_collect_payment_success
Payment Flow Error: card_present_collect_payment_failed (error_type: string)
Product Added to Cart: item_added_to_cart
Order Creation Error: order_creation_failed (error_type: string)
```

Prefix: `woocommerceios_pos_*`

**Comment by malinajirka** [comment]
@iamgabrielma What is the current state of analytics? I thought the basic analytics events has been implemented, but based on this ticket and the references tickets, it seem they haven't 🤔 .

We plan to work on another iteration of events and attributes soon, however, the events above need to be part of the MVP release, while what we plan to work on can be implemented after the release. Might be worth checking with Samuel.

**Comment by iamgabrielma** [comment]
> What is the current state of analytics? I thought the basic analytics events has been implemented, but based on this ticket and the references tickets, it seem they haven't 🤔 .

AFAIK analytics was de-prioritized while working in the POC, what we currently have is:

- `pos_item_added_to_cart` when adding an item, this tracks if simple or variation
- payment events like `card_reader_connection_success`,  `card_reader_discovery_failed`, `card_present_collect_payment_success` are tracked due reusing the payments logic through façade/adaptor, but are not tagged as `woocommerceios_pos_*`. I'll drop a comment in Sam's exploration P2

**Comment by iamgabrielma** [comment]
Followup pdfdoF-6hn-p2#comment-7438

**Comment by iamgabrielma** [comment]
Closing as done!
