### ISSUE TITLE
[Login] Add support for signing in to Black-flagged Sites

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#13348]
## Description
When users attempt to log into the app with a black-flagged site URL, they receive an error message stating the URL is invalid and are unable to proceed with login.

This task should update the login flow to gracefully handle this case by directing those users to use site credentials instead of WordPress.com.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14196
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14255
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14256
- [ ] Connect to `connect/site-info` endpoint on app launch to refresh Jetpack upselling banner visibility
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14384
```

## References
peaMlT-JX
https://github.com/woocommerce/woocommerce-ios/issues/13348

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by JorgeMucientes** [comment]
This task is mostly completed. Closing issue
