### ISSUE TITLE
[Blaze] Push notifications

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13477]
Internal - pe5sF9-331-p2

Iteration 1
- [x] Ensure that the notifications are displayed correctly in Woo iOS.
- [x] Add a condition to D137233-code to ensure that only the latest Woo iOS and Android app versions can receive the new Blaze notifications.
- [x] Test the Blaze and existing "New order" notifications again and land the diff.

Iteration 2

- [x] ~Develop screens to display upon tapping each type of Blaze notification. For design, follow the Jetpack designs from pe5sF9-31J-p2.~ We decided to open the campaign detail web view page instead. 
- [x] Handle navigation and tracking #13843
    - [x] Start fetching the necessary notification info from the WPCOM `notifications` endpoint. If needed for UI, fetch Blaze campaign information. 
    - [x] Open the respective Blaze campaign webview screen upon tapping the notification.
    - [x] Test that existing "New order" and other notifications work as before.
    - [x] Add tracking for push notifications. 

Iteration 3
- [x] 30 days after the last active campaign ended, if no campaign is created in between.
    - [x] Parse and store `start_time` from campaign list response. #13807
    - [x] Schedule no campaign reminder notification. #13816
- [x] #13933
- [x] #13935

Improvements
- [ ] #13920

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by irfano** [comment]
> 30 days after the last active campaign ended, if no campaign is created in between.

See this [comment](https://github.com/woocommerce/woocommerce-android/pull/12374#discussion_r1724844069) for details on the logic from the Android side.

#### Analytics
Local notification events have already been implemented on Android. I used `blaze_no_campaign_reminder` for the `type` when this notification is tapped.
```
local_notification_tapped, Properties:{
  "type": "blaze_no_campaign_reminder",
  "blog_id": 111111111,
  "is_wpcom_store": true,
  "was_ecommerce_trial": false,
  "plan_product_slug": "business-bundle",
  "store_id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "is_debug": true,
  "site_url": "https://irfanobusiness.wpcomstaging.com/"
}
```

`local_notification_scheduled` is tracked when the notification is scheduled.  is tracked whenever a notification is scheduled. We track this multiple times for one notification because we update the scheduled notifications each time we fetch campaigns.
```
local_notification_scheduled, Properties: {
  "type": "blaze_no_campaign_reminder",
  "blog_id": 111111111,
  "is_wpcom_store": true,
  "was_ecommerce_trial": false,
  "plan_product_slug": "business-bundle",
  "store_id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "is_debug": true,
  "site_url": "https://irfanobusiness.wpcomstaging.com"
}
```

**Comment by selanthiraiyan** [comment]
Closing as improvement work is tracked by https://github.com/woocommerce/woocommerce-ios/issues/13920
