### ISSUE TITLE
Rename OrderMetaData entity to MetaData

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#13619]
This requires many changes in different layers (Storage, Networking, Yosemite) so will be done in smaller parts.
```[tasklist]
### Tasks
- [ ] Networking layer https://github.com/woocommerce/woocommerce-ios/pull/13620
- [ ] Migrate `OrderMetaData` entity to `MetaData`
- [ ] Update Storage and Yosemite layers
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
