### ISSUE TITLE
Edit origin address UI

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-ios#13781]
```[tasklist]
### Tasks
- [x] Add UI for origin address list
- [x] Show origin address list as a half sheet when "Ship from" address is tapped
- [x] Connect origin address bottom sheet UI with real origin addresses (using new endpoint + view model)
- [x] Add UI for editing an address
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14943
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14960
- [x] Connect validate button with remote validate action
- [ ] Connect confirm button with remote update action
```

![Image](https://github.com/user-attachments/assets/0d4cf5d9-8967-4762-bf10-12474b89c174)

Some considerations from design: 
  
> - You can either update and verify your store address or a destination address.
> - Let’s call out an unverified destination address in the collapsed details panel. You can tap on this notification to open the edit screen directly or dismiss the notification.
> - While editing, we can show a status message above the primary CTA.
> - Let’s not punish people by highlighting a field in red until they unfocus it. Give them time to fill it out.

[More details](https://teameaglep2.wordpress.com/2024/08/19/shipping-label-purchase-flow-design-milestone-2-i1/#editing-and-validating-store-and-destination-addresses)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
@atorresveiga Should we be using the same rules for local address validation as in the legacy flow? Our [legacy validation](https://github.com/woocommerce/woocommerce-ios/blob/4bdd15810677f96c1270a2613dd7f6e59643093c/WooCommerce/Classes/ViewRelated/Orders/Order%20Details/Shipping%20Labels/Create%20Shipping%20Label%20Form/Shipping%20Address%20Validation/ShippingLabelAddressFormViewModel.swift#L258-L287) checks that the following fields are not empty:

* Either name or company
* Address line 1
* City
* Postcode
* State (if required by the country)
* Country
* Phone number (required for origin addresses and for destination addresses requiring a customs form)

If the address is in the US, it also checks that the phone number is 10 digits long (or 11 digits with a "1" prefix).

**Comment by atorresveiga** [comment]
> Should we be using the same rules for local address validation as in the legacy flow?

Yes, Rachel, lets use the same validation rules as in the legacy flow.
