### ISSUE TITLE
[Woo POS] iOS Design Feedback

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13859]
### Hub Menu

- [x] #13906
- [x] #13904

### POS Loading 

- [ ] [Out of scope p1725611514092989-slack-CGPNUU63E ][Animation] Open and close POS from the top or bottom TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22053 TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22786 
- [x] #13866 : Remove text from POS loading screen TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22058 
- [x] #13866 : [Animation] Change transition from loading to dashboard TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22063

### Simple Products
- [x] #13939
- [x] https://github.com/woocommerce/woocommerce-ios/issues/13939 Text spacing and alignment for Simple Products banner TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22247
- [x]  #13939 Spacing in Simple Products modal TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22571
- [ ] [Out of scope] Direct return from product creation to POS TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22581
- [x] Allow tapping background to dismiss TfaZ4LUkEwEGrxfnEFzvJj-fi-4646_21885 #13912

### Floating Button
- [x] Floating button padding in all the states TfaZ4LUkEwEGrxfnEFzvJj-fi-4646_21885 TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22606 TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22611
- [x] Floating button shadow TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22252
- [x] [Animation] Fade-in color changes TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22745
- [x] Show disabled state clearly on reader disconnect button in success view TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22801

### Cart

- [x] #13970 Too much line height on empty cart
- [x] #13915
- [ ] Top shadow is not transparent: TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22677
- [ ] Missing shadow at the bottom: TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22672
- [ ] [Transition] Back button and icon should move together with the cart when transitioning TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22690 TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22695 TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22730
- [x] #13970 Product cards are getting clipped before the edge of the screen 
- [ ] [Animation] The cart should be pushed out of the way, as the right panel expands TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22740

From follow-up, regarding transitions: TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22710

> I think the rule would be: screen content moves vertically first, then screen area transitions horizontally. In this case it would be the graphic and text moving first, then the cart sliding left / purple area expanding.

### Product List

- [ ] Add shadow on scroll TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22596
- [ ] Larger gap between product list and floating button TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22601
- [ ] Row tap state is too strong TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22636
- [ ] Product and Cart tops don't align TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22660

### Reader Connection Modal

- [ ] [Animation] Transition improvements TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22621 TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22626
- [x] #13890
- [x] #13889
- [x] #13912

### Totals View

- [ ] [Animation] Totals text should not appear while transitioning to skeleton TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22710
- [ ] [Animation] Reader not connected error should appear after finishing loading totals TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22796

### Payments View

- [ ] [Animation] Processing payment transition changes TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22750 TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22756

### Success View

- [x] #13967
- [ ] [Animation] Improve the transition from Success View back to Dashboard TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22776

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by malinajirka** [comment]
I'm closing this, since with the planned integration of a design system, it might be easier to do a new full-end-to-end design review. Feel free to re-open it if you believe it's still valuable.
