### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#14]
Android equivalent epic: https://github.com/woocommerce/woocommerce-android/issues/105

### TODO
* [x] Dashboard settings button
* [x] Dashboard title bar
* [x] Revenue and vistors (#177)
* [x] New Orders (#35) 
* [x] Top performers (#178)
* [x] Dashboard loading state (#181)
* [ ] Dashboard empty state (#179)
* [ ] Dashboard error state (#180)
