### ISSUE TITLE
Core Data Usage Update

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#14050]
PT: p91TBi-cfH-p2

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14011
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/2370
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14054
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14081
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14088
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14090
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14091
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14130
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14132
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14133
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14122
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14662
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14153
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14641
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14129
- [ ] https://github.com/woocommerce/woocommerce-ios/pull/14146
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14533
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by itsmeichigo** [comment]
Closing issue as all subtasks are done ✅
