### ISSUE TITLE
Optimize Core Data usage for order-related stores

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#14090]
```[tasklist]
### Tasks
- [ ] #14093
- [ ] https://github.com/woocommerce/woocommerce-ios/pull/14099
- [ ] https://github.com/woocommerce/woocommerce-ios/pull/14125
- [ ] https://github.com/woocommerce/woocommerce-ios/pull/14124
- [ ] https://github.com/woocommerce/woocommerce-ios/pull/14126
- [ ] https://github.com/woocommerce/woocommerce-ios/pull/14128
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by itsmeichigo** [comment]
Closing since all subtasks are done.
