### ISSUE TITLE
[Woo POS] Pagination support

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#14186]
- Project thread:  pffQ75-Xd-p2
- Exploration: pdfdoF-5zD-p2

### Tasks:
- [x] Update networking: https://github.com/woocommerce/woocommerce-ios/pull/14187
- [x] Initial support for infinite scroll: https://github.com/woocommerce/woocommerce-ios/pull/14195
- [x] Differentiate between initial page fetch vs page fetch vs pull-to-refresh https://github.com/woocommerce/woocommerce-ios/pull/14211
- [x] UI: Shimmering loading skeleton card at the end of the list while fetching new items https://github.com/woocommerce/woocommerce-ios/pull/14223
- [x] Trigger next page load on specific threshold: https://github.com/woocommerce/woocommerce-ios/pull/14382
- [x] Improvement: API Optimization. Compare item.count with page count, and check if new items are zero
- [x] Improvement: Update pull-to-refresh animation https://github.com/woocommerce/woocommerce-ios/issues/14251
- [x] Improvement: Loading state when pull-to-refresh shouldn't be dashboard-wide https://github.com/woocommerce/woocommerce-ios/pull/14226
- [x] Stop network requests when there are no new items: https://github.com/woocommerce/woocommerce-ios/pull/14382
- [x] Remove `.displayInfiniteScrollingUIDetailsInPointOfSale` feature flag: https://github.com/woocommerce/woocommerce-ios/pull/14413

### Improvements:
- https://github.com/woocommerce/woocommerce-ios/issues/14443
- https://github.com/woocommerce/woocommerce-ios/issues/14442

### Testing:
- Loads correct products on scroll.
- Loads correct products on reload.
- Loads all pages and items.
- Does not make unnecessary network requests when end of the list.
- Does not make unnecessary network requests when scrolling up.
- Item shimmering is shown when needed.
- Items are unique, no duplication on fetch.
- Dynamic size
- Reload/pull-to-refresh
- Scenarios with empty item list, and low count of eligible items

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by toupper** [comment]
Closing as not planned. This is an old, stale POS issue and we're consolidating active Point of Sale tracking in Linear. If this still needs to be addressed, please comment or reopen and we'll bring it back into the backlog.
