### ISSUE TITLE
[REST API] UI updates for the account creation during Jetpack setup

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-ios#14421]
```[tasklist]
### Tasks
- [x] Update the email screen to indicate the ability for account creation.
- [x] Update the Magic Link screen.
- [x] Update error message when using a non existing username.
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
