### ISSUE TITLE
[POS TPV Tracking] Send `ipp_channel` metadata in payment intent for IPP/POS

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#14478]
Technical plan: pdfdoF-5QB-p2

## iOS

- [x] Send `ipp_channel` metadata in payment intent for IPP/POS with value `mobile_store_management`/`mobile_pos` respectively https://github.com/woocommerce/woocommerce-ios/pull/14479

## [WooPayments plugin](https://github.com/Automattic/woocommerce-payments)

- [x] Display POS channel value based on the conclusion in pdfdoF-5UW-p2 https://github.com/Automattic/woocommerce-payments/pull/9802
- [ ] Exploration: set a flag when the plugin detects a POS transaction (might require server-side changes) pdfdoF-5UW-p2#comment-6983
- [ ] Exploration: support multiple selections for the channel filter pdfdoF-5UW-p2#comment-6984

## WooPayments server

- [x] Set a transaction's `channel` to `in_person_pos` if the IPP payment's metadata `ipp_channel` is `mobile_pos`

## Data engineering

- [x] Add the new `in_person_pos` channel value to the allowed values list of the channel column in `woocommerce_midput.wcpay_transaction_details` and `woocommerce_data.wcpay_transactions_cache`

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jaclync** [comment]
Exploration tasks will be created as separate issues when we are ready to work on them, closing this issue for now.
