### ISSUE TITLE
Support hiding websites from the site picker

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-ios#14658]
###### Android counterpart https://github.com/woocommerce/woocommerce-android/issues/13107

PT: pffQ75-19D-p2

The app currently lists all Woo Stores connected to the user's WordPress.com account, which can clutter the screen for agencies and site builders when client stores are also connected.

![Image](https://github.com/user-attachments/assets/645330d1-e010-4d9d-b48f-591fff0d7ef8)

```[tasklist]
### Tasks
- [x] Add feature flag to edit site picker displayed sites #14706
- [x] Add `Edit` button to site picker when there are more than 1 site listed #14706
- [x] Add new screen for selecting/unselecting visible sites #14708
- [x] Add logic to save selected sites and hide unselected from the Site picker list #14720
- [x] Integrate notification settings endpoint #14730
- [x] Update notifications settings for shown/hidden sites #14738
- [x] Add tracking #14762
- [x] Enable feature flag #14780
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
