### ISSUE TITLE
Release builds Master Issue

### ISSUE THREAD

**Issue by loremattei** [woocommerce/woocommerce-ios#1883]
**Goal**: the goal of this project is to run beta and final release builds on CI with automatic upload to the stores.

Steps:

- [x] Update the release tooling to properly handle the release finalization -> https://github.com/woocommerce/woocommerce-ios/pull/1880.
- [x] Update the release tooling to create the GitHub release -> https://github.com/woocommerce/woocommerce-ios/pull/2014
- [x] Run the build for beta releases on CI. -> https://github.com/woocommerce/woocommerce-ios/pull/2047
- [x] Run the build for the final release on CI. -> https://github.com/woocommerce/woocommerce-ios/pull/2047

**Comment by jaclync** [comment]
@loremattei it looks like the remaining subtasks both have a merged PR linked, do you think this issue is completed? if so, feel free to close it!

**Comment by loremattei** [comment]
Ah! Thank you for the ping @jaclync 🙇‍♂️ 
I completely forgot to close this!
