### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#19]
### Requirements:

- [x] Verify all Tracks calls are implemented for notifications (@bummytime)

#### Networking: Notifications
 - [x] Data Model (@jleandroperez) #378
 - [x] Fetch All (@jleandroperez) #381
 - [x] Mark as Read (@jleandroperez) #381
 - [x] Mark as Seen (@jleandroperez) #381

#### Networking: Comments
 - [x] Mark as Spam (@bummytime) #415 
 - [x] Trash (@bummytime) #415 
 - [x] Approve / Unapprove (@bummytime) #415 

#### Storage: Notifications 
 - [x] Entity Persistance (@bummytime) #390 

#### Yosemite: Notifications
 - [x] Sync'ing Mechanism (@bummytime) #396 
 - [x] Mark as Read (@bummytime) #405 
 - [x] Mark as Seen (@bummytime) #401 

#### Yosemite: Comments
 - [x] Mark as Spam (@bummytime) #420
 - [x] Trash (@bummytime) #420
 - [x] Approve / Unapprove (@bummytime) #420

#### Notifications List
 - [x] Formatters (@jleandroperez) #395
 - [x] Display Notifications collection, grouped by time frame (@jleandroperez) #402
 - [x] Pull to Refresh #412
 - [x] Fine Tune UI: Match Mockups #413 
 - [x] Filters by Notification Type #423
 - [x] Loading + Empty State #425
 - [x] Push OrderDetails for  **.store_order(s)**  #431
 - [x] Wire Mark all as Read #432
 - [x] Filter Active Site Notifications
 - [x] Remove **NukeMe** Struct / Wire the actual required UIColor(s) (@bummytime) #436
 - [x] Wire Mark as Seen (@bummytime) #447 
 - [x] Wire Mark as Read (@bummytime) #448
 - [x] Ensure Dynamic Type is supported  (@bummytime) #438 
 - [x] Add star rating UI control to table cell (@bummytime) #477 
 - [x] Green "unread" dot on Notifications tab (@bummytime) #443 
 - [x] Add notification filter (right nav bar button) (@bummytime) #453 

#### Notification Details (Single ViewController, generic blocks)
 - [x] Block Groups Logic #418
 - [x] Pull to Refresh #426
 - [x] Product Review (@jleandroperez) #442 
 - [x] Adjust Cell Separators
 - [x] Wire Product Review Actions (@bummytime) #457
 - [x] Product Review Header
 - [x] Add star rating UI control (@bummytime) #477 
 - [x] Ensure Dynamic Type is supported

---

### Blueprints:

![notifications](https://user-images.githubusercontent.com/1195260/47296887-03f12900-d5ea-11e8-9bf2-3114f513b508.png)
