### ISSUE TITLE
Edit Products: Manage Product Categories

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2000]
<img src="https://user-images.githubusercontent.com/198826/76883532-ec9b8700-6841-11ea-89d1-8ed04ad9ae55.png" width="400">

This will need to be broken down to a list of tasks/features that should be built. 

## Task Breakdown

The task breakdown is in https://github.com/woocommerce/woocommerce-ios/issues/2000#issuecomment-602852371.

**Comment by Ecarrion** [comment]
Hi @shiki and @Garance91540 could any of you point me in the direction on that figma file or any  feature spec so I can start digesting and scoping this feature?

Thanks! :-)

**Comment by jaclync** [comment]
Shared the design link in DM 🙂

**Comment by Garance91540** [comment]
> EDIT: @jaclync gave me the figma link but any other resource is well appreciated :-)
I shared a Figma walkthrough in DM with you Ernesto hope it helps to navigate the Figma file!

**Comment by Ecarrion** [comment]
I'll be taking this issue as part of my trial 
https://woomobilep2.wordpress.com/2020/03/23/manage-product-categories/

**Development tasks**
- [ ] Add manage categories feature flag
- [ ] Update Storage layer with ProductCategory new fields
- [ ] Update Network layer with [create new ProductCategory request](https://woocommerce.github.io/woocommerce-rest-api-docs/?shell#create-a-product-category)
- [ ] Update Network layer with [syncrhonize ProductCategories](https://woocommerce.github.io/woocommerce-rest-api-docs/?shell#list-all-product-categories)
- [ ] Update Yosemite layer to orchestrate new Network and Storage actions
- [ ] Display product category in product screen
- [ ] Build ProductCategory selector screen
- [ ] Show action sheet before saving changes on product screen
- [ ] Build Add/Create ProductCategory Screen
- [ ] Build screen to select a parent ProductCategory
- [ ] Remove manage categories feature flag

**Comment by pmusolino** [comment]
I found a small issue when the Product Categories are loading in Dark Mode:

<img src="https://user-images.githubusercontent.com/495617/80382198-48761880-88a2-11ea-890b-78d3649ed016.png" width=300 />

**Comment by pmusolino** [comment]
Extra tasks:
- [ ] Manage category selection
- [ ] Category Save
