### ISSUE TITLE
Order Details

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#21]
## MVLP Order Details
(Note: search is not part of Order Details MVLP)
- [ ] Order Details screen has two states: Completed (order fulfilled) and Processing (order not yet fulfilled)
- [x] Section: Summary #23
- [ ] Section: Extension warning #108
- [ ] Section: Product list with fulfill button #9
- [x] Section: Customer note #27
- [x] Section: Customer Info (shipping / billing) #53
- [x] Section: Payment #67
- [x] Section: Order Notes (add a note, notes) #73
- [ ] Separate screen: Add a note #75
