### ISSUE TITLE
Order Details: Package tracking on completed order

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-ios#250]
### Details:
Order details (for a completed order) should allow users to access the tracking details (if available) within a web view. Note that this is not part of Woo Core, but it can be added by means of [this plugin](https://woocommerce.com/products/shipment-tracking).

### i6 Design:

<img width="797" alt="screen shot 2018-08-20 at 6 38 34 pm" src="https://user-images.githubusercontent.com/154014/44372216-83f2f980-a4a8-11e8-9d5b-078d86c8f550.png">

## To do items
- [x] Support in the `Networking` framework #692 
- [x] Support in the `Storage` framework #701 
- [x] Support in the `Yosemite` framework (stores & models) #710 
- [x] Build out the UI and wire it up (@ctarda ) #721

**Comment by bummytime** [comment]
Just an update here. So testing this out it, the tracking extension provides a new endpoint (`/wc/v2/orders/$orderID/shipment-trackings/`) for the retrieval of tracking information including the URL that takes you to the tracking provider's website.

e.g. 
```JSON
{
  "data": [
    {
      "tracking_id": "c44e60000a04d7851ae43c7d2bcecc9b",
      "tracking_provider": "USPS",
      "tracking_link": "https:\/\/tools.usps.com\/go\/TrackConfirmAction_input?qtc_tLabels1=940553689535799999999",
      "tracking_number": "940553689535799999999",
      "date_shipped": "2019-02-13",
      "_links": {
        "self": [
          {
            "href": "http:\/\/somewhere.someplace.com\/wp-json\/wc\/v2\/orders\/172\/shipment-trackings\/c44e60000a04d7851ae43c7d2bcecc9b"
          }
        ],
        "collection": [
          {
            "href": "http:\/\/somewhere.someplace.com\/wp-json\/wc\/v2\/orders\/172\/shipment-trackings"
          }
        ],
        "up": [
          {
            "href": "http:\/\/somewhere.someplace.com\/wp-json\/wc\/v2\/orders\/172"
          }
        ]
      }
    }
  ]
}
```

Note that when we make the JP tunneled call to this endpoint it looks like we need to make sure we are using `v2` and not `v3` — the v3 endpoint did not work in my tests. 

Rest API docs: https://docs.woocommerce.com/document/shipment-tracking/#section-8

**Comment by bummytime** [comment]
Closing this because the final PR was merged → #721
