### ISSUE TITLE
Custom order statuses

### ISSUE THREAD

**Issue by aforcier** [woocommerce/woocommerce-ios#262]
Minimally support the display of custom status labels but not support any custom workflows.

Android counterpart issue: https://github.com/woocommerce/woocommerce-android/issues/87

- [x] Set up a site with a plugin has a custom order status

- [x] Create an OrderStatus model (Networking)
- [x] Create an OrderStatusMapper (Networking)
- [x] Add the OrderStatus as an entity in Core Data (with Slug and Name for attributes, add relationship to Order)

- [x] Fetch order status options for a single site from the API: `OrderStatusRemote` (Networking)
- [x] Parse the response (Networking)
- [x] Store it in Core Data (Storage)
- [x] Look up an order's slug and display the correct name (results controller fetch?)

- [x] Add unit tests for Yosemite, ~Networking~, and ~Storage~

- [x] Trigger the action / fire the event upon every load of My Store tab, when total orders to fulfill is requested
