### ISSUE TITLE
Ability to delete an existing Product

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#2853]
As part of Product Milestone 5, we should allow users to delete an existing product.

#### TODO:
- [x] Implement the network API request.
- [x] Implement the Yosemite layer for deleting a product (in reality it goes in your Trashed items, as [discussed here](https://a8c.slack.com/archives/C6H8C3G23/p1600696854038900))
- [x] Implement the action in the action sheet (to be showed only when the product is in the `editing` status)
- [x] Show the alert like on Android, asking the user for confirmation.

#### Screen:
![Schermata 2020-09-22 alle 16 30 04](https://user-images.githubusercontent.com/495617/93896199-f1f5f480-fcf0-11ea-9e81-b76d955aa58f.png)
