### ISSUE TITLE
[HACK Week] FakeKit ™️

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#3096]
# Problem

There is an inconvenience when creating a new Networking model which is that creating these models for tests is very tedious.

To circumvent this the project defines a series of "Mock<Model>" objects that help in creating these models in a simpler way.

The problem is that these Mock classes have to be created manually and can't be used between targets.

# Proposed solution

Create `FakeKit ™️` framework on SPM that will store all of these mock objects.

# Tasks

- [x] Fix the problem that does not let us run `rake generate` due to SPM #2864 
- [x] Create a new framework on SPM (and decide a better name?)
- [x] Analyze if fake is a better fit than mock
- [x] Autogenerate fake/mock objects on the new framework
- [ ] Integrate new fakes and delete old mocks
- [x] Update Documentation

**Comment by shiki** [comment]
Another concern that I have is that in some of our unit tests, it's not immediately clear **what data** is being tested. Consider this test for example:

https://github.com/woocommerce/woocommerce-ios/blob/0221c16caae9888b20462d3d673b448f29eca559/WooCommerce/WooCommerceTests/ViewRelated/OrderDetailsViewModelTests.swift#L40-L48

It is not clear whether the test will fail if someone changed `sampleOrderCreatedInCurrentYear()` later. What data is important in `sampleOrderCreatedInCurrentYear()`? Do we really need all this pre-filled information? 

https://github.com/woocommerce/woocommerce-ios/blob/0221c16caae9888b20462d3d673b448f29eca559/WooCommerce/WooCommerceTests/Tools/MockOrders.swift#L68-L93

I think we would do better if we only had [MockOrders.empty()](https://github.com/woocommerce/woocommerce-ios/blob/0221c16caae9888b20462d3d673b448f29eca559/WooCommerce/WooCommerceTests/Tools/MockOrders.swift#L8), which defines the minimum default values, and use `.copy()` to define the test requirements instead: 

```swift
    func testFormattedDateCreatedDoesNotIncludeTheYearForDatesWithTheSameYear() {
        let order = MockOrders().empty().copy(dateCreated: Date())

        let viewModel = OrderDetailsViewModel(order: order)
        let expectedYearString = DateFormatter.yearFormatter.string(from: order.dateCreated)

        let formatted = viewModel.formattedDateCreated

        XCTAssertFalse(formatted.contains(expectedYearString))
    }
```

In the example above, it's immediately clear what value is being tested, it's the `dateCreated` which is set to `Date()`. Doing it this way also makes it easier to write more unit tests since there are [no shared fake data](https://github.com/woocommerce/woocommerce-ios/search?q=sampleOrder%28%29) that would be harder to change later.

**Comment by Ecarrion** [comment]
# Update

## Fact 

`FakeKit` was designed as an `SPM` package and it needs `Networking` entities as dependencies. 

## Problem
`SPM` packages can't have binary frameworks as dependencies 🙃 

## Tasks
- [ ] Convert our binary frameworks to xcframeworks 
or
- [x] Convert `FakeKit` to a normal framework

**Comment by shiki** [comment]
@Ecarrion Does converting the Networking package to SPM help? I don't understand frameworks or xcframeworks so my apologies if my question is stupid. 🤣

**Comment by Ecarrion** [comment]
@shiki 
> Does converting the Networking package to SPM help? 

I didn't consider that possibility! 🤔 
I will investigate if it's possible!

Thanks
