### ISSUE TITLE
Enable searching products by SKU

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-ios#3157]
Provide the option to search for products by SKU in the Products tab. This is one of the feature requested by users from the feedback survey.

Related android issue: woocommerce/woocommerce-android#3168

---
## Subtasks

- [x] Storage layer changes: https://github.com/woocommerce/woocommerce-ios/pull/7738
- [x] Add a segmented control below the search bar to search for all products or by SKU https://github.com/woocommerce/woocommerce-ios/pull/7739
- [ ] Add SKU info to the product result row
- [ ] Analytics: maybe add a filter property to `product_list_searched` event

**Comment by madeincosmos** [comment]
One more user asking for this in 3502853-zen

**Comment by iamgabrielma** [comment]
4065273-zen

> when search product by SKU would be available in woocommerce app. It's a basic but quite useful feature.

**Comment by reginabally** [comment]
Another request in 4121042-zd-woothemes

**Comment by joshbetz** [comment]
Related: https://github.com/woocommerce/woocommerce/issues/28508

**Comment by iamgabrielma** [comment]
4326510-zen

> I really like your app and I’m willing to use it for my online shop, but there is one thing that needs to be added.
The problem is that I can search the products only by name and not SKU!
The sku is very important because it’s unique. There a lot of products in my store with the same name and the only way to find the product that I need is the sku.

**Comment by poojashetty18** [comment]
Another request in [4337982-zen](4337982-zd-woothemes)

**Comment by rossanafmenezes** [comment]
Another request here 4667012-zen

**Comment by reginabally** [comment]
> Having SKU search support within the app would make stock picking and inventory management very convenient, as the code could be read directly from the product and stock value could be updated directly within the app.

4678060-zd-woothemes

**Comment by thabotswana** [comment]
Another request: 4883638-zen
