### ISSUE TITLE
Variations: Empty List State

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#3195]
Ref p91TBi-2Ur-p2.

<img width="610" alt="Screen Shot 2021-01-26 at 11 30 10 AM" src="https://user-images.githubusercontent.com/562080/105874112-3ad4f700-5fca-11eb-8425-51118e628d01.png">

This is shown after tapping in the "Add Variation" and there are no variations. 

## Tasks

- [ ] Build UI(Consider making it an empty state inside the variations list) 
- [ ] Show empty state when there are no variations
- [ ] Connect "Add Variation" cell to this screen
- [ ] Connect "Add Variation" button action to the `Add` Attribute screen
---

Android: https://github.com/woocommerce/woocommerce-android/issues/3211
