### ISSUE TITLE
Add Tracking for Downloadable Files and Enable it for All

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#3381]
### Detail Page

<img src="https://user-images.githubusercontent.com/198826/102690759-df426d00-41c4-11eb-9ea7-223a31bdc188.png" width="300">

- [ ] When the Downloadable files button is tapped, trigger the event `product_detail_view_downloadable_files_tapped`.

### Settings

<img src="https://user-images.githubusercontent.com/198826/102690773-fb460e80-41c4-11eb-941f-340b02e6c311.png" width="300">

- [ ] When tapping Done, trigger the event `product_downloadable_files_settings_changed`. 

### Downloadable File Item

<img src="https://user-images.githubusercontent.com/198826/102690786-17e24680-41c5-11eb-9989-d26aaec985b9.png" width="250"><img src="https://user-images.githubusercontent.com/198826/102690799-31838e00-41c5-11eb-9fd0-eb83cfbb9a70.png" width="250"><img src="https://user-images.githubusercontent.com/198826/102690812-46f8b800-41c5-11eb-9e37-58134dc59b86.png" width="250">

- [ ]  When modifying downloadable files, trigger these events:

Event Name | Trigger | Custom Properties
--------|-------|----
`products_downloadable_file`        |  When tapping Add in the Add downloadable file screen.      |  `action="added"`
`products_downloadable_file`        |  When tapping Update for an existing downloadable file.      |  `action="updated"`
`products_downloadable_file`        |  After confirming the deletion of a downloadable file.      |  `action="deleted"`

## Enable for All

- [ ]  The Downloadable Files feature should no longer be hidden under the M5 feature flag.

---

Android: https://github.com/woocommerce/woocommerce-android/issues/3353
