### ISSUE TITLE
Mobile Payments M1: Epic: Connecting BBPOS Chipper 2X BT Readers

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#3509]
This epic contains the work needed to discover, connect and forget BBPOS Chipper 2X BT card readers for US merchants. Whenever possible we want to leverage the terminal mock to avoid having to introduce the location serivces and bluetooth capabilities prematurely to develop

- [x] Add feature flag
- [x] Add remote for connection token
- [x] Fetch whether a site has a WCPay account
- [x] Fetch site's current WCPay mode (test or live or not active)
- [ ] Fetch whether site has ordered a reader
- [x] Add entity (or UserDefaults) for known readers
- [x] Add reader discovery delegate (service) and terminal mock
- [x] Add terminal delegate to service
- [x] Add settings view for readers
- [x] Add discovered readers to settings view
- [x] Add connect-to-reader to settings view
- [x] Add disconnect-and-forget-reader to settings view
- [x] Add reader SW update view
- [ ] Add reader status bar subview
- [ ] Add buy-a-reader view
- [x] Enable location services and bluetooth in plist

**Comment by ctarda** [comment]
Closing. This one seems outdated.
