### ISSUE TITLE
Migrate to v3 REST API

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-ios#352]
For MVLP, we are only going to support the [v3 REST API](https://github.com/woocommerce/woocommerce/tree/master/includes/api) which is shipping in WooCommerce 3.5. In order to adopt it, we will need to make a few modifications:

- [ ] If possible, filter the site picker during auth to only display v3.5+ sites (otherwise interrogate the site upon user-selection and display warning if it's not a v3.5 site) #399 
- [ ] Update all of our `*Remote` classes to use the `v3` namespace #479
- [ ] Update the new orders sync logic #348 
- [ ] Add support for system vs user-created private order notes #55
- [ ]  Top performers: support original date ranges #353 
- [ ] If a WooCommerce v3.4 or older user is already logged into the beta app, display a warning dialog to them (and maybe log them out) #398 

/cc @aforcier @jleandroperez
