### ISSUE TITLE
Variations: Refresh Product after updating attributes or variations

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#3619]
We need to find a way to update the underlying `product` in  `ProductFormViewController` after updates to it happen.

### Tasks
- [x] Add new / Edit  product attribute #3690 
- [x] Remove Product Attribute
- [x] Add new variation #3690
- [x] Remove variation #3764
- [x] Update main product list page on create and delete variations. #3787

**Comment by Ecarrion** [comment]
We also need to make sure that the main product list is updated!
