### ISSUE TITLE
Product Details: Remove "Done" button on sub edit flows.

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#3652]
Ref:  p1612977972011800-slack-CGPNUU63E and p91TBi-4rc-p2

# Why
We spotted that there is some redundancy around the "Done" buttons when editing a product.

Basically, it's not worth having a "Done" button to commit local changes if later we have an "Update" button to push local changes to the hosted site.

# Task

We should remove the "Done" buttons in the sub-edit product flows and commit the local changes as soon as the merchant made them. This means that the only "back button alert" would exist in the main edit product screen.

- [ ] Edit Description
- [ ] Edit Shipping
- [ ] Edit Inventory
- [ ] Edit Categories
- [ ] Short Description
- [ ] Linked products
- [ ] Edit Variations Attributes 
- [ ] Edit Product Link
- [ ] Edit SKU
- [ ] Edit Downloadble files
- [ ] Edit Grouped Products
- [ ] Edit product settings
- [ ] Variations: Rename attribute

**Comment by shiki** [comment]
Mentioned and re-verified in p91TBi-5oi-p2#comment-5239. 

> If it’s possible to remove the need to select “Done” everytime we submit a change, I’d say let’s do it! But FYI, this is a change that we implemented on Android on all the child screens, not just on Products. So if we implemented this behavior on iOS we should do it for all the sections.

**Comment by shiki** [comment]
@Ecarrion Just wanted to confirm since you're still assigned to this. Are you planning on taking this on yourself? Or would you like to keep it unassigned until you're ready? In case @ealeksandrov wants to take it? 😁

**Comment by Ecarrion** [comment]
I'll unassign myself 😅

**Comment by shiki** [comment]
We discussed this during the Eagle call today, we'll probably have to align the experience with Order Editing + Order Creation first before we tackle this. Do we want a Done button or do we want changes to be updated right away?

**Comment by shiki** [comment]
This is too old that I think we'll have to rethink how we're gonna approach this. And it's also really not that important if we consider the current situation.
