### ISSUE TITLE
[Mobile Payments] Epic: Does the site support card present payments

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#3839]
As part of mobile payments, we need to properly wire up checking whether the WooCommerce site has a card present payment compatible plugin active, account status, etc. Some intersection with #3555 

- [x] Networking: get plugins (to see if wcpay active) #3844
- [x] Networking: get wcpay account (if any) #3881
- [ ] Storage?: persist plugin list, persist card present capable accounts (more in the sense of a medium timeframe cache to reduce fetches since plugin list and account status change infrequently)
- [ ] Yosemite: Actions to fetch plugins list, fetch card present capable accounts
- [ ] WooCommerce/UI: Invite user to enroll, complete setup, show account status
- [ ] Performance?: Advise user if site is capable of supporting card present payments

**Comment by Ecarrion** [comment]
Storage/Yosemite for plugin list will be handled here https://github.com/woocommerce/woocommerce-ios/issues/3921

**Comment by AliSoftware** [comment]
Moved this issue's milestone to 6.9, as code freeze for 6.8 is happening today.

**Comment by ctarda** [comment]
Closing, as this is completed
