### ISSUE TITLE
Present a clearer message if the site is password-protected, XML-RPC is blocked, or cannot be reached

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#3891]
Found in https://github.com/woocommerce/woocommerce-ios/issues/3883#issuecomment-809819474
Solutions discussed in p91TBi-4Pz-p2

## Describe the bug

The app responds with an indistinct message (“Not a WordPress site”) when logging in with a site that has one of these conditions:

- [ ] Is password-protected via a basic HTTP auth. (moved to #3883)
- [x] If the site blocks XML-RPC. #3957 
- [x] If the device is offline #3957 
- [x] If the site is HTTP only #3957 

### Password-protected

I performed similar steps with my site:

1. Create a WooCommerce site that is connected to Jetpack.
2. I added a basic HTTP auth to the site. [Here](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/) is an example for Nginx.  Ask @shiki if you need help setting up a site. 
3. Log in by clicking on "Enter your Store Address" and enter the site address.

Here is the result on Android but it's the same on iOS: 

<img src="https://user-images.githubusercontent.com/198826/112916639-2e4e4700-90be-11eb-89a2-fd5d1daa8311.png" width="300">

### XML-RPC 

This will probably work → [How to Disable XML-RPC in WordPress](https://www.wpbeginner.com/plugins/how-to-disable-xml-rpc-in-wordpress/)

## Expected behavior

I would expect a more specific message so that I can troubleshoot further. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

## Mobile Environment

Please include:
- Device: iPhone 11 simulator
- iOS version: 14
- WooCommerce iOS version: a0ebe53

## WordPress Environment
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

--- 

Android: https://github.com/woocommerce/woocommerce-android/issues/3767

**Comment by designsimply** [comment]
Answering a question [from another thread on a related issue](https://github.com/woocommerce/woocommerce-ios/issues/3883#issuecomment-810421656):

> I'm not sure of the priority of that though. I don't know how often we receive instances where the problem is a password-protected site. Maybe you have an idea?

https://github.com/woocommerce/woocommerce-ios/issues/3891 looks great to me! My first thought on priority is that it is medium, or maybe even high!, because even though it likely does not happen often it is incredibly frustrating and hard-to-figure-out when it does happen and also because it happens in one of our most important critical flows: login.

**Comment by shiki** [comment]
I discovered that the WordPress iOS app can connect to sites with Basic Auth. WC does not seem to have this mechanism.

**Comment by shiki** [comment]
Fixed by #3957. I'm moving the remaining items to #3883.
