### ISSUE TITLE
Shipping Labels M2: display the last package selected

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3940]
After discussing with @anitaa1990, it seems that we should show the last package selected in the "Package Details screen", and we need to fetch the Shipping Label Settings for it.
There is some work already done, and probably we just need to update the model `ShippingLabelSettings` and update the Storage layer for this.

**Comment by rachelmcr** [comment]
The last package selected comes from the WCS Settings endpoint `/wc/v1/connect/account/settings` (`last_box_id` in `userMeta` in the response). This is different from the Shipping Label Settings we already support (which are per order).

To display the last package selected we'll need:

- [x] Support for `GET /wc/v1/connect/account/settings` in the Networking layer #3983 
- [x] New entity representing WCS Settings in the Storage layer, to save the last package ID (`last_box_id`). #3996
- [x] Support for WCS Settings in the Yosemite layer #4016

I'm also checking to see if `last_box_id` includes details about the last custom package selected, or if it only returns service packages (since custom packages only have a `name`, not an `id`).

**Comment by rachelmcr** [comment]
@hichamboushaba clarified a couple points about how we're doing this on the Android side. (Thanks!)

Handling both service and custom packages:

> For custom packages, `last_box_id` returns the name of the package, so to make things clearer on our side, we decided to add a property id to the custom package class in the business model layer, and copy the name value to it. Then we just compare the id from our class to what last_box_id returns.

When to fetch the endpoint:

> We also fetch the endpoint when the form is loaded (before showing any steps), and we cache the result while the form is open. We do so because the result contains the payment methods that we need also to decide whether the payment step is required or not, if a payment method is already selected, the user shouldn't have to re-select it.
