### ISSUE TITLE
Error synchronizing: "Unable to load content" and "Unable to refresh list" when logged in to a Jetpack site as a user with the Editor role

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#3963]
To prepare:

<sup>TL;DR have a Jetpack site with one Administrator Jetpack-connected account and one Editor Jetpack-connected account.</sup>

* Set up a WooCommerce store hosted somewhere other than WordPress.com.
* Install, activate, and connect Jetpack using a WordPress.com account.
* Go to WP Admin > Users and create an Editor account using a different WordPress.com account email.
* Log out of both WordPress.com and WP Admin.
* Log back in to WP Admin as the user you just created.
* Go to WP Admin > Jetpack Dashboard > Account connection and click the "Link to WordPress.com" link.
* Connect to the WordPress.com with the email address of the Editor account in WP Admin.
* You should end up with something that looks similar to [this screenshot](https://user-images.githubusercontent.com/1119271/114798908-b6d21600-9d53-11eb-936b-3604021753f3.png).

To test: 

1. Log in to the WooCommerce app as a Jetpack-connected user with an Editor role.
1. Browse around in the app.

**Result:** if I log in to the WooCommerce app with a user that is Jetpack-connected but has an Editor role, the app will show "Unable to load content" and "Unable to refresh list" and the app log says "Error synchronizing" multiple times.  ([1m33s](https://cloudup.com/c0NWSqCI4Xw))

```
2021/04/14 19:58:42:104  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:104  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
```

<details>
<summary>Full app logs for the timestamp matching the video</summary>

```
2021/04/14 19:58:01:812  ðŸ”µ Tracked unified_login_interaction, properties: [AnyHashable("click"): "submit", AnyHashable("source"): "default", AnyHashable("flow"): "wordpress_com", AnyHashable("step"): "start"]
2021/04/14 19:58:02:630  ðŸ”µ Tracked unified_login_step, properties: [AnyHashable("source"): "default", AnyHashable("step"): "start", AnyHashable("flow"): "login_password"]
2021/04/14 19:58:10:565  Received OAuth2 response: {
    "access_token" = "*** REDACTED ***";
    "blog_id" = 0;
    "blog_url" = "<null>";
    scope = global;
    "token_type" = bearer;
}
2021/04/14 19:58:10:609  ðŸ”µ Tracked unified_login_step, properties: [AnyHashable("flow"): "login_password", AnyHashable("step"): "success", AnyHashable("source"): "default"]
2021/04/14 19:58:10:795  ðŸ“± Unregistering For Remote Notifications...
2021/04/14 19:58:10:795  â˜Žï¸ [Zendesk] Unregistering for Notifications...
2021/04/14 19:58:10:963  ðŸ”µ Tracked unified_login_step, properties: [AnyHashable("flow"): "login_password", AnyHashable("step"): "success", AnyHashable("source"): "default"]
2021/04/14 19:58:12:291  TracksService sendQueuedEvents completed. Sent 4 events.
2021/04/14 19:58:23:415  âš ï¸ Cannot check WC version on default store â€” default siteID is nil or 0.
2021/04/14 19:58:23:416  checkAppleIDCredentialState: No Apple ID found.
2021/04/14 19:58:39:419  ðŸ“± Registering for Remote Notifications...
2021/04/14 19:58:39:460  â™»ï¸ Requesting dashboard data be reloaded...
2021/04/14 19:58:39:501  ðŸ“± Device Token Received: [*** REDACTED ***]
2021/04/14 19:58:39:597  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:58:39:597  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:58:39:600  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:58:39:600  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:58:39:600  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:58:39:600  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:58:39:629  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:58:39:629  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:58:39:878  ðŸ“± Successfully registered Device ID 41285461 for Push Notifications
2021/04/14 19:58:42:104  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:104  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:162  â›”ï¸ Site settings sync had 2 error(s) for siteID 191940058: [Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources., Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.]
2021/04/14 19:58:42:238  â›”ï¸ Could not successfully fetch order statuses for siteID 191940058: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:369  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:370  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:377  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:377  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:388  â›”ï¸ Failed to sync payment gateways for siteID: 191940058. Error: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:406  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:406  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:412  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:413  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:432  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:432  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:584  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:584  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:667  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:667  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:42:674  â›”ï¸ Error loading dashboard: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:49:846  checkAppleIDCredentialState: No Apple ID found.
2021/04/14 19:58:51:886  â›”ï¸ Order List â€” Error synchronizing order statuses: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:52:090  â›”ï¸ Error synchronizing orders: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:58:57:259  â›”ï¸ Error synchronizing products: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:09:934  â™»ï¸ Requesting dashboard data be reloaded...
2021/04/14 19:59:10:060  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:10:060  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:10:061  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:10:061  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:10:062  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:10:063  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:10:063  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:10:063  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:11:293  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:294  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:294  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:294  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:310  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:310  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:351  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:351  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:357  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:357  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:377  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:377  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:379  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:379  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:468  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:468  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:11:472  â›”ï¸ Error loading dashboard: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:48:602  â™»ï¸ Requesting dashboard data be reloaded...
2021/04/14 19:59:48:730  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:48:731  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:48:731  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:48:731  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:48:735  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:48:735  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:48:768  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:48:768  â›”ï¸ Error synchronizing visitor stats: noPermission
2021/04/14 19:59:50:509  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:510  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:534  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:534  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:820  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:820  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:876  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:877  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:901  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:902  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:921  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:922  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:952  â›”ï¸ Dashboard (Order Stats) â€” Error synchronizing order stats v4: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:952  â›”ï¸ Error synchronizing order stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:995  â›”ï¸ Dashboard (Top Performers) â€” Error synchronizing top earner stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:50:995  â›”ï¸ Error synchronizing top earners stats: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 19:59:51:002  â›”ï¸ Error loading dashboard: Dotcom Error: [woocommerce_rest_cannot_view] Sorry, you cannot list resources.
2021/04/14 20:00:00:080  checkAppleIDCredentialState: No Apple ID found.
2021/04/14 20:03:31:860  checkAppleIDCredentialState: No Apple ID found.
```
</details>

<img src="https://user-images.githubusercontent.com/1119271/114803643-0d901d80-9d5d-11eb-9785-0c8499186202.png" width="200" alt="Unable to load content"> <img src="https://user-images.githubusercontent.com/1119271/114803705-30223680-9d5d-11eb-90e0-e16d15711a82.png" width="200" alt="Unable to refresh list"> <img src="https://user-images.githubusercontent.com/1119271/114804621-d28ee980-9d5e-11eb-8a86-d8b7b6b4ea68.png" width="200" alt="No products yet">
<sup>Tested with WCAndroid 6.4.0.0 (TestFlight beta) on iPhone 11 iOS 14.4.2 on favourite-saki.jurassic.ninja (WP 5.7.1-RC1 JP 9.6.1 WC 5.2.1) logged in as testuser031821 (which is a WordPress.com account username used to connect to the account with the same name on the Jetpack site and that has an Editor role there).</sup>

**Potential solutions:** 

1. Update the minimum requirements for the app to mention the account in WP Admin must be connected to Jetpack and must either be an Administrator or Shop Manager role. 
1. Add error handling for `Sorry, you cannot list resources` to let the user know the role requirements and how to update that in WP Admin (make sure to note that an Administrator must make the change).

**Comment by shiki** [comment]
Android issue: https://github.com/woocommerce/woocommerce-android/issues/3846

**Comment by dvdchr** [comment]
### Update

Hey there! 👋  Sorry it took a while to wrap up this feature! Here's a list of remaining work items that hopefully gives you a clearer picture on when this would be _finally_ completed 😅 : 

- [x] Merge #4619 to `issue/3963-auth-role-error`. 
- [x] Merge the integration branch to `develop`. PR: #4620
  - FYI, contents of the branch are still detached from application flow, and should be safe to merge into `develop`. The actual flow impacting changes are centralized in #4493. 
  - Additionally, merging to develop avoids turning it into integration branch, since there's still two more sizable PRs coming up (see below points).
- [x] Proceed to resolve and merge #4492 to `develop`.
- [x] Proceed to resolve and merge #4493 to `develop`.

Despite the list, there's really only a few changes left to be made, so I'm aiming to get things done this week! 🤞

**Comment by designsimply** [comment]
Thank you @dvdchr! This came up again in an app review and I just wanted to include it for reference because I'd like to try to follow up with this specific user after the issues with roles is resolved to see if that helped them (app reviews are often lacking in detail and it's not yet clear if permissions/role is truly the problem in this case—they did specifically mention the "Unable to load content" error though!).


> The application is simply chaotic: slow, lags, always the same error message "Unable to load content" WooCommerce frustrates me more than to free me from order management. [Translated from French using Google Translate.]
> 
> <sup>1-star review - Jul 15, 2021 - Version 7.0 - France</sup>

**Comment by dvdchr** [comment]
Update: this feature will be available in version 7.2! 🙂
