### ISSUE TITLE
Plugins: Update Storage layer

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#4112]
## Tasks

- [ ] Add SitePlugin model
- [ ] Add unit test for migration
- [ ] Update MIGRATIONS.md
- [ ] Add feature flag & merge to develop

**Comment by itsmeichigo** [comment]
Thanks @Ecarrion 🙂

**Comment by itsmeichigo** [comment]
Hi @Ecarrion, I want to target my PR to develop branch - which release version should I note in the migration log?

**Comment by Ecarrion** [comment]
>  I want to target my PR to develop branch - which release version should I note in the migration log?

Hey @itsmeichigo, our next release will be `6.7.0` which should go out on `May 17`. If you plan to have it merged before then you should note `6.7.0` in the migration log.
