### ISSUE TITLE
Plugins: Update UI layer

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#4114]
## Tasks
- [ ] Update DefaultStoresManager to sync plugins
- [ ] Update Settings screen for an entry point to the plugin list
- [ ] Add PluginListViewModel
- [ ] Add PluginListViewController
- [ ] Build SwiftUI refresh control (if possible)

**Comment by itsmeichigo** [comment]
Thanks @Ecarrion 🙂

**Comment by itsmeichigo** [comment]
@Ecarrion  I think this issue can be closed now right?
