### ISSUE TITLE
Variations: Add "Variation Attributes" button

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#4312]
We are going to be doing some changes for editing attributes.

<img width="332" alt="product attributes" src="https://user-images.githubusercontent.com/562080/119887108-55c46300-bef9-11eb-9a8b-d3e2354eee47.png">

## Tasks

- [x] Show "Variations Attribute" row when the product has at least one attribute

- [x] Make that button to navigate to the "Edit Attributes" screen

- [x] Remove buttons to edit attributes from the "Create Variation" flow. (Variations list, empty variations)
