### ISSUE TITLE
Variations: Changes when creating a new variation

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#4313]
We are going to be doing some changes when creating the first variation.

<img width="1173" alt="creating-first-variation" src="https://user-images.githubusercontent.com/562080/119867226-46d2b600-bee3-11eb-94a6-b5dacfe29a8d.png">

## Task

- [x] After creating the first variation, redirect the user to the main product screen
- [x] After creating the first variation, present a notice informing the user that a variation was created.
- [x] If some variations don't have prices, show the "add price to your variations" cell indicator
