### ISSUE TITLE
Support for International Shipping Labels

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#4596]
We need to update the origin and shipping addresses to accept international shipping, and when an international order is found, we need to require a customs form declaration.
Make sure to follow the release order: https://github.com/woocommerce/woocommerce-ios/issues/4595

## Tasks (you can split them into subtasks):
- [x] Update the country selector in the origin address field to accept US and its territories that have at least one USPS postal office: ‘US’, ‘PR’, ‘VI’, ‘GU’, ‘AS’, ‘UM’, ‘MH’, ‘FM’, ‘MP’ ([source](https://github.com/Automattic/woocommerce-services/blob/dbeed610f336f8db7995743765dbcd0ff2e18474/client/extensions/woocommerce/woocommerce-services/state/shipping-label/constants.js#L1))
- [x] Update the country selector in the destination address to accept other countries.
- [x] Require a valid phone number for international shipping.
- [x] Display the customs step when we detect international shipping.
- [x] Clicking the Continue button in the customs step would open the customs declaration screen.
- [x] https://github.com/woocommerce/woocommerce-ios/issues/4597

![Schermata 2021-07-13 alle 15 40 30](https://user-images.githubusercontent.com/495617/125462081-0cf9b402-7fb5-4579-9de7-42249d39622c.png)
