### ISSUE TITLE
Plugins: Storage layer

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#4604]
Parent: https://github.com/woocommerce/woocommerce-ios/issues/4278

## Tasks
- [ ] Add a new model
- [ ] Add migration test.
- [ ] Update Storage readme
- [ ] Add model to Network Layer

**Comment by fernandofgfer** [comment]
**Quick update:**

- [x]  Add a new model
- [x]  Add migration test
- [x]  Update Storage readme
- [x]  Add model to Network Layer
