### ISSUE TITLE
CPP Onboarding: Epic Phase 1

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#4611]
Provide merchants with information about the next necessary step they need to take in order to enable in-person payments on their stores.

Designs are available on vaw3DvewbUwuQnPXpdNGGH-fi-370%3A468 - **we should consider implementing any deviations from the scope (p91TBi-5uD-p2) in the next phase of this project.**

Eligibility Checks
- [x] Introduce a feature flag (PR https://github.com/woocommerce/woocommerce-ios/pull/4612)
- [x] Create initial generic error page (PR https://github.com/woocommerce/woocommerce-ios/pull/4613)
- [x] Create initial settings page with success state (PR https://github.com/woocommerce/woocommerce-ios/pull/4615)
- [x] Loading state UI (#4759)
- [x] Unsupported country state UI (#4750)
- [x] Unsupported country state business logic (#4724, #4730)
- [x] WCPay not installed state UI (#4738)
- [x] WCPay not installed state business logic (#4729)
- [x] WCPay not activated state UI (PR https://github.com/woocommerce/woocommerce-ios/pull/4751)
- [x] WCPay not activated state business logic (#4729)
- [x] Unsupported WCPay version state UI (PR https://github.com/woocommerce/woocommerce-ios/pull/4752)
- [x] Unsupported WCPay version state business logic (#4729)
- [x] WCPay not setup state UI (#4761)
- [x] WCPay not setup state business logic (#4731)
- [x] Stripe Account Restricted – Under Review state UI (PR https://github.com/woocommerce/woocommerce-ios/pull/4760)
- [x] Stripe Account Restricted – Under Review state business logic (#4731)
- [x] Stripe Account Restricted – Pending Requirements state UI (PR https://github.com/woocommerce/woocommerce-ios/pull/4762)
- [x] Stripe Account Restricted – Pending Requirements state business logic (#4731)
- [x] Stripe Account Restricted – Overdue Requirements state UI (PR https://github.com/woocommerce/woocommerce-ios/pull/4763)
- [x] Stripe Account Restricted – Overdue Requirements state business logic (#4731)
- [x] Stripe Account Rejected state UI (PR https://github.com/woocommerce/woocommerce-ios/pull/4764)
- [x] Stripe Account Rejected state business logic (#4731)
- [x] ~Live Account in Test Mode state UI~ (moved to #4774)
- [x] ~Live Account in Test Mode state business logic~ (moved to #4774)
- [x] Generic Error Screen (PR https://github.com/woocommerce/woocommerce-ios/pull/4793)
- [x] No connection error screen (#4794)

Other changes
- [x] Ordering Card Reader flow (#4782)
- [x] Add tracking (#4802)
- [x] Full UI review (test dark mode, accessibility fonts, RTL, landscape, iPad,...)

Matching Android issue: https://github.com/woocommerce/woocommerce-android/issues/4413
