### ISSUE TITLE
CPP Onboarding: Epic Phase 2

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#4774]
A continuation of #4611 

- [x] Live Account in Test Mode state UI
- [x] Live Account in Test Mode state business logic
- [x] Increase minimum required version of WCPay to 2.9.0 to handle BEGIN_OBJECT expected (waiting for release of wcpay 2.9.0)

**Comment by malinajirka** [comment]
This was done years ago but we forgot to close it.
