### ISSUE TITLE
[What's New Component] Fetch and Store Feature Announcements on App Launch

### ISSUE THREAD

**Issue by caiobzen** [woocommerce/woocommerce-ios#4862]
# Description 📜

In order to show the latest features available on WooCommerce app, we must fetch this data from a public WordPress API and persist it to show this data later on under _Settings_.

# Screenshot 📱
<img width="552" alt="image" src="https://user-images.githubusercontent.com/997521/130467303-a4f19440-85b4-486e-b3b1-1a7582681437.png">

# Expectation 🔍

1. When user opens the app, if not fetched yet, we must fetch the latest announcements and persist it on a plist file.
2. For now, just by looking at the network traffic and seeing that announcements was fetched only once is ok to validate the caching mechanism

# Todo ✓ 
- [x] Create Store
- [x] Invoke Announcements fetching with Yosemite Action
- [x] Implement system to prevent fetching features of the same version
- [x] Persist Announcements in Store
- [x] Handle Errors!
- [x] Implement request to WordPress announcements
- [x] Invoke Store from app coordination start
- [x] Remove WordPressKit dependency from Yosemite
