### ISSUE TITLE
[What's New Component] Present Latest Features on App Launch and Settings

### ISSUE THREAD

**Issue by caiobzen** [woocommerce/woocommerce-ios#4863]
# Description 📜

In order to show the latest features available on WooCommerce app, now that we've fetched and stored the latest announcements, next step is to build up the screen.

# Screenshot 📱
<img width="552" alt="image" src="https://user-images.githubusercontent.com/997521/130467303-a4f19440-85b4-486e-b3b1-1a7582681437.png">

# Expectation 🔍

1. When user opens the app, we must show the What's New Screen.
1. When user opens What's new on WooCommerce" under the app Settings, we must show the What's New Screen.

# Todo ✓ 
- [x] Create SwiftUI Views (Check existing ones on SwiftUI Components Folder)
- [x] iPad!
- [x] RTL!
- [x] Create Settings cell and prepare the navigation to the What's New Screen 
- [ ] Handle Dark Mode! 🌚
- [x] Create ViewController populated with ViewModel data
- [x] Handle Modal dismissal
- [x] Present What's New screen on App launch
- [x] Make sure we present What's New Component only once on app launch (toggle displayed property)
