### ISSUE TITLE
[What's New Component] Track user interaction

### ISSUE THREAD

**Issue by caiobzen** [woocommerce/woocommerce-ios#4864]
# Description 📜

Track the user interaction with What's New component.
- Event: What's New screen is opened (from app upgrade or app settings)

# Screenshot 📱
<img width="552" alt="image" src="https://user-images.githubusercontent.com/997521/130467303-a4f19440-85b4-486e-b3b1-1a7582681437.png">

# Expectation 🔍

1. Whenever What's New Component is presented, we must track this action.

# Todo ✓ 
- [ ] Add new event on _WooAnalyticsStat_
- [ ] Create new _WooAnalyticsEvent_
- [ ] Dispatch What's New Component presentation event from ViewModel

**Comment by rachelmcr** [comment]
I updated the issue to reflect our decision to only track one event, when the What's New screen is opened:

Event: `_feature_announcement_shown` with property `source: (app_upgrade|app_settings)` (`app_upgrade` when the screen appears after an upgrade to a new app version, or `app_settings` when it is opened from settings)

Discussion: p91TBi-5Wo-p2#comment-6810
