### ISSUE TITLE
Push notifications for all stores

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#5032]
Project thread p91TBi-5Oe-p2
iOS plan p91TBi-630-p2

## Goals

The main goal of this project is to notify merchants of sales and reviews for all of their stores on the go.

## Subtasks

- [x] Add a feature flag `pushNotificationsForAllStores` https://github.com/woocommerce/woocommerce-ios/pull/5033
- [x] Set `selected_blog_id` to an empty string when registering a device https://github.com/woocommerce/woocommerce-ios/pull/5033
- [x] Keep one `ReviewsCoordinator` per logged-in session for multiple stores, so that tapping on a new review notification from a different store opens the review details after switching store https://github.com/woocommerce/woocommerce-ios/pull/5044
- [ ] ~~(Pivoted to backend implementation) [Pending backend changes D67135] Create a `UNNotificationServiceExtension` target for modifying push notification content given payload from the server. Prerequisites & subtasks:~~
  - [x] Extract feature flag code to a separate Experiments framework https://github.com/woocommerce/woocommerce-ios/pull/5106
  - [ ] ~~Create a skeleton `UNNotificationServiceExtension` target https://github.com/woocommerce/woocommerce-ios/pull/5168~~
  - [ ] ~~Update notification content based on payload and feature flag in the notification service extension~~
- [x] [Pending backend changed D68195] Support new push notification payload format https://github.com/woocommerce/woocommerce-ios/pull/5299
- [x] Update badge number logic (not behind a feature flag): show 1 instead of the actual count for the selected store (ref p91TBi-66O-p2) https://github.com/woocommerce/woocommerce-ios/pull/5151
- [x] Change the copy of notice after switching store from "Switched to %1$@. You will only receive notifications from this store." to "Switched to %1$@." https://github.com/woocommerce/woocommerce-ios/pull/5137
- [x] Analytics: add event prop `is_from_selected_site` to `push_notification_received` and `push_notification_alert_pressed` events (ref p91TBi-6dd-p2) https://github.com/woocommerce/woocommerce-ios/pull/5222

Bug fixes:

- [x] Handle edge case: push notifications from a store that the app doesn’t know about yet (newly connected to Jetpack) https://github.com/woocommerce/woocommerce-ios/pull/5256

## Example screenshots

<img src="https://user-images.githubusercontent.com/1945542/134269139-878cf692-8876-4ac9-bdf4-74e90e4f4829.jpg" width="300" />

## After stable release

Can move these to a separate issue later.

- [x] #5401
- [x] Comment on p8wKgj-1Sx-p2__-17 to remove Zendesk agent access
