### ISSUE TITLE
Allow sharing SSR in the app

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#5071]
It would be great to have an easy way to share the WooCommerce System Status Report via the app directly rather than making people send this via their browser/email. 

For parity, this is the ongoing Android project: https://github.com/woocommerce/woocommerce-android/issues/4781

**Comment by iamgabrielma** [comment]
Related: https://github.com/woocommerce/woocommerce-ios/issues/684

**Comment by itsmeichigo** [comment]
Checklist: 

- [x] Update Networking layer with endpoint: `GET /wp-json/wc/v3/system_status` #5673 & #5678
- [x] Update Yosemite layer with new action and store to fetch SSR. #5688 
- [x] Add new item in Settings for SSR #5686 
- [x] Fetch SSR and error handling #5691 
- [x] Format SSR to match Core's #5693
- [x] Add features to copy ~and share~ SSR #5696
- [x] Add tracks #5696
- [x] Update RELEASE_NOTES.txt #5702
