### ISSUE TITLE
Product List: add support for product filtering by category

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#5159]
At the moment, the product lists can be filtered by Stock Status, Status, and Product Type. The capability to filter by category has been requested a few times by merchants and will be good to add to the app.
Related task on Android: https://github.com/woocommerce/woocommerce-android/issues/4578

**TODO**:
- [x] Fetch a list of products, filtered by category. [Networking/Yosemite layer changes]
- [x] Get a list of products from core data filtered by category. [Storage layer]
- [x] Add a feature flag for not exposing this feature until is completed to our merchants.
- [x] When the product filter screen is opened, fetch a list of categories (if there's internet) or get from DB if they are stored, and add them to the list of filters. The categories view should manage also pagination. [UI]
- [x] When a category filter is selected and the "Show products" button is tapped, include the category as criteria for filtering and show the result. [UI]
- [x] On the products list screen, if a category filter is already selected and the user taps the "Filters" button again, make sure the selected category is persisted and already selected in the "Category" filter. [UI]
- [x] Send the new filter to analytics

**Comment by toupper** [comment]
Added **TODO**:
- [x] Remove feature flag when the feature is done

**Comment by toupper** [comment]
>  Get a list of products from core data filtered by category. [Storage layer]

As discussed in https://github.com/woocommerce/woocommerce-ios/pull/5310, this is not implemented because:

- Retrieving a list of products from core data does not include the products belonging to the subcategories of the selected categories, unlike the remote request.
- Retrieving a list of products from core data breaks the pagination, and it is not consistent with the remote request pagination. We could improve it in the future implementing that pagination synchronizing mechanism.

**Comment by pmusolino** [comment]
Project completed with this PR: https://github.com/woocommerce/woocommerce-ios/pull/5388
