### ISSUE TITLE
Order List filters

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#5243]
Enable filtering orders by status or date range. This task also included a new design for the screen were tabs will be removed and a single order list will be displayed.

More details p91TBi-5L9-p2

### 💻  Tasks

- [x] Add a feature flag that shows/hides the order filter bar https://github.com/woocommerce/woocommerce-ios/pull/5248
- [x] Display the order filter bar https://github.com/woocommerce/woocommerce-ios/pull/5248
- [x] Remove tabs and keep a single order list https://github.com/woocommerce/woocommerce-ios/pull/5400
- [x] Enable filtering by order status and date range https://github.com/woocommerce/woocommerce-ios/pull/5423
- [x] Persist selected filters between sessions https://github.com/woocommerce/woocommerce-ios/pull/5481
- [x] Add filter for given ranges: Today, Last 2 Days, This Week, This Month https://github.com/woocommerce/woocommerce-ios/pull/5374
- [x] Remove status filters from search view https://github.com/woocommerce/woocommerce-ios/pull/5442
- [x] Add filter for custom date range https://github.com/woocommerce/woocommerce-ios/pull/5374
- [x] Tracking events https://github.com/woocommerce/woocommerce-ios/pull/5454
- [x] Update empty state that now looks a bit different from the design. https://github.com/woocommerce/woocommerce-ios/pull/5444
- [x] Allow multiples selection of statuses https://github.com/woocommerce/woocommerce-ios/pull/5462

#### Filters: Order Status
![2](https://user-images.githubusercontent.com/495617/137908436-c2b83fb9-aabc-461b-89da-dc59c1296dab.jpg)

#### Filters: Date Range
![Schermata 2021-10-19 alle 14 24 22](https://user-images.githubusercontent.com/495617/137908511-ee7d89f3-9dab-439d-988a-55f4e7eda885.png)
![Schermata 2021-10-19 alle 14 25 34](https://user-images.githubusercontent.com/495617/137908672-316b4b2f-2936-4a3e-84a1-e2846b18ecd8.png)
Merchants will also be able to select a Date Range. Options include Today, Last 2 Days, This Week, This Month.

#### Custom Range
![Schermata 2021-10-19 alle 14 26 38](https://user-images.githubusercontent.com/495617/137908845-45205e4b-8549-4d60-bdef-9205c128438a.png)
If possible, or as a stage 2 feature we could include the option to select a Custom Date Range. Either by selecting a start and end date via the OS native picker.

**Comment by pmusolino** [comment]
Issue that should be solved:
- I can't seem to select the current date in the date picker by tapping on the current date. Tapping on another date then back to the current date works
- If I already selected a range and edit again, then select the end date to be the same as the start date, I can't select a later end date anymore:
https://user-images.githubusercontent.com/1945542/141984077-ef09324c-124e-418e-a972-0520e920d7e9.mov
