### ISSUE TITLE
Simple Payments: Summary screen  Interactions

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#5346]
### Tasks
- [x] Track email changes
- [x] Track charge taxes switch
- [x] Allow to add an order note
- [x] Allow to edit an order note
