### ISSUE TITLE
Simple Payments: Take Payment by cash

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#5350]
<img width="341" alt="cash" src="https://user-images.githubusercontent.com/562080/140246954-351993a1-f81f-43fc-9bf7-0c5244e3c343.png">

### Tasks
- [x] Show alert confirmation before creating order
- [x] Create order and mark it as complete
- [x] Handle loading states & error
