### ISSUE TITLE
Simple Payments: Take Payment by card

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#5351]
### Tasks

- [x] Integrate with IPP to collect payment instantly
- [x] Redirect user to order list
- [x] Handle loading and error states
- [x] Show notice
- [ ] Reload order list
