### ISSUE TITLE
Simple Payments: Release Feature

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#5353]
### Tasks
- [x] Re-organize feature to swap prototype for the full implementation
- [x] Delete feature flag
- [x] Update release notes
