### ISSUE TITLE
Jetpack CP: detect a JCP site in `me/sites` calls (workaround: extra API requests to fetch site metadata and for JCP sites to show up in site picker)

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#5364]
Refs:
- P2 that explains JCP workarounds p91TBi-6lK-p2
- Android issue https://github.com/woocommerce/woocommerce-android/issues/5137
- Android FluxC PR https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2169

(Adapted from p2 post above)

## Why

This workaround is for usage of `/me/sites` and `/sites/{site_id}` endpoints, so that JCP sites show up in the site picker and the app can fetch correct info about JCP sites.

The app currently uses the endpoint `/me/sites` during the login and site picker to fetch sites of the current user. It also keeps fetching sites on each app launch to keep the list of current sites up-to-date, and to confirm that the site is still connected.

And the endpoint `/sites/{site_id}` is used in two scenarios:

- During the login step in pretty specific circumstances: login with site URL, and when we reach the site picker, we find out that the site doesn’t have WooCommerce
- On each cold start of the app to keep an updated set of the site’s metadata.

Both those endpoints are currently broken for Jetpack Connection Package sites, `/me/sites` has data that was sent during the initial connection, so it might be outdated, and `/sites/{site_id}` doesn’t work at all.

**This issue focuses on the changes for `/me/sites` calls (on app launch and when showing the site picker).**

## High-level tasks

- When fetching the full list of sites, the app will hit the endpoint `/me/sites` first, then for each site that doesn’t have Jetpack-the-plugin, it will use two additional requests to the remote site: `/wc/v3/settings?_fields=""` to check if WooCommerce is installed, and `/wp/v2/settings` to get the updated site’s metadata, and then update the app’s local database accordingly
- When fetching a single site, if the site doesn’t have jetpack-the-plugin, it will use just the last two endpoints `/wc/v3/settings` and `/wp/v2/settings` to update the app’s local database

## Subtasks

- [x] Storage: schema update - add 2 new attributes `isJetpackConnected: Bool` and `isJetpackThePluginInstalled` to `Site` https://github.com/woocommerce/woocommerce-ios/pull/5418
- [x] Netwroking: schema update - add 2 new attributes `isJetpackConnected: Bool` and `isJetpackThePluginInstalled` to `Site` https://github.com/woocommerce/woocommerce-ios/pull/5420
- [x] [Refactoring] Networking: adding a Combine publisher for making a network request https://github.com/woocommerce/woocommerce-ios/pull/5435
- [x] Networking: adding 2 endpoints `/wp/v2/settings` and `/wc/v3/settings?_fields=""` to `AccountRemote` for the workaround https://github.com/woocommerce/woocommerce-ios/pull/5453
- [x] Yosemite: updating `AccountStore.loadSites` to call `/wp/v2/settings` and `/wc/v3/settings?_fields=""` for JCP sites so that their metadata and `isWooCommerceActive` are accurate https://github.com/woocommerce/woocommerce-ios/pull/5466
- [x] Only apply the workaround behind a feature flag https://github.com/woocommerce/woocommerce-ios/pull/5467
