### ISSUE TITLE
Jetpack CP: install Jetpack from the app

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#5365]
Refs:
- Android issue https://github.com/woocommerce/woocommerce-android/issues/4865
- Slack discussion p1635988584012800-slack-C02HHDEUEH
- API p2 p91TBi-6sO-p2

Steps:
- Installing Jetpack: `WPCOM.API v 1.1 POST /jetpack-blogs/<site_id>/rest-api` with path `wp/v2/plugins/` and body `{ "slug" : "jetpack" }`
- Activating Jetpack (by default when a plugin is installed, it's set as deactivated. This step activates it): `WPCOM.API v 1.1 POST /jetpack-blogs/<site_id>/rest-api` with path `wp/v2/plugins/jetpack/jetpack` and body: `{ "status" : "active" }`

- Making sure Jetpack is installed: `WPCOM.API v 1.1 GET /jetpack-blogs/<site_id>/rest-api` with path `wp/v2/plugins/jetpack/jetpack`

Given an existing and connected Jetpack CP plugin, when the Jetpack plugin is activated for the first time, then it will also be connected automatically.

<img width="916" alt="Screen Shot 2021-11-05 at 3 26 09 PM" src="https://user-images.githubusercontent.com/1945542/140473713-24e389d8-e3ec-4856-8e93-4fc9d7ddcc82.png">

**Comment by itsmeichigo** [comment]
Subtasks:
- [x] Create Install Jetpack initial screen #5475 
- [x] Create Jetpack installation flow screen and navigate from the initial screen (UI only) #5476 
- [x] Add remote endpoints for 3 steps to install Jetpack (Networking & Yosemite) #5504 
- [x] Update Yosemite layer for 3 new actions #5507
- [x] Integrate the first 2 installation steps with UI #5525
- [x] Workaround to sync site's option #5526 
- [x] Add retry mechanism and check for plugin before installing #5565 
- [x] Error handling #5568 
- [x] Update Networking & Storage to get `admin_url` for Site #5611 
- [x] Replace hardcoded WPAdmin URL #5568 
- [x] Auto retry for checking connection #5716 
- [x] Add tracking events: #5732
    - Tap on “Install Jetpack In WP-Admin” button --> `jetpack_install_in_wpadmin_button_tapped`
    - Tap on “Contact Support” --> `jetpack_install_contact_support_button_tapped`
    - Then we can log `jetpack_install_succeeded` if Jetpack-the-plugin becomes active. 
    - We log `jetpack_install_failed` whenever an error is returned from any installation step.

**Comment by itsmeichigo** [comment]
Closing this issue since all subtasks have been completed.
