### ISSUE TITLE
Order Creation: Order Status section UI

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#5406]
When a new order is created, the default order status is `pending`. We need a section at the top of the New Order screen showing the current date and editable order status (like in Order Details). When the `Edit` button is tapped, a list opens to select a new status.

### Tasks

Feel free to divide these into separate subtasks:

- [ ] Display current date
- [ ] Display order status (`pending` by default)
- [ ] Select different order status from a list

Order Status section|Order Status list
-|-
![iOS-CreateOrder-Status](https://user-images.githubusercontent.com/8658164/141468332-6c3c8adf-905f-4d3f-a296-b7122095e888.png)|![iOS-CreateOrder-Edit Discount](https://user-images.githubusercontent.com/8658164/141468368-8955a6b2-0187-41eb-99d2-8f01f8a720aa.png)
