### ISSUE TITLE
Order Creation: API support for order status when creating an order

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#5407]
The order status for a new order needs to be added to the request sent to the order creation endpoint (`POST /wc/v3/orders`) when the order is created.

### Tasks

Feel free to divide these into separate subtasks:

- [ ] Add Networking support for sending the order status to the order creation endpoint
- [ ] Add Yosemite support for sending the order status to the order creation endpoint
- [x] Add UI integration for including the order status selected on the New Order screen when the new order is created

Sample request:

```
{
  "status": "processing"
}
```
