### ISSUE TITLE
Order Creation: Products section UI with non-variable products

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#5408]
To add products to a new order, we need a Products section with an `Add product` button on the New Order screen. When the button is tapped, an Add Product screen is displayed with a searchable list of products. For this task, do not include variable products in the list (they will be added in a separate issue).

### Tasks

Feel free to divide these into separate subtasks:

- [x] UI for Products section with `Add product` button on New Order screen
- [x] UI for Product section to display products added to the order
- [x] UI for Add Product screen
- [x] Products section: real data showing selected products
- [x] Products section: change the quantity of a product added to the order
- [x] Products section: remove a product from the order
- [x] Add Product: real data (from sync/storage) with list of non-variable products
- [x] Add Product: select a product and have it added to the order
- [x] UI polish: Check padding and edge-to-edge landscape mode (especially dividers)

Products section (no products)|Add Product|Products section (1 product)|Remove Product
-|-|-|-
<img src="https://user-images.githubusercontent.com/8658164/141468460-47ef4d51-46d9-428c-828b-aa2b1e8d2763.png" width="300px">|<img src="https://user-images.githubusercontent.com/8658164/141468488-c2f327e8-9c0b-4061-9a65-55858019f248.png" width="300px">|<img src="https://user-images.githubusercontent.com/8658164/143474877-f3522c25-57ce-4aa8-856a-9c91ae09ceae.png" width="300px">|<img src="https://user-images.githubusercontent.com/8658164/146759514-7d623aa1-8d5f-4a8c-b3cb-4b8096ea9d2e.png" width="300px">
