### ISSUE TITLE
Order Creation: API support for existing products when creating an order

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#5410]
The products added to the order (product ID and quantity) need to be added to the request sent to the order creation endpoint (`POST /wc/v3/orders`) when the order is created.

### Tasks

Feel free to divide these into separate subtasks:

- [ ] Add Networking support for sending products (product ID and quantity) to the order creation endpoint
- [ ] Add Yosemite support for sending products (product ID and quantity) to the order creation endpoint
- [ ] Add UI integration for including the products (product ID and quantity) when the order is created on the New Order screen

Sample request:

```
{
  "line_items": [
    {
      "product_id": 196,
      "quantity": 2
    },
    {
      "product_id": 206,
      "quantity": 3
    }
  ]
}
```
