### ISSUE TITLE
Order Creation: Customer section UI (billing & shipping details)

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#5412]
To add customer details (name, email, phone, and billing and shipping addresses) to a new order, we need a Customer section with an `Add Customer` button on the New Order screen. There is some discussion about this naming, see the Figma designs and discussion for latest details: p91TBi-6xc-p2#comment-7214

When the `Add Customer` button is tapped, it opens a form to enter the customer details. For milestone 1, we will only create orders for guest customers (with no UI to select existing customers).

### Tasks

Feel free to divide these into separate subtasks:

- [x] UI for Customer section with `Add Customer` button on New Order screen
- [x] Refactor `EditOrderAddressFormViewModel` to allow reuse of address form between Order Editing and Creation
- [x] Connect Address Form to New Order view
- [x] UI for Customer section with customer details (after entering billing/shipping information)
- [x] ~~UI for Summary screen with customer data~~
- [x] Add a toggle for "different shipping address" with expanding form
- [ ] Connect data for both address types from expanding form

Customer section|Billing & Shipping form|Customer section (completed)
-|-|-
![iOS-CreateOrder-Customer](https://user-images.githubusercontent.com/8658164/141469081-2cb63703-605c-44bd-9045-ed363a9ff905.png)|![iOS-CreateOrder-BillingShipping](https://user-images.githubusercontent.com/8658164/141469118-d5e98d22-d2db-4472-9f35-da4bb46715ef.png)|![iOS-CreateOrder (2)](https://user-images.githubusercontent.com/8658164/141775190-2108d853-42d7-4f4b-bba7-ef40dbef7ae1.png)
