### ISSUE TITLE
Analytics: Display revenue/orders/products

### ISSUE THREAD

**Issue by ealeksandrov** [woocommerce/woocommerce-ios#5651]
## Description

As part of the Analytics project, we want to display the revenue/orders and products for a given date range of a store.

## Subtasks

- [ ] Add a date range selector at the top of the screen. Default data to be displayed would be the current day data.
  - No need for “custom” option for first version.
- [ ] Display the Revenue card.
  - [ ] The total sales and Net Sales.
  - [ ] The % of sales compared to the previous date range.
  - [ ] The “See Report” button would redirect to the wp-admin for the particular report.
  - No need for graphs for first version.
- [ ] Display the Orders card.
  - [ ] The total orders and Average Order Value.
  - [ ] The % value compared to the previous date range.
  - [ ] The “See Report” button would redirect to the wp-admin for the particular report.
  - No need for graphs for first version.
- [ ] Display the Products card.
  - [ ] The total items sold.
  - [ ] The list of products + the quantity of that product sold.
  - [ ] The “See Report” button would redirect to the wp-admin for the particular report.

## Screenshots

All cards overview:
<img width=400 src=https://user-images.githubusercontent.com/3132438/145481732-12619f8e-cd6c-4ac3-937d-e6bd390a040d.jpeg>

Date picker:
<img width=400 src=https://user-images.githubusercontent.com/3132438/145481737-db134e5d-28e0-4112-ae37-1bf645d0eac2.jpeg>
