### ISSUE TITLE
Coupons: Show coupon details

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#5765]
When tapping a coupon on the coupon list, users should be navigated to a screen for details of that coupon. The screen should include:

- [x] Description, code, and expiry status. #5999 
- [x] Update remote to retrieve a single coupon #6002 
- [x] Update apply rules for coupon #6105 
- [x] Performance of the coupon #6110
- [ ] ~More specific details~
- [x] Row to navigate to usage details #6161 
- [x] Add action sheet to copy and share coupon code #6117

<img width="301" alt="Screen Shot 2021-12-27 at 17 08 56" src="https://user-images.githubusercontent.com/5533851/147461940-e8dd9c7e-20b8-4b49-9f35-c4b65e5297a1.png">
