### ISSUE TITLE
Coupons: Add pagination and pull-to-refresh for coupon list

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#5767]
To improve the UX for the coupon list, a few features should be added:

- [x] Simplify state management #5813 
- [x] Pagination: coupons should be fetched by pages to ensure the performance of the list #5827
- [x] Pull-to-refresh: to update the list with the latest data #5828

**Comment by itsmeichigo** [comment]
Closing this issue since sub-tasks are all done.
