### ISSUE TITLE
Coupons: Add search functionality for coupon list

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#5768]
Similar to Order and Product lists, we should also have functionality to search for any specific coupon on the list based on coupon code or description.

<img src="https://user-images.githubusercontent.com/5533851/147465044-08778aab-322e-448a-a8be-385ceb706c23.png" width=320 />
Search functionality on Order list

**Comment by itsmeichigo** [comment]
No `search` field is found in the API documentation for fetching the coupon list though, we'll may have to either update the API or remove this task out of the project scope.

**Comment by itsmeichigo** [comment]
Checklist:

- [x] Networking: Add new endpoint in CouponsRemote for searching coupon #5960 
- [x] Storage: Add new entity for CouponSearchResults #5962
- [ ] Yosemite: Update CouponAction and CouponStore with search coupons functionality #5975 
- [ ] UI: Add CouponSearchUICommand and update Coupon list screen with entry point to search screen #5982
