### ISSUE TITLE
Hub Menu Tracking Events

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#5798]
When the Hub Menu will be released, we should implement some tracking events.
Here are some proposals:

- [x] `hub_menu_tab_selected`- Tracks "Hub Menu Tab Selected" Events. We should remove the event for the re-selection of the reviews tab.
- [x] `hub_menu_tab_reselected` - Tracks "Hub Menu Tab Re Selected" Events. We should remove the event for the selection of the reviews tab.
- [x] `hub_menu_switch_store_tapped` - Tracks when the user press the "Switch Store" button in the hub menu. We should also remove the `settings_selected_site_tapped` event.
- [x] ` hub_menu_option_tapped` -  Tracks when the user press one of the options in the hub menu. We will pass these properties for the moment: `view_store`, `admin_menu`, `reviews`, `coupons`
- [x] `hub_menu_settings_tapped` - Tracks when the user press the Settings button in the hub menu. We should also remove the `main_menu_settings_tapped` event.
