### ISSUE TITLE
Simple Payments: Update tax information in Summary screen to reflect more accurate information

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#5809]
# Problem
Currently, the tax amount displayed on the summary screen of Simple Payments flow can be inaccurate. As @shiki reported: when the default tax is set to 6.625% on the WooCommerce Admin page:
 
![image](https://user-images.githubusercontent.com/5533851/148157838-40e0d0be-2951-41ba-84c4-0d3d19cd3dd4.png)

And then he created a Simple Payment order with $1.29 as the amount. Notice that the tax rate that is presented is 6.98% ❗️, not the configured 6.625%. 

<img src="https://user-images.githubusercontent.com/5533851/148158042-63bcd311-678a-443b-b6bc-1809da3eb9c8.jpeg" width=320 />

# Expectation
Let's follow how tax is displayed in order details on the WooCommerce Admin Page with separate tax lines:

![rates-core](https://user-images.githubusercontent.com/5533851/148158539-b532022f-3ba1-49fd-b83a-fd8456341b82.jpeg)

These tax lines can be found in the response of order details.

The final summary screen should look like so:
![rates-app](https://user-images.githubusercontent.com/5533851/148158648-96d3a3ea-8ee4-4c56-9d29-3000a7795f4f.jpeg)

(Internal ref: p91TBi-749-p2)

**Comment by selanthiraiyan** [comment]
### Subtasks

- [x] Introduce `OrderTaxLine` in Networking layer - https://github.com/woocommerce/woocommerce-ios/pull/5916
- [x] Introduce `OrderTaxLine` Storage layer - https://github.com/woocommerce/woocommerce-ios/pull/5918
- [x]  Introduce `OrderTaxLine` Yosemite layer - https://github.com/woocommerce/woocommerce-ios/pull/5931
- [x] Add feature flag to represent the compound tax rate UI - https://github.com/woocommerce/woocommerce-ios/pull/5923
- [x] `TitleAndValueRow` - To make longer `title` text look nicer use `multilineTextAlignment` modifier with `leading` alignment. Check the multi line behaviour of `value` text and apply `multilineTextAlignment` with `trailing` alignment. Update SwiftUI preview to demo multi-line cases. - https://github.com/woocommerce/woocommerce-ios/pull/5963
- [x] Show `taxLines` from server behind `taxLinesInSimplePayments` feature flag. To avoid behaviour change, show Tax row with zero values if `taxLines` are empty.  - https://github.com/woocommerce/woocommerce-ios/pull/5964
