### ISSUE TITLE
Master Issue for Repo Cleaning

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#581]
Go through each item and remove sensitive URLs, screenshots, and data

- [x] Scrub **open issues**
- [x] Scrub closed issues of sensitive info
- [x] Scrub open PRs
- [x] Scrub closed PRs
- [x] Page 1-5
- [x] Page 6-10
- [x] Page 11-15
- [x] Scrub commits of sensitive data 
- [x] Notify devs that cleaned repo is getting pushed
- [x] Delete local copy of repo and git clone cleaned repo
- [x] Contact GitHub support for access to hidden ref force push
- [x] ~force-push repo changes to hidden refs~ // no access

Related: Android master list https://github.com/woocommerce/woocommerce-android/issues/664
