### ISSUE TITLE
[Home Screen updates - Inbox] Implement the Inbox View

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#5954]
We should implement the view (in SwiftUI) displaying all the entries of the Inbox notifications.
Feel free to split the task in subtasks.
Figma is always the source of truth: vbzgTKHV9XsyyN5cxxAuhv-fi-443%3A8556

dark | light
-- | --
<img width="268" alt="Screen Shot 2022-02-11 at 9 21 55 AM" src="https://user-images.githubusercontent.com/1945542/153523900-5c7a4d15-45a2-44e8-81b0-3832de944944.png"> | <img width="267" alt="Screen Shot 2022-02-11 at 9 22 05 AM" src="https://user-images.githubusercontent.com/1945542/153523910-211b50bb-a46f-4e84-bf25-2288e3ffbc48.png">

## Subtasks

- [x] Inbox note list - skeleton list (action handling in https://github.com/woocommerce/woocommerce-ios/issues/5955) https://github.com/woocommerce/woocommerce-ios/pull/6159
- [x] Note title, HTML content using `AttributedText`, action buttons https://github.com/woocommerce/woocommerce-ios/pull/6160
- [x] Add header with icon and relative date https://github.com/woocommerce/woocommerce-ios/pull/6172
- [x] Update empty state vbzgTKHV9XsyyN5cxxAuhv-fi-443%3A14458 https://github.com/woocommerce/woocommerce-ios/pull/6184
- [x] Show notes from storage https://github.com/woocommerce/woocommerce-ios/pull/6210
- [x] Add pull-to-refresh support (originally using `refreshable` iOS 15+ p1644830464328879-slack-CGPNUU63E, but we removed `List` usage) https://github.com/woocommerce/woocommerce-ios/pull/6272
- [x] Remove icon (discussion: p91TBi-7AK-p2) https://github.com/woocommerce/woocommerce-ios/pull/6273

---
### Maybe
- Look into implementing HTML content with a webview to fix issues
- Fix placeholder weird height change https://github.com/woocommerce/woocommerce-ios/pull/6176#pullrequestreview-884005261 --> moved to https://github.com/woocommerce/woocommerce-ios/issues/6190

dark | light
-- | --
<img width="398" alt="Screen Shot 2022-02-10 at 3 55 17 PM" src="https://user-images.githubusercontent.com/1945542/153363450-92d24e3c-e06c-4b50-b24c-ae0dcac8338f.png"> | <img width="267" alt="Screen Shot 2022-02-10 at 3 55 40 PM" src="https://user-images.githubusercontent.com/1945542/153363472-def793e2-6658-4672-a482-75857e93a440.png">

**Comment by jaclync** [comment]
Closing this issue now that all the subtasks are done.
