### ISSUE TITLE
Product Variations: Create new Bulk Price Settings screen

### ISSUE THREAD

**Issue by chrisKns** [woocommerce/woocommerce-ios#6242]
This is part of the Bulk update prices for Product Variations project p91TBi-7x3-p2. See parent issue #5762. This issue has the sub-tasks for creating a new Price update screen that will change the price on a collection of variations:

<img src="https://user-images.githubusercontent.com/562080/152804794-5bf02917-c726-4df1-96e5-0d262c994d2a.png" width=40% height=20%>

Implement after #6239 & #6240

We will create a "bulk price settings" screen to allow a user to enter a sale/regular price that will be applied in all the product variations when the user taps a "save" button. The user will remain in the same screen in case of save errors. Upon successfully saving the new price change, it will return in the previous "Bulk update Screen". 

Sub-tasks:
- [x] Refactor extract price validation methods to reuse them later in  the view model #6296
- [x] Add initial view model handing the price change events and "save" button states(enabled, disabled, loading) #6374
- [x] Add handling taps of button "save" in the view model  #6374 
- [x] Add initial "bulk price settings" view controller, with a price field that will send the price change events to the view model #6403
- [x] Update "bulk price settings" view controller, to display the footer message. A method in the view model will provide the formatted string #6403
- [x] Update "bulk price settings" view controller to add the “save” button and send the save event to the view model #6403
- [ ] Update "bulk price settings" view controller to add display for error Notices after the user taps save with error
- [ ] Update UI of `UnitInputTableViewCell` to match style of the mockups
- [ ] Update "Bulk update Screen"  (see #6239) to show success notice on successful price update.
