### ISSUE TITLE
Shipping Labels: Clean up feature flags

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#6269]
Since the last milestone of Shipping Labels project have been released since October 2021, I think it's time to clean up the feature flags now. There are a few things to take care of for this task:

- [x] Remove all flags: `shippingLabelsM2M3`, `shippingLabelsInternational`, `shippingLabelsAddPaymentMethods`, `shippingLabelsAddCustomPackages`, `shippingLabelsMultiPackage` #6270 
- [x] Remove `ShippingLabelPackageDetails` along with its view model since it has been replaced with `ShippingLabelPackagesForm` when the multi-package feature was introduced. #6281
- [x] Update the `checkCreationEligibility` remote to remove parameters `can_create_customs_form`, `can_create_payment_method` and `can_create_package` since these `true` as default values. #6283

**Comment by itsmeichigo** [comment]
Closing this issue since all subtasks have been completed.
