### ISSUE TITLE
Order List: Search

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#63]
### Design:
We're implementing a new entity, to be called **OrderSearchResults**, which will allow us to map a given **Keyword** to a collection of Orders.

This allows us to display cached search results, when in offline mode, and also makes it possible to rely on ResultsController and EntityListener to keep all of the involved ViewControllers in sync.

### Yosemite:
- [x] Search Orders Action #558

### Orders List:
- [x] Wire the new Search UI #557
- [x] Exclude Orders not retrieved via regular scrolling (Search Results Cache) #559

### New Search UI:
- [x] Wire **OrderAction.search** #559
- [x] Infinite Scroll Support #559
- [x] Wire Details UI #559
- [x] Loading + Empty States #559
- [x] Verify (all of the) Order Detail Flows work fine! #559
