### ISSUE TITLE
Split view for Orders tab

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#6381]
We'd like to grow our tablet usage by making a suite of optimization:

- Implement Order List split screen layout

<img width="882" alt="Screen Shot 2021-07-06 at 2 47 31 PM" src="https://user-images.githubusercontent.com/28450084/124602458-29d9bd00-de69-11eb-85a3-57b84b836fd9.png">

**Comment by itsmeichigo** [comment]
Checklist:

- [x] Update Orders list #6387 
- [x] Feature flag for split view on Orders tab #6413
- [x] Hide updates behind the feature flag #6415
- [x] Present New Order flow as a modal #6397 
- [x] Fix offline banner & initial detail column state #6399
- [x] Fix weird issue when entering Editing customer note #6406
- [x] Fix collapsed view on large screen phones when rotating #6424 
- [ ] ~Fix incorrect "<" button color in split view~ ([no longer happens](https://github.com/woocommerce/woocommerce-ios/pull/6399#issuecomment-1078654642))
- [x] Fix offline banner position #6447 
- [x] Fix edge case when an order is selected on secondary column and the list on the primary column is updated without the item #6972 
- [x] Fix edge case when the layout of empty view on order list is not correct on iOS 14 ([reference here](https://github.com/woocommerce/woocommerce-ios/pull/6424#pullrequestreview-909618466)). #6951 
- [x] Fix issue showing order details in the primary column after creation. ([reference here](https://github.com/woocommerce/woocommerce-ios/pull/6972#pullrequestreview-988746900))  #7243

**Comment by itsmeichigo** [comment]
Closing as all tasks have been completed, waiting for the feature flag to be enabled.
