### ISSUE TITLE
Coupons: Add new select products flow

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#6489]
We have a new and shiny design for the select products flow:

<img width="541" alt="Screen Shot 2022-03-23 at 14 23 10" src="https://user-images.githubusercontent.com/5533851/159646087-51d7c5cb-fb12-49b7-bd36-94a09b88fc52.png">

**Comment by itsmeichigo** [comment]
The view should be configurable so that it can be reused for selecting excluded products:

<img width="254" alt="Screen Shot 2022-03-30 at 11 58 48" src="https://user-images.githubusercontent.com/5533851/160754509-c9fc69ba-f196-480b-b97e-e7a3acee04d2.png">

**Comment by itsmeichigo** [comment]
After some struggle with updating the existing [`ProductListSelectorViewController`](https://github.com/woocommerce/woocommerce-ios/blob/trunk/WooCommerce/Classes/ViewRelated/Products/ProductListSelector/ProductListSelectorViewController.swift), we've decided to take another direction to make [`AddProductToOrder`](https://github.com/woocommerce/woocommerce-ios/blob/trunk/WooCommerce/Classes/ViewRelated/Orders/Order%20Creation/ProductsSection/AddProductToOrder.swift) reusable and customizable since this screen is matching quite closely with the Select Products and Exclude Products screen of the Coupon flow.

Subtasks: 

- [x] Rename `AddProductToOrder` to `ProductSelector` and move it along with related files to under `Products` group in the project structure for easier discovery. #6664
- [x] Make the title of `ProductSelector` customizable to be reused in different flows. #6672
- [x] Support multiple selections (with checkboxes and a Done button at the bottom). #6679
- [x] Add optional filter functionality #6696 
- [x] Add optional ~Select all~ Clear selection button #6715 
- [x] Revert changes to Linked Products flow #6720 

Internal discussion: p1649844987957019-slack-C02TD63FZA8
