### ISSUE TITLE
Order List Master Checklist

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#66]
**Order List Master Issue**

- [ ] Networking: Retrieve Orders
- [ ] Storage: Store a collection of Orders
- [ ] Service Layer: Request Batch of Orders, w/"starting at" 
- [ ] Displaying Order Cells
- [ ] Infinite Scroll
- [ ] Pull-to-refresh
- [ ] Filtering
- [ ] Search
- [ ] Group orders in fuzzy date sections
