### ISSUE TITLE
[Mobile Payments] Run onboarding flow when tapping "Collect Payment" in Order Details

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#6607]
# Background
Onboarding to Card Present Payments isn't neccesarily a one-time process: changes in the environment and status of a merchant's WCPay/Stripe account can lead to issues that are communicated and resolved via the Onboarding flow.

At present, we only trigger that flow from Settings. If a merchant tries to accept a payment without being in the `.complete` state, they will be unable to connect to a card reader and take that payment. We don't currently tell them anything about the failure or how they can resolve it.

To help merchants resolve this situation, we will show the Onboarding flow for any tap on a payment button when the onboarding state isn't `.complete`.

Context: pdfdoF-yu-p2

## Actual behaviour
1. Install and activate WCPay and the Stripe Extension in a USA store.
2. Set a network breakpoint on `https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/{siteID}/rest-api/?json=true&path=/wc/v3/payments/accounts`
3. Navigate to an order eligible for IPP: Orders > Order Details
4. Tap "Collect Payment"
5. The app starts the payment flow, but fails to connect to the reader with a generic error.

## Expected behaviour
1. Install and activate WCPay and the Stripe Extension in a USA store.
2. Navigate to an order eligible for IPP: Orders > Order Details
3. Tap "Collect Payment"
4. The app informs the merchant that it is not possible to collect payments because they have both plugins installed and activated. 

![Order Details screen collect payment](https://user-images.githubusercontent.com/2472348/165948522-76218b80-1f4b-49ab-bdfc-dac082ea3ac0.jpg)

## Subtasks
- [x] Extract CardPaymentReadiness logic to check whether Onboarding was successful, and expose as a Combine publisher.
- [x] Add preliminary check in `CardPaymentReadiness` for whether a reader is connected, to bypass onboarding check (requires refactor of existing `checkCardReaderConnected` action.)
- [x] Share data source for Onboarding between CardPaymentReadiness and Onboarding flow.
- [x] Trigger readiness check when Order Details is opened: 0.5
- [x] Refresh readiness check when pull-to-refresh is used
- [x] Display Onboarding flow when required, on `Collect Payment`: 0.5
- [x] Return to the collect payment flow when onboarding status is `complete`: 0.5
- [x] Enable Onboarding flow's `complete` step to be hidden (optional): 0.5

**Comment by jaclync** [comment]
Let's also consider adding this onboarding flow to Issue Refund action when in-person refund is required (e.g. for Interac in Canada) (original discussion: p1649662079602789/1649658303.417889-slack-C025A8VV728)

**Comment by joshheald** [comment]
I can't reproduce this exact behaviour, it's a bit different: 

When both plugins are active, the `Collect Payment` button only shows for a tiny fraction of a second for unpaid orders, it remains at `Issue Refund`.

In this video, I start with both plugins activated, then when I back out of the Order Details screen I deactivate the Stripe Gateway. Then when I go back in to Order Details, the `Collect Payment` button does show.

https://user-images.githubusercontent.com/2472348/165276224-b2c4e2b3-52fd-4830-859e-2b969fb08713.mp4

This goes back to at least the 8.7 release in mid-March.


With network conditioning through Proxyman, it's still too short on screen for me to be able to tap it.

With a breakpoint in Proxyman on the response from `/payments/accounts`, I can see the button for long enough to tap it, but the app doesn't fail silently, it goes in to the payment collection flow (which is unexpected) and fails with an unknown error, I think *possibly* because we make a malformed request for the reader connection token, since we don't have the account.


I tried connecting the reader in settings first (with only WCPay active) then activating the Stripe Gateway too. In that case I was able sometimes to tap `Collect Payment` and it brought up the flow, which failed with unknown errors.


The Expected Behaviour above is definitely not implemented, so this needs work... but I wanted to note my findings on repro for future reference when we're testing.

**Comment by joshheald** [comment]
> Let's also consider adding this onboarding flow to Issue Refund action when in-person refund is required (e.g. for Interac in Canada) (original discussion: p1649662079602789/1649658303.417889-slack-C025A8VV728)

Added issue for this:
- #6754
