### ISSUE TITLE
Orders Details: Avoid duplicated code for Country and State selector in Order Details

### ISSUE THREAD

**Issue by toupper** [woocommerce/woocommerce-ios#6667]
`CountrySelectorCommand`/`StateSelectorCommand` and `CountrySelectorViewModel`/`StateSelectorViewModel` share the majority of its code. To avoid the downsides of having duplicated code, it would be nice to collapse these classes into one of each, injecting the list of countries or states into these new elements. If necessary, we can abstract `State` and `Country` into one protocol to make it more generic.

### Tasks
- [ ] Collapse `CountrySelectorCommand`/`StateSelectorCommand` into one class
- [ ] Collapse `CountrySelectorViewModel`/`StateSelectorViewModel` into one class
- [ ] Adapt Unit Tests

**Comment by JorgeMucientes** [comment]
Closing as part of the Woo Mobile GitHub stale-issue audit cleanup.

Rationale for closing:
- Listed in audit section "Potentially Stale / Good Candidates To Close Still Open, Outside Grouped Commerce Rows (40)". Last GitHub activity in the audit: 2022-09-13 1388d. Audit recommendation: Keep / Manual review. Audit rationale: Open in the 2026-07-02 live snapshot; last GitHub update 2022-09-13 (1388d ago). Current-code signal from rg: `CountrySelectorViewModel` appears in `WooCommerce/WooCommerceTests/ViewRelated/Orders/Order Details/Addresses/CountrySelector/CountrySelectorViewModelTests.swift`. Current-code signal from rg: `StateSelectorViewModel` appears in `WooCommerce/Classes/ViewRelated/Orders/Order Details/Address Edit/AddressFormViewModel.swift`.. No longer in a protected grouped area in this report; close as stale backlog cleanup and reopen if still reproducible or product-owned.

Reopen if this is still reproducible, product-owned, or should be tracked in a current Linear issue.
