### ISSUE TITLE
[Mobile Payments] Migrate PaymentCaptureOrchestrator to the new Swift Concurrency Model

### ISSUE THREAD

**Issue by toupper** [woocommerce/woocommerce-ios#6931]
### Description
With this issue, we want to migrate `PaymentCaptureOrchestrator` internally and externally to the new Swift concurrency model. That means that its clients (e.g `CollectOrderPaymentUseCase`) will have to adapt as well as part of this issue.

Basically, we have two public functions to be addressed: 

```
func collectPayment(for order: Order,
                        orderTotal: NSDecimalNumber,
                        paymentGatewayAccount: PaymentGatewayAccount,
                        paymentMethodTypes: [String],
                        stripeSmallestCurrencyUnitMultiplier: Decimal,
                        onWaitingForInput: @escaping () -> Void,
                        onProcessingMessage: @escaping () -> Void,
                        onDisplayMessage: @escaping (String) -> Void,
                        onProcessingCompletion: @escaping (PaymentIntent) -> Void,
                        onCompletion: @escaping (Result<CardPresentCapturedPaymentData, Error>) -> Void)
```
As you can see, there are multiple callbacks here used. As in https://github.com/woocommerce/woocommerce-ios/issues/6930, we can make use of [AsyncStream](https://developer.apple.com/documentation/swift/asyncstream) for that, returning an enum containing cases for every callback.
Secondly we have `func cancelPayment(onCompletion: @escaping (Result<Void, Error>) -> Void)`. This can easily be converted to an `async throws` function.

### Tasks
- [ ] Convert `collectPayment` function
- [ ] Convert `cancelPayment` function
- [ ] Adapt class clients (e.g `CollectOrderPaymentUseCase`)
- [ ] Unit tests

**Comment by Ecarrion** [comment]
>  That means that its clients (e.g CollectOrderPaymentUseCase) will have to adapt as well as part of this issue.

Do you think we can maintain both interfaces and implementations while we test that it is stable enough? Not sure how many clients/consumers it has(Thinking about simple payments & order details), but if there are multiple it may make sense to migrate them incrementally.

**Comment by toupper** [comment]
Thanks, @Ecarrion for your comment, that's a good point!
For this class, we have only one client/consumer, the `CollectOrderPaymentUseCase`, so I assume that it will be straightforward. But you brought an interesting topic also for other issues on this project, whether to use a feature flag and/or treat it as an experimental feature, so we can keep both approaches during testing.
You can read more about the project here pdfdoF-OG-p2, please feel free to add any concerns or suggestions there as a comment as well. 😃

**Comment by toupper** [comment]
Closing as part of a migration of our issue tracking to an internal system. If this is still relevant, we'll address it based on priority and impact. Thanks a lot! 🙏
