### ISSUE TITLE
[Mobile Payments] Migrate CardPresentRefundOrchestrator to the new Swift Concurrency Model 

### ISSUE THREAD

**Issue by toupper** [woocommerce/woocommerce-ios#6944]
### Description
With this issue, we want to migrate `CardPresentRefundOrchestrator` internally and externally to the new Swift concurrency model. That means that its clients (i.e `RefundSubmissionUseCase`) will have to adapt as well as part of this issue.

Basically, we have two public functions to be addressed: 

```
func refund(amount: Decimal,
                charge: WCPayCharge,
                paymentGatewayAccount: PaymentGatewayAccount,
                onWaitingForInput: @escaping () -> Void,
                onProcessingMessage: @escaping () -> Void,
                onDisplayMessage: @escaping (String) -> Void,
                onCompletion: @escaping (Result<Void, Error>) -> Void)
```
Here there are multiple callbacks here used. As in https://github.com/woocommerce/woocommerce-ios/issues/6930, we can make use of [AsyncStream](https://developer.apple.com/documentation/swift/asyncstream) for that, returning an enum containing cases for every callback. As the last one can fail, the function should throw.
Secondly we have `func cancelRefund(onCompletion: @escaping (Result<Void, Error>) -> Void)`. This can easily be converted to an `async throws` function.

### Tasks
- [ ] Convert `refund` function
- [ ] Convert `cancelRefund` function
- [ ] Adapt class clients (e.g `RefundSubmissionUseCase`)
- [ ] Unit tests

**Comment by toupper** [comment]
Closing as part of a migration of our issue tracking to an internal system. If this is still relevant, we'll address it based on priority and impact. Thanks a lot! 🙏
