### ISSUE TITLE
[Unified Order Editing] Refactor Order Creation form to be used with an existing order

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#6961]
The order creation form should be able to take an existing order and render it correctly.

# Tasks:

- [x] Refactor names so they are not only valid for order creation.
- [x] Refactor form to receive an existing order.
- [x] Check that no price is re-calculated when the form is opened.
- [x] Updates notices so they are not only valid for order creation.
