### ISSUE TITLE
[Unified Order Editing] Present Order Edit Form from Order Details Form

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#6962]
# Tasks:

- [x] Launch the newly refactor Order Edit form from the "Edit" icon.
- [x] Change the screen title to "Order #{order_number}"
- [x] Add a "Done" dismiss the order edit form.

**Comment by Ecarrion** [comment]
@ealeksandrov  I think we can close this, right?

**Comment by ealeksandrov** [comment]
Yes, it's done.
