### ISSUE TITLE
[Unified Order Editing] Handle multiple shipping lines edit

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#6980]
# Description

Our current `Order Creation` form only supports one custom shipping line.

Ref: pe5pgL-4W-p2

# Task

- [x] Allow edition of only the first shipping line
- [x] Allow deletion of only the first shipping line
- [x] Make sure all shipping lines are calculated in the totals.
