### ISSUE TITLE
[Unified Order Editing] Handle multiple fee lines edit

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#6982]
# Description

Our current `Order Creation` form only supports one fee line.

Ref: pe5pgL-4W-p2

# Tasks

- [x] Allow edition of only the first fee line
- [x] Allow deletion of only the first fee line
- [x] Make sure all fee lines are calculated in the totals
