### ISSUE TITLE
Localization and screenshots tooling upgrade: Next steps

### ISSUE THREAD

**Issue by mokagio** [woocommerce/woocommerce-ios#6987]
This issue pulls together the threads from three PRs I opened recently, because I can benefit from having them all on one place and to avoid missing anything. 

The PRs are:

- https://github.com/woocommerce/woocommerce-ios/pull/6936
- https://github.com/woocommerce/woocommerce-ios/pull/6937
- https://github.com/woocommerce/woocommerce-ios/pull/6939

## Next Steps

- [x] @mokagio to revert the `download_app_store_translations` deletion from #6939, because it turns out is not unused as I initially thought
- [x] @mokagio to close #6937 for the moment, because it's too simplistic and more work on that area of the code will be required later
- [x] @mokagio to address [this comment](https://github.com/woocommerce/woocommerce-ios/pull/6936#discussion_r881785597) from #6936 to put it in a ready to merge state – [Done](https://github.com/woocommerce/woocommerce-ios/pull/6936#issuecomment-1143287143)
- [ ] Once #6936 is merged: @mokagio / @rachelmcr to coordinate on the screenshots localization tooling updates (see https://github.com/woocommerce/woocommerce-ios/pull/6936#discussion_r881870941)
- [x] _Unrelated, but still worth tracking here_: @mokagio to remove all the remaining localization scripts that merging #6936 made unused – WIP https://github.com/woocommerce/woocommerce-ios/pull/7032

---

I opted for an issue over a GitHub project because the latter seemed like too much overhead for the handful of steps we have here.

**Comment by mokagio** [comment]
All steps here have been addressed. See also https://github.com/woocommerce/woocommerce-ios/pull/16531
