### ISSUE TITLE
Support background image uploads

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#7021]
Ref: p91TBi-8Gx-p2

### Subtasks
- [x] Add `ProductImageUploader` as a global dependency under a feature flag, where the implementation for the disabled state remains the same as the preexisting implementation. `ProductImageUploader` continues uploading images after leaving the product form without saving images to the product https://github.com/woocommerce/woocommerce-ios/pull/7022
- [x] Add `ProductAction.updateProductImages` to Yosemite for attaching uploaded images to the product https://github.com/woocommerce/woocommerce-ios/pull/7033
- [x] Behind the feature flag, update the "save" behavior in product form. If the user taps "save" after uploading some images, it saves the product right away and the images uploaded before the "save" will be added to the product's images with `ProductAction.updateProductImages` after none is pending upload. We probably want to save a snapshot of image statuses at the "save" action, since any changes on the images (new uploads or reordering of images) shouldn't be saved https://github.com/woocommerce/woocommerce-ios/pull/7048
- [x] Update a new product's remote product ID when it is ready https://github.com/woocommerce/woocommerce-ios/pull/7126 @selanthiraiyan 
- [x] Update uploaded image's product ID once remote product ID is available. 
  - [x] For a new product that just gets a remote product ID, update `parent_id` of previously uploaded images - https://github.com/woocommerce/woocommerce-ios/pull/7152 @selanthiraiyan 
  - [x] Use [different API](https://developer.wordpress.org/rest-api/reference/media/#update-a-media-item) for updating product ID of images in JCP site. https://github.com/woocommerce/woocommerce-ios/pull/7167 @selanthiraiyan 
- [x] Show a Notice when an image upload fails, with an action to view product details @jaclync https://github.com/woocommerce/woocommerce-ios/pull/7145
- [x] Show a Notice when [the product update request](https://github.com/woocommerce/woocommerce-ios/blob/fc47c8e0cd35dbb8bc06b7b44907c5d2915e2fdf/WooCommerce/Classes/ViewRelated/Products/Media/ProductImagesSaver.swift#L61) fails @jaclync https://github.com/woocommerce/woocommerce-ios/pull/7154
- [x] Look into why an error alert is shown when visiting product images view every time after image upload failure @jaclync https://github.com/woocommerce/woocommerce-ios/pull/7174
- [x] Cancel all image uploads when the user logs out @jaclync https://github.com/woocommerce/woocommerce-ios/pull/7161 
- [x] Support product variation image update in the background - right now the "Save" CTA is still visible after tapping it @jaclync 
  - [x] Update product ID in the interface to support variations https://github.com/woocommerce/woocommerce-ios/pull/7179
  - [x] Yosemite and Networking changes for the variation image update endpoint https://github.com/woocommerce/woocommerce-ios/pull/7180
  - [x] Upload and save the variation image in the background https://github.com/woocommerce/woocommerce-ios/pull/7195
- [x] Analytics p91TBi-8Gx-p2#comment-10778 https://github.com/woocommerce/woocommerce-ios/pull/7196
- [x] Fix an issue where the "Save" CTA remains visible after saving a downloadable product's downloadable files after image upload https://github.com/woocommerce/woocommerce-ios/pull/7254

#### Product types
- [x] Test product
- [x] Test product variation
- [x] Test downloadable product > Downloadable files upload

### Next phase
- [ ] Add persistence support to resume image upload on app launch
