### ISSUE TITLE
[Unified Order Editing] Add non-editable indicators

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#7101]
# Desciption

In order to properly indicate to the merchants what fields are not editable within an order, we will add a lock icon next to the un-editable section.

![Image](https://user-images.githubusercontent.com/562080/174105309-6dfb7db9-c9c0-445d-99eb-204ab97c1285.png)

ref: p91TBi-99O-pw

# Task

- [ ] Add the lock icon to the products section when the order is not editable
- [ ] Add the lock icon to the payment section when the order is not editable.
- [ ] Make sure the loading icon has precedence over the lock icon.
