### ISSUE TITLE
[Unified Order Editing] Inform about multiple fee & shipping Lines

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#7181]
# Description

We need to inform the merchant that the current order editing experience doesn't support multiple shipping or fee lines.

Ref: 

# Task

- [x]  When the order contains multiple shipping lines, show a notification row with the following message

> Shipping details are incomplete.
> To edit all shipping details, browse the order in your WooCommerce store admin.

- [x] When the order contains multiple fee lines, show a notification row with the following message

> Fees are incomplete.
> To edit all fees, browse the order in your WooCommerce store admin.

- [x] When the order contains multiple fee & shipping lines, show a notification row with the following message

> Fees & Shipping details are incomplete.
> To edit all the details, browse the order in your WooCommerce store admin.

Fees | Shipping | Both
--- | --- | ---
![Image](https://user-images.githubusercontent.com/562080/176787945-3e7c791b-53f0-4cf1-9f2b-8bbbd7f39267.png) | ![Image](https://user-images.githubusercontent.com/562080/176787944-9172cac6-8525-466d-b64b-32cf4ca91937.png) | ![Image](https://user-images.githubusercontent.com/562080/176787946-e7f2869a-356d-447e-8b03-4443544e6206.png)

**Comment by Ecarrion** [comment]
Update: Improved copy
