### ISSUE TITLE
Login Enhancement: Support installing Jetpack from Login

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#7269]
One of the Login Experiments idea is to Prompt users to install Jetpack. Essentially, we want to add an option to install Jetpack from the Jetpack error screen when a user is trying to log in to a store that doesn't have Jetpack.

To-do:
- [x] Add web view to handle Jetpack setup #7294
- [x] Add redirect deeplink to handle the setup success #7294
- [x] If Jetpack setup succeeds, resync sites and show site picker #7294
- [x] Add analytics #7319 
- [ ] Optimize the wp.com login flow on the web by sending access token there

**Comment by itsmeichigo** [comment]
Closing this issue in favor of #7370 for future improvements.
