### ISSUE TITLE
[Order Meta Data] Handle complex order metadata

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#7279]
We need to handle different kinds of values in order metadata (as defined in 213-gh-woocommerce/woomobile-private):

- [x] Discard empty values.
- [x] Discard JSON values. (Already discarded because we only accept string values for `OrderMetaData`)
- [x] Strip HTML from strings.
- [x] Detect when the value is a URL and make it tappable, opening the URL in an internal browser.
