### ISSUE TITLE
[Bulk Order Actions] Perform Mark To Complete action

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#7341]
# Description

When the user triggers the "Mark as Completed" action we need to perform that action remotely

# Task

- [x] Fire the mark as completed request when the users triggers the  "Mark as Completed" action.
- [x] Optimistically update the order to the complete status
- [x] Revert to the initial status in case of any error
