### ISSUE TITLE
Login Jetpack Install: Improve authentication experience

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#7370]
# Description
There are a few issues with the current Jetpack Install flow:
- It doesn't work after site credentials login (internal reference: pe5sF9-is-p2 - Iteration 2 section)
- Possible duplicated request to log in with site credentials/WP.com account between the web view and the app.

# Expectations
- [x] Jetpack Install should work properly when logging in with site credentials. #7373
- [x] User should only have to enter WP.com account credentials once. #7395 
- [x] User should only have to enter site credentials only once. #7787 
- [x] Update CTA title from "Install Jetpack" to "Set up Jetpack". #7787 
- [ ] Show native login flow if WP.com authentication is needed in the web view
