### ISSUE TITLE
Flaky test on CI ❄️ 

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#7425]
The following tests have failed on CI once in a while:

- [ ] WooCommerceTests.AsyncDictionaryTests: also reported back in 2019 in https://github.com/woocommerce/woocommerce-ios/issues/1687 ([CI output](https://buildkite.com/automattic/woocommerce-ios/builds/7081#01826c98-679e-4950-9384-5084a2b04e48))
```
▸   testAsyncUpdatesWhereTheFirstOperationFinishesLast, Asynchronous wait failed: Exceeded timeout of 1 seconds, with unfulfilled expectations: "Wait for completion callback for the first operation".
```
- [ ] WooCommerceTests.RemoteOrderSynchronizerTests ([CI output](https://buildkite.com/automattic/woocommerce-ios/builds/8073#01837f10-b065-46c6-bb26-e110a4c1ea1c))
```
▸   test_double_inputs_are_debounced_during_order_update, Asynchronous wait failed: Exceeded timeout of 1 seconds, with unfulfilled expectations: "test_double_inputs_are_debounced_during_order_update()".
```
- [ ] A few cases in CollectOrderPaymentUseCaseTests: test_collectPayment_processing_completion_does_not_track_collectInteracPaymentSuccess_event_when_payment_method_is_not_interac, test_collectPayment_processing_completion_tracks_collectInteracPaymentSuccess_event_when_payment_method_is_interac, test_collectPayment_with_interac_dispatches_markOrderAsPaidLocally_after_successful_client_side_capture, test_collectPayment_with_noninterac_does_not_dispatch_markOrderAsPaidLocally_after_successful_client_side_capture ([CI output](https://buildkite.com/automattic/woocommerce-ios/builds/8067#01837dc8-2b18-4e22-9dd0-af748f0698a4))
```
✗ test_collectPayment_with_interac_dispatches_markOrderAsPaidLocally_after_successful_client_side_capture, failed - Timed out waiting for done callback to be called.
```

- [ ] InAppPurchaseStoreTests.test_user_is_entitled_to_product_returns_false_when_not_entitled

▸   test_user_is_entitled_to_product_returns_false_when_not_entitled, XCTAssertFalse failed
▸   /usr/local/var/buildkite-agent/builds/MV-MKE-X64-010/automattic/woocommerce-ios/WooCommerce/WooCommerceTests/Yosemite/InAppPurchaseStoreTests.swift:191
▸   ```
▸         let isEntitled = try XCTUnwrap(result.get())
▸         XCTAssertFalse(isEntitled)
▸     }
▸   ```

- [ ] A couple cases in LoginJetpackSetupViewModelTests: test_shouldShowInitialLoadingIndicator_is_correct, test_shouldShowSetupSteps_is_correct ([CI output](https://buildkite.com/automattic/woocommerce-ios/builds/9870#018510ca-71b0-4cd6-a6e5-49a94581dc8c))
```
✗ test_shouldShowInitialLoadingIndicator_is_correct, failed - Timed out waiting for condition to return `true`.
✗ test_shouldShowSetupSteps_is_correct, failed - Timed out waiting for condition to return `true`.
```

**Comment by jaclync** [comment]
Closing this as the flaky tests in the description are outdated.
