### ISSUE TITLE
Handle Order Details Universal Link

### ISSUE THREAD

**Issue by toupper** [woocommerce/woocommerce-ios#7537]
## Description
With this task we want to handle order details universal links and navigate the user to the details of the order specified by the parameters in the link URL.
The path schema, pending [confirmation](pe5pgL-qo-p2#comment-638), would be `/orders/details?blog_id=<blog id number>&order_id=<order id number>` e.g /orders/details?blog_id=1&order_id=17 would navigate to the orders tab and then open the details for the `order_id` 17, of site with `blog_id` 1
The main challenge, therefore, is to change the site of the app if the passed blog id is not the same as the current app site id.

## Tasks

- [x] Add `Route` for order details
- [x] Read the path to extract site and order id
- [x] Change site if the given blog id does not match the current app site
- [x] Navigate to the orders tab and open details of the order with the associated order id
