### ISSUE TITLE
Handle In-Person Payments Universal Link

### ISSUE THREAD

**Issue by toupper** [woocommerce/woocommerce-ios#7538]
## Description
With this task we want to handle payments universal links and navigate the user to the Payments screen.
The path is `/payments`. We should then navigate the user to the Menu tab and open the Payments Menu screen. (pending confirmation [here](https://wooengage.wordpress.com/2022/08/19/link-mobile-ipp-menu-from-order-email/))

## Tasks

- [ ] Add `Route` for payments
- [ ] Read the universal link path to ascertain that matches the payments path
- [ ] Navigate to the Menu tab and then open the Payments menu screen
