### ISSUE TITLE
[Widgets] Fetch and Share data store info

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#7564]
# Description

When requesting fresh data for the widget, we need to make sure we store such data in a way it is accessible to the widget.

# Tasks

- [x] Set keychain sharing https://github.com/woocommerce/woocommerce-ios/pull/7681
- [x] Set Access Group Sharing https://github.com/woocommerce/woocommerce-ios/pull/7682
- [x] Request Widget Data From Network https://github.com/woocommerce/woocommerce-ios/pull/7690
- [x] Make sure data is requested with the correct timezone and parameters https://github.com/woocommerce/woocommerce-ios/pull/7707
