### ISSUE TITLE
Product Details: Support product details

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#764]
**Requires:**

- [x] new models (Product with all details) #747 
- [x] Storage (Product persistence) #805
- [x] Product Networking Layer ([docs](http://woocommerce.github.io/woocommerce-rest-api-docs/#products)) #747
- [x] Yosemite #821
