### ISSUE TITLE
[Just In Time Messages] Display JITMs at the top of the My Store screen

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#7853]
## Description
In order to promote In-Person Payments to relevant merchants, we intend to add JITM support in the mobile apps. Note that this can be used for any JITM, it's not limited to IPP-related messages.

In the first instance, we will support JITM support on the My Store screen, above the analytics charts.

We will match the UI from the Feature Announcement Card used in Upsell Card Readers #7229.

## Tasks
- [x] #7908
- [x] #7915
- [x] Additionally decode `CTA.link`, `id`, `ttl`, and `feature_class`, as they will be needed in future issues.
- [x] #7916
- [x] Track `*_jitm_displayed` event with props `jitm_group: {FEATURE_CLASS}`, `jitm_id: {JITM_ID}`, `source: my_store`
- [x] Track `*_jitm_fetch_success` event with props `source: my_store`, `jitm: {FIRST_RECEIVED_JITM_ID}`, `count: {NUMBER_OF_JITMs_IN_RESPONSE}`
- [x] Track `*_jitm_fetch_failure` event with props `source: my_store` and standard `error` props

## Further Reading
- pdfdoF-1uc-p2 
- pdfdoF-1vt-p2
