### ISSUE TITLE
[Just In Time Messages] Dismiss JITM when x tapped

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#7854]
## Description
JITMs can be dismissed, and dismissal will result in them not being sent again by the server until 
- their next display interval is reached
- up to a maximum of n dismissals (usually 2).

To achieve that, we must make a request to the server to report that the user has dismissed the message.

## Tasks
- [x] Dismiss UI for JITM when x is tapped
- [x] Make a POST request to `path=jetpack/v4/jitm` with the JITM's ID to mark it dismissed.
- [x] Track `*_jitm_dismissed` event with props `jitm_group: {FEATURE_CLASS}`, `jitm_id: {JITM_ID}`, `source: my_store`
- [x] Track `*_jitm_dismiss_success` event with props `jitm_group: {FEATURE_CLASS}`, `jitm_id: {JITM_ID}`, `source: my_store`
- [x] Track `*_jitm_dismiss_failure` event with props `jitm_group: {FEATURE_CLASS}`, `jitm_id: {JITM_ID}`, `source: my_store` and standard error props

## Further Reading
- pdfdoF-1uc-p2 
- pdfdoF-1vt-p2
