### ISSUE TITLE
Store creation M1

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#7879]
PT: pe5sF9-I3-p2
Release plan: pe5sF9-Jv-p2

## Subtasks (tentatively)

- [x] Entry point: site picker behind a feature flag https://github.com/woocommerce/woocommerce-ios/pull/7886
- [x] Account creation: https://github.com/woocommerce/woocommerce-ios/issues/7891
- [x] Entry point: after account creation from the prologue https://github.com/woocommerce/woocommerce-ios/pull/7927
- [x] Entry point: login CTA on the account creation - this requires significant changes to the WPAuthenticator to pass a source tag https://github.com/woocommerce/woocommerce-ios/pull/7964
- [ ] Issues: pe5sF9-JD-p2#comment-1124 - hopefully fixed by web customizations https://github.com/woocommerce/team-ghidorah/issues/109
  - [ ] Fix mobile web scaling issue in the domain selection
  - [ ] Look into the flow getting stuck half of the time 
- [ ] Design polishes:
  - [x] Show discard changes alert when dismissing the modal manually ([follow copy in Android](https://github.com/woocommerce/woocommerce-android/pull/7715)) https://github.com/woocommerce/woocommerce-ios/pull/8009#discussion_r1011339791
  - [ ] Check the password error is localized https://github.com/woocommerce/woocommerce-ios/pull/7897#discussion_r1002837606: after checking GlotPress, the string is in the translation database but hasn't been translated into different languages. In Calypso, it's actually showing a different localized error message and doesn't use the message from the API. We can hard code the mapping from the insecure password for now to match Calypso:
`This password is too easy to guess: you can improve it by adding additional uppercase letters, lowercase letters, or numbers`
- [x] Analytics pe5sF9-Jv-p2#comment-1071 https://github.com/woocommerce/woocommerce-ios/pull/7985

## Tech debt

- [x] Unit tests for `StoreCreationCoordinator` https://github.com/woocommerce/woocommerce-ios/pull/8026

**Comment by jaclync** [comment]
Closing, store creation feature was removed.
