### ISSUE TITLE
Products Onboarding: Template endpoint integration

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#7920]
# Tasks

- [x] Call `Yosemite` action when the merchant chooses to create a template product
- [x] Show some sort of loading screen while the product is being created
- [x] Navigate to created product
