### ISSUE TITLE
Store creation M2: domain selection

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#8045]
Project thread: pe5sF9-I3-p2
Design: HyVloP5FipZzyPVenH2euI-fi-2116%3A106887

### Subtasks
- [x] Domain suggestions data source: https://github.com/woocommerce/woocommerce-ios/pull/8060
  - Networking layer
  - Yosemite layer
- [x] Implement a new screen to select a domain with `wordpress.com` subdomains only (free) first (paid domains will be in a separate milestone) https://github.com/woocommerce/woocommerce-ios/pull/8065
<img width="462" alt="Screen Shot 2022-11-07 at 3 26 03 PM" src="https://user-images.githubusercontent.com/1945542/200250521-6acf5df5-c87f-4e65-bfb9-4ad920729642.png">

- [x] Handle error - show the error message (design TBD) https://github.com/woocommerce/woocommerce-ios/pull/8092
- [x] Update empty state - design TBD https://github.com/woocommerce/woocommerce-ios/pull/8092
- [x] Update loading state - design TBD https://github.com/woocommerce/woocommerce-ios/pull/8092
- [x] Improve landscape layout https://github.com/woocommerce/woocommerce-ios/pull/8092
- [x] Update placeholder image - dark mode, transparent background https://github.com/woocommerce/woocommerce-ios/pull/8165
- [x] Update layout based on the [latest design feedback](https://github.com/woocommerce/woocommerce-ios/pull/8092#issuecomment-1311169943) https://github.com/woocommerce/woocommerce-ios/pull/8165
  - [x] Auto-focus the text field
  - [x] Auto-dismiss the keyboard after selecting a domain and the continue button appears ([ref](https://github.com/woocommerce/woocommerce-ios/pull/8092#pullrequestreview-1176782138))
  - [x] Update spacing between elements
  - [x] Update SUGGESTIONS header text to footnote font
  - [x] Update search field trailing padding, and decrease space around the search icon ([ref](https://github.com/woocommerce/woocommerce-ios/pull/8092#pullrequestreview-1176782138))
  - [x] Remove the skip button pecCkj-dp-p2
  - [x] Update no search results error pecCkj-dp-p2
  - [x] Update bottom Continue CTA to use `safeAreaInset`
- [x] Minor polish: no debounce for the initial query https://github.com/woocommerce/woocommerce-ios/pull/8271

#### Entry points

- [x] Entry point: native store creation https://github.com/woocommerce/woocommerce-ios/pull/8065
  - Add a feature flag `storeCreationM2`
  - Show the domain screen for store creation behind the feature flag, since this is the first screen of the flow

~~- [ ] (Deferred to M4 pecCkj-dp-p2): Entry point: settings > domain~~
<img width="470" alt="Screen Shot 2022-11-07 at 3 26 14 PM" src="https://user-images.githubusercontent.com/1945542/200250540-c2c8a389-eacb-46df-a319-1a12df051232.png">
