### ISSUE TITLE
Login: Native experience for the Jetpack installation flow

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#8075]
**Description**
Currently the Jetpack installation flow is implemented with a web view, which is flaky and not user-friendly.
Handling all the setup steps natively will make the experience smoother and improve the success rates.

Design: ERGtCFLyiC9CFpHsw1XIid-fi-1110%3A37319
To-do:

- [x] Networking: Update `JetpackConnectionRemote` with endpoints for plugin management. #8076 
- [x] Yosemite: Update `JetpackConnectionStore` and `JetpackConnectionAction` for plugin management. #8095 
- [x] UI: Add a new screen for the Jetpack error screen that is reusable for installation and connection. #8127 
- [x] UI: Add a new screen for site credential login from within the app. #8142
- [x] UI: Add a new screen for Jetpack setup OR update the existing screen. #8152
- [x] UI: Add view model to handle Jetpack setup steps. #8168 
- [x] UI: Error states for Jetpack setup. #8186 
- [x] Update tracks: 
  - [x] Update `*_site_picker_site_discovery` properties: replace `has_valid_jetpack` with `is_jetpack_installed`, `is_jetpack_active`, and `is_jetpack_connected`. - https://github.com/woocommerce/woocommerce-ios/pull/8187
  - [x] Add events for Jetpack error, site credentials and setup screens - https://github.com/woocommerce/woocommerce-ios/pull/8187
   - [x] Add events for different WPCOM account - https://github.com/woocommerce/woocommerce-ios/pull/8204
- [x] Apply A/B test: - https://github.com/woocommerce/woocommerce-ios/issues/8166
  - [x] Experiment proposal P2 - pbxNRc-29W-p2
  - [x] Code change - https://github.com/woocommerce/woocommerce-ios/pull/8170
  - [x] New Abacus experiment - 20913-explat-experiment
  
**Bugs identified**
https://github.com/woocommerce/woocommerce-ios/issues/8225
