### ISSUE TITLE
Store creation M2: store summary -> WPCOM plan

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#8108]
Project thread: pe5sF9-I3-p2
Design: HyVloP5FipZzyPVenH2euI-fi-2116%3A106887

After a site is created in the store summary screen, the user can tap the primary CTA to see the eCommerce plan and a CTA to purchase with IAP.

Testing guide: PdfdoF-1Ej-p2
Sandbox/proxy setup (Charles proxy is required): pb3aDo-OE-p2

### Subtasks

- [x] WPCOM plan screen with product from IAP https://github.com/woocommerce/woocommerce-ios/pull/8120
~~- [ ] Integrate with IAP purchase and show the success/failure alerts~~ update: we're going with web checkout for M2
- [x] New checkout flow:
  - [x] Networking layer changes https://github.com/woocommerce/woocommerce-ios/pull/8203
  - [x] Yosemite layer changes https://github.com/woocommerce/woocommerce-ios/pull/8205
  - [x] Checkout flow https://github.com/woocommerce/woocommerce-ios/pull/8216
- [x] Show loading UI while fetching IAP status p1668653541795519/1668565030.897709-slack-C045CUK1Y3U
~~- [ ] Polish IAP error UI (right now it's an alert)~~ update: there's no error with the updated checkout implementation
- [x] Release: update expected product identifier
- [x] Design polishes: https://github.com/woocommerce/woocommerce-ios/pull/8271
  - Update icons (export ones that aren't in the app)
  - Accommodate long price text
  - Update refund info to be footnote style

<img width="568" alt="Screen Shot 2022-11-14 at 1 37 25 PM" src="https://user-images.githubusercontent.com/1945542/201583569-79ffcd75-6e9a-46c9-8e32-27e30023d0f6.png">
