### ISSUE TITLE
Store creation M2: installations (loading & success screens)

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#8118]
Project thread: pe5sF9-I3-p2
Design: HyVloP5FipZzyPVenH2euI-fi-2369%3A101577&t=Y9fAyMRWXAyQSWDn-0

### Subtasks

- [x] In-progress screen while waiting for the site to become a Jetpack & Woo site https://github.com/woocommerce/woocommerce-ios/pull/8154
- [x] Success screen with a webview of their new site https://github.com/woocommerce/woocommerce-ios/pull/8141
- [x] CTA: preview the new site in a webview https://github.com/woocommerce/woocommerce-ios/pull/8141
- [x] CTA: continue to the new site https://github.com/woocommerce/woocommerce-ios/pull/8154
- [ ] Issue: store preview image is sometimes not available ([example screenshot](https://user-images.githubusercontent.com/5533851/204194850-f771a4f8-d057-4456-9ea6-25e010d130fd.png))

<img width="792" alt="Screen Shot 2022-11-15 at 9 18 13 AM" src="https://user-images.githubusercontent.com/1945542/201803071-696872b1-7016-46bf-a19e-9d4a6b87b3a4.png">

**Comment by jaclync** [comment]
> Issue: store preview image is sometimes not available ([example screenshot](https://user-images.githubusercontent.com/5533851/204194850-f771a4f8-d057-4456-9ea6-25e010d130fd.png))

This is because the URL of the new site from the WPCOM `/me/sites` response has is using `http` instead of `https`. Asked the Jetpack team in p1669881159192899/1667224844.942809-slack-CDLH4C1UZ. Closing the issue now, we could consider adding a spinner before the webview content is loaded, but I think we should fix the root cause instead. Otherwise, the user is still seeing an infinite spinner.
