### ISSUE TITLE
[Analytics Hub] Create Date range picker view with selection support

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-ios#8146]
Depends on #8144 

## Summary
Besides the date selection coming from the `See more` button entry point, the date range section should also be clickable and display a selector to change the current date range of the stats.

The following options should be presented:

- Today
- Yesterday
- Last Week
- Last Month
- Last Quarter
- Last Year
- Week to Date
- Month to Date
- Quarter to Date
- Year to Date

### Tasks
- [x] Introduce Date picker UI component
- [x] Adjust Time Range structure to support additional ranges
- [x] Introduce Yesterday range
- [x] Introduce Last Week, Last Month and Last Year ranges
- [x] Introduce Last Quarter and Quarter to Date ranges

## Behavior
Each of the options should not only acquire the selected date range, but the respective previous period. Here's how each new option should be presented:

Given that Today is `2022-11-17` or `Nov 17, 2022`

- When Yesterday is the selected range, the previous period should be the day before Yesterday. 
`Yesterday Nov 16, 2022 compared to Nov 15, 2022`

- When Last Week is the selected range, the previous period should be the week before the Last Week.
`Last Week Nov 6 - 12, 2022 compared to Oct 30 - Nov 5, 2022`

- When Last Month is the selected range, the previous period should be the month before the Last Month. 
`Last Month Oct 1 - Oct 31, 2022 compared to Sep 1 - Sep 30, 2022`

- When Last Quarter is the selected range, the previous period should be the quarter before the Last Quarter.
`Last Quarter Jul 1 - Sep 30, 2022 compared to Apr 1 - Jun 30, 2022`

- When Last Year is the selected range, the previous period should be the year before Last Year.
`Last Year Jan 1 - Dec 31, 2021 compared to Jan 1 - Dec 31, 2020` 

- When Quarter to date is the selected range, the previous period should be Last Quarter in the same period.
`Quarter to date Oct 1 - Nov 17, 2022 compared to Jul 1 - Aug 17, 2022`

Today, Week to date, Month to date, and Year to date ranges should be already available from #8144 implementation.

Example capture from the WCAndroid behavior:

https://user-images.githubusercontent.com/5920403/202525782-266cdd2a-3465-42a8-a6bf-71050e43c8c3.mp4

## Designs

⚠ Note that the `Custom` option should not be included in this task.

![Image](https://user-images.githubusercontent.com/5920403/202528934-83431542-b9c4-4a5d-b9f5-d45e3f2b5339.png)
