### ISSUE TITLE
[Analytics Hub] Create reusable Analytics stats main body with info card component

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-ios#8148]
## Summary
The main stats we're looking to introduce inside the Analytics Hub are the Orders and Revenue. They should be displayed in a scrollable view with the Order first and the Revenue right below. Both share the same UI, so we should aim to create a UI element that can be reused for both stats types.

## Behavior

The stats view content:

### Left and Right subsections, each subsection containing:
- Subtitle
- Main value
- Delta percentage badge

![Image](https://user-images.githubusercontent.com/5920403/202557144-799ea7f5-3bf9-445f-b25a-ad5f86418cbe.png)

We should exclude the `See more` button and charts information for now.

## Designs

| Original designs  | What we want |
| ------------- | ------------- |
| ![Image](https://user-images.githubusercontent.com/5920403/202532880-17914685-ba29-42c6-ac3a-ecf7751d75eb.png) | ![Image](https://user-images.githubusercontent.com/5920403/202532942-7438b905-760c-432e-91b6-1efb450cd7ed.jpg) |

**Comment by Ecarrion** [comment]
# Tasks

- [x] Adds main hub view
- [x] Adds main view model
- [x] Create stats cards
- [x] Integrate cards + view + view model
- [ ] Handle Accessibility
