### ISSUE TITLE
[Analytics Hub] Configure Products Analytics card

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-ios#8198]
## Summary
The Product analytics card should be able to display the `Total items sold` for that period. Which be properly acquired directly from the Woo Core stats API.

We will integrate real data from the API in another issue. Until then, we can use fake data for the previous and current periods and generate a percentage delta value based on the Total Items sold difference between the two periods.

## Designs
![Image](https://user-images.githubusercontent.com/5920403/203627338-77920429-b31e-4bf3-ad57-9cd2bfc6aca5.png)

**Comment by Ecarrion** [comment]
## Tasks

- [x] Build Card UI 
- [x] Fetch and get data ready
- [x] Integrate Data & UI
