### ISSUE TITLE
[Analytics Hub] Add custom date range selection support

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-ios#8200]
Depends on #8146

## Summary
Besides the defined ranges available inside the Hub, we should also allow the user to select a custom date range to properly check stats from any given selection. The range selector must allow selection that spans multiple weeks and months, but the end date must be limited to the current date since it doesn't make sense to have a date range selecting the future.

## Designs
We should look for an iOS date picker component that allows us to select a start and end date. This is how the custom selection works on the Android side (we don't need to perfectly replicate how it works on Android, but follow the iOS expected pattern instead):

https://user-images.githubusercontent.com/5920403/203633950-f9d19acc-ff9f-4ed4-abe8-b1f21b20f390.mp4

**Comment by Ecarrion** [comment]
# Tasks

- [x] Define new UX alternative
- [x] Build UI
- [x] Add Internal custom Range support
- [x] Present UI after selecting custom range option
- [ ] Format range subtitle in range selection
