### ISSUE TITLE
[Native Jetpack Installation] Conclude A/B testing experiment

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#8514]
### Description
Based on the results from the A/B testing experiment and the funnels created, we measured that the native Jetpack installation flow performs better when compared to the webview flow. 

So, we decided to deploy the native Jetpack installation flow for all users.

### Links
Explat - 20925-explat-experiment
Funnels - p1672644856954759/1672641535.374929-slack-C046HDZL87J

### Tasks

- [x] Disable the experiment
- [x] Remove the experiment code and deploy treatment (Native installation flow) for all users https://github.com/woocommerce/woocommerce-ios/pull/8533
- [x] Add a conclusion to the P2 and experiment model in Abacus pbxNRc-29W-p2#comment-3995
