### ISSUE TITLE
Order Fulfillment: Detect Shipment Tracking Plugin

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#852]
As a user, I want to add Shipment Tracking to an order that is ready to be fulfilled.

- [ ] Create a mechanism for detecting extensions.
- [ ] Add a method that checks for the Shipment Tracking extension.
- [ ] If Shipment Tracking is available, display the "Add Tracking" row in the Fulfillment ViewController.

**Comment by bummytime** [comment]
Currently on the fulfillment screen, the `Add tracking` button displays even if the tracking plugin is not installed/active:

![tracking_check](https://user-images.githubusercontent.com/154014/55991344-a91ebd00-5c6f-11e9-8067-425e75bd43f5.gif)

Let's hide/display this button by doing the simplest check possible (for now) — on `FulfillViewController` we always sync tracking information in `viewWillAppear`. If the plugin is not installed/active we receive a 404 error and the following error displays in the console:

```
⛔️ Error synchronizing tracking: The operation couldn’t be completed. (Networking.DotcomError error 5.)
```

So how we inspect if `error != nil` in the completion block for `syncTracking()`. If we have an error, just hide the button, otherwise show it.

/cc @ctarda
