### ISSUE TITLE
Settings: domain update

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#8558]
Spike: pe5sF9-Ug-p2
Design: VyLr7LvKodHE4kINfBE7Lw-fi-682%3A40227&t=S2CYnbufFyxeCeMk-0

<img width="1354" alt="Screen Shot 2023-01-06 at 10 39 07 AM" src="https://user-images.githubusercontent.com/1945542/210918758-a0d9369a-f6a5-4188-a58a-175576b3250b.png">

---

## Subtasks

- [x] Create a feature flag `domainSettings` https://github.com/woocommerce/woocommerce-ios/pull/8581
- [x] In settings, add a CTA that navigates to the main UI if: https://github.com/woocommerce/woocommerce-ios/pull/8581
  - The feature flag is enabled
  - The site is a wpcom site
- [x] Hide the `*.wordpress.com` domain in the list https://github.com/woocommerce/woocommerce-ios/pull/8848
- [x] Update the free staging domain to match Calypso https://github.com/woocommerce/woocommerce-ios/pull/8848

### Analytics

- [x] Analytics plan pe5sF9-15a-p2#comment-1694 https://github.com/woocommerce/woocommerce-ios/pull/8870

### Eligibility check

- [x] Only enable domain settings for store admins https://github.com/woocommerce/woocommerce-ios/pull/8879

Non admins get this error from loading site domains: `⛔️ Error retrieving domains for siteID 215173688: Dotcom Error: [authorization_required] User or Token does not have access to specified site.`

#### UI

- [x] Show the free `*.wpcomstaging.com` URL at the top, and one of the following below: https://github.com/woocommerce/woocommerce-ios/pull/8581
  - If no other domains, there are two CTAs:
    - Show "Already own a domain?" link to open a webview to connect to an existing domain at `https://wordpress.com/start/domains/use-your-domain`
    - Otherwise, show a CTA to search for a domain that navigates to the next screen
  - [x] If there are existing domains, show the list of domains for the site with a CTA to add another one which navigates to the next screen https://github.com/woocommerce/woocommerce-ios/pull/8606
- [x] If the site includes a domain credit, show the domain credit UI with a CTA to search for a domain using domain credit in the next screen https://github.com/woocommerce/woocommerce-ios/pull/8711
- [x] Show the instructions text below the bottom CTA (URL: https://wordpress.com/go/tutorials/what-is-a-domain-name/ from [this thread](VyLr7LvKodHE4kINfBE7Lw-fi-682:40227)) https://github.com/woocommerce/woocommerce-ios/pull/8855
- [ ] Refactor the badge view to be reusable
- [ ] Test newly created sites to make sure the Domain settings are available ([ref](https://github.com/woocommerce/woocommerce-ios/pull/8663#pullrequestreview-1252837385))
- [x] [Minor] Placeholder state when loading domains https://github.com/woocommerce/woocommerce-ios/pull/8821

#### Yosemite/Networking

- Fetch info for the current state of domains: `https://public-api.wordpress.com/rest/v1.1/sites/{siteId}/domains/?locale=en_US`
- Fetch plans info, and check for `"current_plan": true` to determine the currently selected plan and then `"has_domain_credit": true`, to determine if the user has credit to claim a domain: `https://public-api.wordpress.com/rest/v1.3/{sideId}/plans/?locale=en_US`

- [x] Networking layer https://github.com/woocommerce/woocommerce-ios/pull/8600
- [x] Yosemite layer https://github.com/woocommerce/woocommerce-ios/pull/8601

#### UI

- [x] UI integration after Yosemite layer: the copy and content are different from the free domain selector in the store creation flow https://github.com/woocommerce/woocommerce-ios/pull/8663
- [x] Attributed price info https://github.com/woocommerce/woocommerce-ios/pull/8710
- [x] "Free for the first year" if the site has domain credit https://github.com/woocommerce/woocommerce-ios/pull/8778
- [x] Don't show support action in the navigation bar https://github.com/woocommerce/woocommerce-ios/pull/8819
- [x] Update header text https://github.com/woocommerce/woocommerce-ios/pull/8819
- [ ] Add unit tests for `PaidDomainSelectorDataProvider`
- [ ] Add unit tests for `DomainSettingsCoordinator`

#### Yosemite/Networking

Load all the products and match them later with the domain suggestions to apply the proper discount: `https://public-api.wordpress.com/rest/v1.1/products?http_envelope=1&type=domains`.

- [x] Networking layer https://github.com/woocommerce/woocommerce-ios/pull/8642
- [x] Yosemite layer https://github.com/woocommerce/woocommerce-ios/pull/8660

### Checkout screen

- [x] Yosemite & Networking layer changes https://github.com/woocommerce/woocommerce-ios/pull/8696
- [x] Navigate to web checkout when not using a domain credit https://github.com/woocommerce/woocommerce-ios/pull/8696

### Domain credit checkout flow

- [x] API request to redeem a domain with domain credit https://github.com/woocommerce/woocommerce-ios/pull/8771
- [x] Contact info form https://github.com/woocommerce/woocommerce-ios/pull/8784
- [x] API request to load & validate domain contact info https://github.com/woocommerce/woocommerce-ios/pull/8803
- [x] Pass contact info when redeeming a domain https://github.com/woocommerce/woocommerce-ios/pull/8784
- [x] Easier phone number form field to conform to the format of `+areacode.number` https://github.com/woocommerce/woocommerce-ios/pull/8859

❓ How about the error state? a banner?

### Success screen

- [x] Create a new screen with the domain name, and a CTA to go back to the domain dashboard screen https://github.com/woocommerce/woocommerce-ios/pull/8696
  - [x] Polish UI https://github.com/woocommerce/woocommerce-ios/pull/8785

### Settings screen

- [x] Update CTA to a different section VyLr7LvKodHE4kINfBE7Lw-fi-1144%3A64907 https://github.com/woocommerce/woocommerce-ios/pull/8860

<img width="234" alt="Screenshot 2023-02-03 at 10 05 37 AM" src="https://user-images.githubusercontent.com/1945542/216495075-11129e60-53b6-4e59-9a8d-cee53e95e953.png">

### Nice to haves

- [ ] Polish domain suggestions query parameters: for query `fun testing`, Calpyso uses `https://public-api.wordpress.com/rest/v1.1/domains/suggestions?http_envelope=1&query=funtesting&quantity=30&include_wordpressdotcom=false&include_dotblogsubdomain=false&tld_weight_overrides=&vendor=variation8_front&site_slug=funtestingusa.com&recommendation_context=fun,testing`

**Comment by JorgeMucientes** [comment]
Closing as part of the Woo Mobile GitHub stale-issue audit cleanup.

Rationale for closing:
- Listed in audit section "Potentially Stale / Good Candidates To Close Still Open, Outside Grouped Commerce Rows (40)". Last GitHub activity in the audit: 2023-04-27 1162d. Audit recommendation: Keep / Manual review. Audit rationale: Open in the 2026-07-02 live snapshot; last GitHub update 2023-04-27 (1162d ago). No direct current-code signal found; manual product triage recommended.. No longer in a protected grouped area in this report; close as stale backlog cleanup and reopen if still reproducible or product-owned.

Reopen if this is still reproducible, product-owned, or should be tracked in a current Linear issue.
