### ISSUE TITLE
[REST API] Media DotCOM requests need to be converted to REST API 

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#8566]
### Description
The requests from [`MediaRemote`](https://github.com/woocommerce/woocommerce-ios/blob/trunk/Networking/Networking/Remote/MediaRemote.swift) are all WPCOM requests, and those requests aren't using Jetpack tunnel.

I learnt from this internal discussion that `/media` requests cannot use Jetpack tunnel. p1672921523522859-slack-C046HDZL87J

### Next steps

- We need to investigate about how we can convert these WPCOM requests into REST API requests when authenticating using application passwords.
- Please note that [MediaStore](https://github.com/woocommerce/woocommerce-ios/blob/trunk/Yosemite/Yosemite/Stores/MediaStore.swift) runs [this check](https://github.com/woocommerce/woocommerce-ios/blob/trunk/Yosemite/Yosemite/Stores/MediaStore.swift#L73) to choose between `rest/v1.1/` and `wp/v2/` for JCP and non-JCP sites respectively. We should investigate the possibility of always using `wp/v2/`.

**Comment by selanthiraiyan** [comment]
### ~Task breakdown~
- [x] ~Add WordPressAPI version to `RESTRequest` https://github.com/woocommerce/woocommerce-ios/pull/8590~
- [ ] ~`MediaRemote` - Add REST request methods https://github.com/woocommerce/woocommerce-ios/pull/8594~
- [ ] ~Pass site ID or URL in `MediaAction` https://github.com/woocommerce/woocommerce-ios/pull/8603~

---

We decided to convert `DotcomRequest` into `RESTRequest` instead of sending `RESTRequest` directly from `MediaRemote`.  Discussed during this PR review - https://github.com/woocommerce/woocommerce-ios/pull/8594
### Task breakdown
- [x] Convert `DotcomRequest` into `RESTRequest` https://github.com/woocommerce/woocommerce-ios/pull/8682
- [x] Migrate endpoints from `MediaRemote` + `MediaStore` https://github.com/woocommerce/woocommerce-ios/pull/8686
