### ISSUE TITLE
Order Summary: Product Prices always exclude tax

### ISSUE THREAD

**Issue by joashrajin** [woocommerce/woocommerce-ios#8591]
**Describe the bug**

Some WC Stores have the prices displayed including tax using `Display prices in the shop` & `Display prices during cart and checkout` set to "Including Tax".

On those sites, the prices in the order summary and emails include the tax. On the app though, this does not reflect and always excludes tax. 

It would be nice if we could make it match. Maybe we could add an option in the app to make the prices show including taxes?

**To Reproduce**
1. Go to WooCommerce > Settings > Tax, then ensure that it is set similar to this: ![LtdTsV.png](https://user-images.githubusercontent.com/16253818/211299951-10c88ec2-4e51-4e62-992b-f1247675f19a.png)
2. Set up some standard tax rates
3. Order a test product, then compare the totals shown in the order email to the order summary in the app

**Screenshots**

App:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/16253818/211300330-855dee57-1a26-4ed1-9a92-a836c90dab44.png">

Email Confirmation: 

<img width="560" alt="image" src="https://user-images.githubusercontent.com/16253818/211300221-8018694c-07d5-47f0-a316-0e37acc39e03.png">

**Expected behavior**

The order details within the app should match what you see in the order confirmation email and the site itself. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 14 Pro Max
- iOS version: 16.2
- WooCommerce iOS version: 7.2.2

5832302-zd-woothemes

## Tasks

- [ ] Verify if this problem exists in Android too.

**Comment by jostnes** [comment]
This looks like a platform parity between core and the app. Pinging @shiki for awareness and prioritization, I think your team is working on Orders (please help ping the right people if I got it wrong 🙏)

**Comment by JorgeMucientes** [comment]
Closing this as part of a maintenance pass on the GitHub issue backlog. This issue matched the auto-close criteria for this pass: it has not been updated since 2023-04-20, is unassigned, is not labeled as a bug or high/medium priority, and does not appear to involve POS, payments, login, data loss, crash, security, vulnerability, auth, or fraud.

If this is still relevant, please comment with current details and we can reopen it or move it into Linear for triage.
