### ISSUE TITLE
Nuke product variation code + data model updates 🧨💥 

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-ios#869]
Check out all the code in #830, #841, #845. Awesome isn't it? Now remove it all!

![200](https://user-images.githubusercontent.com/154014/55913609-a4dc9c00-5baa-11e9-823d-0d43598aecba.gif)

Because we are going to fetch product variations from the `/products` endpoint, there is no need for this code right now or the foreseeable future. 

## Tasks
- [x] Remove `ProductVariation` Networking code + tests (ref: #841)
- [x] Remove `ProductVariation` Storage code (ref: #830)
- [x] Create a new data model that reverts the `ProductVariation` updates in model v13 — specifically the `ProductVariation`, `ProductVariationAttribute`, `ProductVariationDimensions`, and `ProductVariationImage` entities (ref: #830)
- [x] Remove `ProductVariation` Yosemite code + tests (ref: #845)

/cc @nbradbury @astralbodies 😢
