### ISSUE TITLE
[Support Requests] Add API-Providers Zendesk SDK support

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#8794]
# Tasks

- [x] Make sure to use the latest SDK that supports the API-Providers API
- [x] Create a VM for the new Support UI.
- [x] Create & Configure the request exactly as we are sending it right now.
