### ISSUE TITLE
[Support Requests] Refactor Zendesk Helpers to be used with the new Support UI

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#8795]
Currently, all of our Zendesk code is in a file called `ZendeskManager`. We need to look at it, and possibly refactor it:

# Task

- [x] Expose connection/authentication methods
- [x] Move non-zendesk code out of it.
- [ ] Make it easier for other teams at Automattic to copy the code over.

**Comment by Ecarrion** [comment]
Closing this as we don't plan to do any further improvements!
