### ISSUE TITLE
[Support Requests] Integrate New UI + API Providers

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#8796]
# Task

- [x] Integrate UI with new API - Provider Request
- [x] Show loading indicators
- [x] Show error notices.
- [x] Alert users that they will be contacted via email next
