### ISSUE TITLE
[Support Requests] Figure out how to send extra information provided my merchant

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#8797]
This task is still in the research phase but the idea is for merchants to select what kind of help they need.

# Tasks

- [x] Figure out(UI-wise) how the user will indicate what kind of help they need.
- [x] Figure out how are we going to send that selection to the Zendesk SDK.
- [x] Implement the above decisions.

## Meta data to send:

- Mobile App – Routes to mobile queues
   - Tags mobile_app
   - Form ID 360000010286

- Card Reader / In-Person Payments – Route to mobile queues
   - Tags woocommerce_mobile_apps, product_area_apps_in_person_payments
   - Form ID 360000010286

- WooCommerce Plugin – Routes to Woo Core queues
   - Tags woocommerce_core
   - Form ID 189946

-  WooCommerce Payments – Routes to WooCommerce Payments queue
   - Tags woocommerce_payments, product_area_woo_payment_gateway
   - Form ID 189946

- Other Extension / Plugin – Route to Woo Core queues for triaging
   - Tags product_area_woo_extensions
   - Form ID 189946
