### ISSUE TITLE
[Support Requests] Integrate Suggestions Ui with Network Request

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#8800]
# Tasks

- [ ] Integrate FAQ suggestions API with on the New Support UI
- [ ] Launch FAQ selection in a web view
- [ ] Log any error that may occur 
- [ ] Show loading indicator

**Comment by shiki** [comment]
Same for https://github.com/woocommerce/woocommerce-ios/issues/8799#issuecomment-1516930494. Closing for now.
