### ISSUE TITLE
[Support Requests] Remove Feature Flag

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#8801]
Once all iterations have been completed.

# Tasks

- [ ] Remove feature flag
- [ ] Announce to HEs
- [ ] Announce to beta testers - Build mini test plan

**Comment by shiki** [comment]
I think we have already removed the feature flag. 😅
