### ISSUE TITLE
Dashboard: one scroll view for all header views and stats tabbed view

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#8911]
## Why

We're adding an onboarding card to the dashboard, and the card can be taller than the previous announcement/feedback card especially with larger font sizes. The stats view (store stats & top performers) is currently in a tabbed view with one scroll view for each tab. Any views above the stats view are not scrollable right now. However, with the introduction of the onboarding card, it's time to update the dashboard UI hierarchy so that there's only one single scroll view for all the content in the vertical space.

Note: I've tried some workarounds, like adding a swipe gesture to the header stack view or putting the scrollable stats view inside a top-level scroll view. However, I encountered UX issues with these workarounds and we shouldn't have nested scroll views in any case.

## Subtasks

- [x] Refactor dashboard UI hierarchy to have only one scroll view https://github.com/woocommerce/woocommerce-ios/pull/9031
- [x] Fix top performers view height when data changes https://github.com/woocommerce/woocommerce-ios/pull/9121
- [x] Always show the onboarding view in landscape and all scroll states ([ref](https://github.com/woocommerce/woocommerce-ios/pull/9031#issuecomment-1463539011)) https://github.com/woocommerce/woocommerce-ios/pull/9121
- [x] Store name is truncated https://github.com/woocommerce/woocommerce-ios/pull/9031#issuecomment-1466182738 (related: https://github.com/woocommerce/woocommerce-ios/issues/8499)

**Comment by selanthiraiyan** [comment]
I am adding this here to keep track. 

https://github.com/woocommerce/woocommerce-ios/pull/8991#pullrequestreview-1318999656

> I found one minor issue when the IPP banner is displayed though - seems like the banner takes up a bit space of the onboarding view (notice the Store setup label being cut off a bit at the top):

<img src="https://user-images.githubusercontent.com/5533851/222041240-d346e368-5fa9-4600-bb1c-792aafbc27a5.png" width=320 />


I believe that this will be fixed when we address the overall scroll issue. Let me know if you think we should create a separate issue.
