### ISSUE TITLE
REST API: Benefit banner and modal

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#8912]
Reuse the Jetpack CP benefits banner and modal as an entry point to the Jetpack installation:

- [x] Display the banner when application passwords are used on dashboard and settings screens like Jetpack CP. #8924 
- [x] Update the modal's content depending on the site's type. #9112 
- [x] Add feature flag to enable Jetpack setup for user authenticated with site credentials #8924
