### ISSUE TITLE
REST API: Custom WPCom login flow for Jetpack setup

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#8918]
We need an in-house flow for the WPCom login step of the Jetpack setup feature:

- [x] New UI for email login #8993 
- [x] New UI for password login #9022 
- [x] New UI for magic link login #9021 
- [x] Check if account is passwordless #9001 
- [x] Request authentication link for magic link login #9009 
- [x] New UI for 2FA login #9029 
- [x] Integrate login with email/username password #9029 
- [x] Handle edge case for when email login is not allowed (username required) #9040

**Comment by itsmeichigo** [comment]
Closing as all subtasks have been completed
