### ISSUE TITLE
REST API: Update current Jetpack setup flow to use application password auth

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#8919]
- [x] Rename classes and views related to Jetpack install/setup #8933 
- [ ] ~Switch between `JetpackConnectionStore` and `SitePluginStore` based on authentication state.~
- [x] Integrate the Jetpack setup flow after login #9113
- [x] Pass the credentials from login to the Jetpack setup flow for authenticating the Jetpack URL page and authenticate after Jetpack setup succeeds. #9113
- [x] Update`AuthenticatedWebViewController` to accept WPCom credential as input and send it from the Jetpack setup view model. #9113
- [x] Add analytics #9341 
- [ ] Edge cases pe5sF9-1oh-p2 #9354 

Event | Properties | Triggers
-- | -- | --
jetpack_benfits_login_button_tapped |   | When the Log in button on the Jetpack benefit modal is tapped.
jetpack_setup_connection_check_completed | is_already_connected: true \| false;requires_connection_only: true \| false | When the check /wp-json/jetpack/v4/connection/data completes.
jetpack_setup_connection_check_failed | error details (domain, code) | When the check /wp-json/jetpack/v4/connection/data fails.
jetpack_setup_login_flow | tap: submit \| dismiss;step: email_address \| password \| magic_link \| verification_code;failure: error details (domain, code) | Events during the login flow during Jetpack setup
jetpack_setup_login_completed |   | When the login flow during Jetpack setup completes
jetpack_setup_flow | step: installation \| activation \| connection \| all_done;tap: dismiss \| support \| continue_setup \| go_to_store \| try_again;failure: error details (domain, code) | Events during the Jetpack setup flow (after wpcom login)
jetpack_setup_completed |   | When Jetpack setup completes
jetpack_setup_synchronization_completed |   | When synchronization completes after Jetpack setup.
