### ISSUE TITLE
[In-App Purchases] Adapt to the new MobilePay create order request with original_transaction_id

### ISSUE THREAD

**Issue by toupper** [woocommerce/woocommerce-ios#8939]
## Description
MobilePay adapted its implementation to the new [App Store Server API ](https://developer.apple.com/documentation/appstoreserverapi) to verify the validity of a transaction. With this, we do not need to send the receipt anymore, instead, we have to send the original transaction id of the purchase so it can be verified.

## Tasks
- [x] Pass the original transaction id parameter to the request, via `original_transaction_id`
- [x] Remove the receipt information from the request.
- [x] Clean code.
- [x] Adapt Unit tests.
