### ISSUE TITLE
[Product Multi-selection] Prepare for release

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#8945]
Closes #8888 

### Tasks M1 & M1.1:
- [x] Switch feature flag and deal with experimental toggle.
- [x] Confirm that UI Tests are updated
- [x] Confirm items and testing flows work as expected: pdfdoF-2pG-p2 
- [x] Release notes

**Comment by iamgabrielma** [comment]
Closed via https://github.com/woocommerce/woocommerce-ios/pull/9358
