### ISSUE TITLE
Make Manage Card Reader screen more reusable

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#9011]
## Description
We'll reuse the existing Manage Card Reader flow/screens for the new set up flow.

These could do with a refactor to make that reuse easier.

```[tasklist]
## Tasks
- [x] Remove reliance on storyboards
- [x] Rename Manage Card Reader code which we will reuse for Payment Settings Flows
- [x] Extract reused views
```
