### ISSUE TITLE
[Free Trial] Fill "Subscription" view with data

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#9061]
On the "Subscription" view:

# Tasks

- [x] Display the name of the current subscription
- [x] Handle the "Subscribe now" button. When writing this description, it's not determined if we should navigate the user to a web flow or show a dialog. See internal communication: pe5sF9-1fp-p2#comment-1826 - Probably a web view.
- [x] Confirm copy to show when the trial is not over.

**Comment by wzieba** [comment]
> When writing this description, it's not determined if we should navigate the user to a web flow or show a dialog.

We decided to go with a web flow for the first iterations. More info internally: https://wooengage.wordpress.com/2023/03/02/project-thread-free-trial/#comment-1944

I'll change the status to "ready.", but feel free to revert to "unclear requirements" if you have questions.
