### ISSUE TITLE
[Free Trial] Support "Report subscription issue" action

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#9063]
Handle "Report subscription issue" action.

# Tasks

- [ ] Ask for zendesk tags
- [ ] Implement new support data source 
- [ ] Update SupportForm to auto select option.

<img width=300 src=https://user-images.githubusercontent.com/5845095/222515498-320cc48c-c35c-46fc-b3e9-6f2b87234f16.png>
