### ISSUE TITLE
[Free Trial] Add tacks to subscription settings module

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#9064]
# Questions

- [ ] How many users are clicking on the plans section and upgrading to a paid plan from the app? 
- [ ] How many users are dismissing the webview without upgrading to a paid plan?

# Tasks

- [x] Define tack events
- [x] Implement track events

**Comment by Ecarrion** [comment]
Android "tap on upgrade now" event https://github.com/woocommerce/woocommerce-android/pull/8379#issuecomment-1461895779
