### ISSUE TITLE
[Free Trial] Fill banner with subscription data

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#9066]
# Tasks

- [ ] Control showing dashboard banner when the user is on a trial #9065
- [ ] Populate with current plan data #9061
- [ ] When tapping on the CTA, navigate user to the subscription settings view. pe5sF9-1fp-p2#comment-1826
