### ISSUE TITLE
Task: launch your store

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#9122]
Spike: pe5sF9-1d7-p2
Design: VyLr7LvKodHE4kINfBE7Lw-fi-1644%3A80179

![Image](https://user-images.githubusercontent.com/1945542/224926359-d64c986a-7bf1-4fb2-bcf5-d6caae37eb7f.png)
![Image](https://user-images.githubusercontent.com/1945542/224926360-d7a79f95-98af-438b-9e8e-87f82f5b690f.png)

## Subtasks

- [x] Show launch store main screen with a CTA that's no-op https://github.com/woocommerce/woocommerce-ios/pull/9123#event-8740979732
- [x] Networking & Yosemite: publish store action https://github.com/woocommerce/woocommerce-ios/pull/9140
- [x] UI integration and error handling for two cases https://github.com/woocommerce/woocommerce-ios/pull/9145
  - [x] Add a retry primary action to the unexpected error scenario https://github.com/woocommerce/woocommerce-ios/pull/9283
- [x] Live store screen when the task is complete https://github.com/woocommerce/woocommerce-ios/pull/9148
  - [x] Remove the URL scheme from the URL shown in the header https://github.com/woocommerce/woocommerce-ios/pull/9289
- [x] [Ref](https://github.com/woocommerce/woocommerce-ios/pull/9268#pullrequestreview-1353848985): after publishing a site, I tapped the Back to my store button but the modal would not be dismissed. I had to drag to dismiss the modal, but this works in landscape mode - Unable to reproduce closing based on this similar issue and discussion https://github.com/woocommerce/woocommerce-ios/pull/9292#issuecomment-1484721516
