### ISSUE TITLE
Store onboarding: support free trial sites

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#9141]
Design: VyLr7LvKodHE4kINfBE7Lw-fi-1644-82386

<img src="https://user-images.githubusercontent.com/1945542/226836845-bddc6ec4-b047-42fb-9a32-5ef2fce63ad5.png" width="300" />

## Subtasks

- [ ] Add a way to check if a site has a free trial (first check with Eagle to see if this is already implemented)
- [ ] Onboarding card: for a free trial site, manually add a "Launch store" task if it's not in the API response https://github.com/woocommerce/woocommerce-ios/pull/9315
- [ ] Launch store: add a top banner with a upsell CTA to upgrade to eCommerce plan
- [ ] Launch store > upsell: navigate to purchase eCommerce plan
