### ISSUE TITLE
[Free Trial] [Epic] User can upgrade plan from a native flow

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-ios#9205]
### Description

This epic is about allowing users to see details of eCommerce plans and make it easy for them to upgrade to a different plan directly in the app.

```[tasklist]
### Tasks
- [] https://github.com/woocommerce/woocommerce-ios/issues/9207
- 
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/9207
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/9208
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/9209
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/9206
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/9210
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/9211
```

<img src=https://user-images.githubusercontent.com/5845095/222517381-ab85efd7-839a-4659-af0c-a05ca6333b6a.png width=300>

**Comment by JorgeMucientes** [comment]
Closing this as part of a maintenance pass on the GitHub issue backlog. This issue matched the auto-close criteria for this pass: it has not been updated since 2023-03-17, is unassigned, is not labeled as a bug or high/medium priority, and does not appear to involve POS, payments, login, data loss, crash, security, vulnerability, auth, or fraud.

If this is still relevant, please comment with current details and we can reopen it or move it into Linear for triage.
