### ISSUE TITLE
[Free Trial] Release 1st Iteration

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#9251]
# Tasks

- [x] Remove conditional code under the feature flag
- [x] Add release notes
- [ ] Run test plan
