### ISSUE TITLE
[Mobile Payments] Add `mobile/payments/tap-to-pay` Universal Link support

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#9370]
## Description
So far in sTAP Away Milestone 2, we've added a set-up flow for Tap to Pay on iPhone. The other part of M2 is to inform users about TTPoI; currently it'll only be seen by users who visit the payments tab, or tap `Collect Payment` on an order.

We've decided to add support for a universal link which opens the Set up Tap to Pay on iPhone flow, which can then be used in marketing emails, JITMs, and other approaches to inform users about the feature and get them directly to the right place to get started.

The URL we will support is:
`https://woocommerce.com/mobile/payments/tap-to-pay`

When this is tapped from an email, or another link in iOS on a phone where the app is installed, it should open the app and navigate to the Set up Tap to Pay on iPhone flow.

```[tasklist]
## Tasks
- [x] Add support for the URL pattern to open the TTP flow
- [x] Show onboarding at the start of the TTP flow when required
- [x] Remove block on opening the flow before the background check is done
- [ ] Add information screen for when link is opened on a device running iOS15.x (or bump to the web?)
- [ ] Add information screen for when link is opened on a device that can't support TTP, regardless of OS version (or bump to web?)
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/9516
- [x] Enable feature flag
```
