### ISSUE TITLE
[Privacy Choices] Keep analytics choice state up to date

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#9611]
Make sure the "Analytics" choice always reflects the latest status of the [`me/settings`](https://href.li/?https://developer.wordpress.com/docs/api/1.1/post/me/settings/) endpoint.

# Tasks

- [x] Make sure to always sync the latest state when entering the privacy view
- [x] Make sure to commit the new state after changing selection
- [x] Show a notice + a retry when failing to get the latest selection state
- [x] Show a notice + a retry when failing to commit the new selection
- [x] Remove analytics tracking when toggling the state.
