### ISSUE TITLE
[Privacy Choices] Handle "Save" CTA

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#9615]
# Tasks

![Image](https://user-images.githubusercontent.com/562080/235852790-f3d16a3a-4d22-4b02-8bd6-76446bd78dda.png)

When the user taps on the "Save" CTA we should:

- [x] Fire a `POST` request to [`me/settings`](https://href.li/?https://developer.wordpress.com/docs/api/1.1/post/me/settings/) with the user selection
- [x] Opt-In / Out from tracks according to the user's selection.
- [x] After the request is successful, mark the banner as seen/presented.
- [x] Show a loading state while the request is being performed
- [x] Show an error notice with a retry button if the request fails.
- [x] Handle non-jp sites.
