### ISSUE TITLE
[Privacy Choices] Handle "Go to Settings" CTA

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#9617]
# UI

![Image](https://user-images.githubusercontent.com/562080/235853383-b741122c-42a9-45b8-9bfa-627081fa805a.png)

# Tasks

When the user taps on the "Go To Settings" CTA we should:

### If the user has made any change to the "Analytics" Selection:

- [ ] Fire a `POST` request to [`me/settings`](https://href.li/?https://developer.wordpress.com/docs/api/1.1/post/me/settings/) with the user selection.
- [ ] After the request is successful, mark the banner as seen/presented.
- [ ] After the request is successful, navigate the user to the privacy settings screen.

### If the user has not made any change to the "Analytics" Selection:

- [ ] Mark the banner as seen/presented.
- [ ] Navigate the user to the privacy settings screen.

# To Discuss
- [ ] How should we wait on the banner while the request is being performed?
- [ ] What should we do if the request fails?
