### ISSUE TITLE
Store creation: update how we wait for the new site to be ready for the timeout issue

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#9733]
## Why

Since May 4, we started seeing most created sites timing out while waiting for the site to be a Jetpack/Woo site (more details in pe5sF9-1vz-p2). This means that most of the merchants see a timeout alert in the app, instead of the success state where they're navigated to the newly created site. Based on Dale@WPCOM's advice pe5sF9-1vz-p2#comment-2166, we can update how we wait for the site from polling from `me/sites` to `sites/:siteId/plugins` (to check if Jetpack-the-plugin is active) & `sites/:siteId` (to fetch site name etc.) as a workaround. We hope the backend team also looks into why the sync failure has been surging.

## How

In iOS, we currently calls `me/sites` periodically to check if the site is ready or not. We're updating this endpoint to `sites/:siteId/plugins` to wait for Jetpack-the-plugin to be active. When it's active, we then call `sites/:siteId` to sync the basic site info like the site name. Some properties of the site might still be out of sync, and we should log the error `site_creation_properties_out_of_sync` like before.

## Subtasks

- [x] Update how we wait for the site to be ready https://github.com/woocommerce/woocommerce-ios/pull/9731
- [ ] Also wait for the WooCommercec plugin to be active
- [ ] Remove extra site plugins call after retrying site info
