### ISSUE TITLE
Activate: Improve sharing experience

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#9785]
This task aims to improve the sharing experience for new merchants so that they can start selling and getting their first orders.

- [x] #9792 (Dropped this task as we decided to not add a local store onboarding task)
- [x] Celebratory screen after creating the first product #9790 
- [x] #9788
- [x] Swipe-to-share a product #9799 
- [x] Share store #9796 
- [x] #9817
- [x] AI-generated share content #9867 
- [x] ~A/B experiments~ (dropped this since it's related to #9792 
- [x] Analytics

Internal reference: pe5sF9-1xq-p2.
