### ISSUE TITLE
Activate: Add AI support for sharing product messages

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#9867]
Part of #9785.

- [x] New feature flag for AI Generated product messages https://github.com/woocommerce/woocommerce-ios/pull/9873
- [x] Update `ProductStore` and `ProductAction` to generate sharing message based on product URL #9872 
- [x] Add coordinator to switch between AI generated sharing messages and the basic sharing sheet https://github.com/woocommerce/woocommerce-ios/pull/9875 , https://github.com/woocommerce/woocommerce-ios/pull/9880
- [x] Update UI to show product sharing message AI generation for eligible sites #9885
- [x] Update prompt to include product name, description and product URL for improved generation #9921
- [x] Analytics #9912
