### ISSUE TITLE
Show a bottom sheet the very first time users use this "write it for me" AI feature about reviewing the generated content (design NMncL2ViLjomfLhuyEhVM1-fi-219_59788)

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#9934]
<img width="320" src="https://github.com/woocommerce/woocommerce-ios/assets/524475/e03c2746-ba35-4938-8f0d-076dfc7caa04"/>

Design - NMncL2ViLjomfLhuyEhVM1-fi-219_59788

- [x] Build the celebration view using SwiftUI #9939
    - [ ] Add dark mode illustration once available 9998
- [x] Add user defaults to track whether AI product description generation is being used for the first time #9940
- [x] Show the celebration view after the user applies the AI-generated product description #9966
