### ISSUE TITLE
Order fulfillment: "Add Tracking" button missing from the Order Details screen

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#996]
As part of the i8 designs, the Order Details screen should have an "Add Tracking" button.

<img width="438" alt="Screenshot 2019-05-28 at 10 10 42 AM" src="https://user-images.githubusercontent.com/2722505/58445862-f3c99b00-8130-11e9-9351-edd266ee6c03.png">

- [ ] Include a "Add Tracking" button
- [ ] Update the order of the sections. The trackings should be displayed right before Order Notes
- [ ] Add a Tracks event: `order_detail_tracking_add_tracking_button_tapped`

**Comment by ctarda** [comment]
Closing because it was implemented in #998
